/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_timer_2_timer(void);
static void widget_timer_timer(void);

hmi_widget_func_t hmi_window_6C6F676F_event_funcs[]={
{"timer_2_timer",(void *)widget_timer_2_timer},
{"timer_timer",(void *)widget_timer_timer},
{NULL,NULL}
};

static void widget_timer_2_timer(void)
{
	u8 __hmi_var_67 = (*(u8 *)hmidb_get_data_value("system.IsMouseDown"));
	u8 __old___hmi_var_67 = __hmi_var_67;
	{
#line 1 "控件:timer_2,事件:timer"
if(__hmi_var_67)
    __hmi_var_67 = 0;
else
{   //关闭除主界面所有窗口
    hmi_window_hide("logo");
    hmi_window_hide("win_get_pack");
    hmi_window_hide("win_box_tip");
    hmi_window_hide("win_input_password");
    hmi_window_hide("win_admin");
    hmi_window_hide("TextKeyboard6");
    hmi_window_hide("win_cabinet_set");
    hmi_window_hide("win_tip");
    hmi_window_hide("win_box_set");
    hmi_window_hide("win_box_operate");
    hmi_window_hide("win_sender_psd");
    hmi_window_hide("win_wait_tip");
    hmi_window_hide("win_input_send_tm");
    hmi_window_hide("win_input_pnum_type");
    hmi_window_hide("win_save_pack_next_tip");
    hmi_window_hide("NumKeyboard3");
    hmi_window_hide("win_sys_set");
    hmi_window_hide("win_change_admin_psd");
    hmi_window_hide("win_sys_set_time");
    hmi_window_hide("win_sys_reset");
    hmi_window_hide("win_disp_box_status");
    hmi_window_hide("win_history");
    hmi_window_hide("win_history_detail");
    hmi_window_hide("TextKeyboard6");
    hmi_window_hide("NumKeyboard3");
    hmi_window_show("win_ad");//显示广告
}

	}
{
	if(__old___hmi_var_67 != __hmi_var_67)
	{
		hmidb_set_data_value("system.IsMouseDown",&__hmi_var_67);
	}
}
}

static void widget_timer_timer(void)
{
	u8 __hmi_var_68 = (*(u8 *)hmidb_get_data_value("picture_ctrl.logo_ctrl"));
	u8 __old___hmi_var_68 = __hmi_var_68;
	u8 __hmi_var_69 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_logo_pic_num"));
	u8 __old___hmi_var_69 = __hmi_var_69;
	u8 __hmi_var_70 = (*(u8 *)hmidb_get_data_value("sys_set.heart_count"));
	u8 __old___hmi_var_70 = __hmi_var_70;
	u8 __hmi_var_71 = (*(u8 *)hmidb_get_data_value("sys_set.heart_delay_count"));
	u8 __old___hmi_var_71 = __hmi_var_71;
	u8 __hmi_var_72 = (*(u8 *)hmidb_get_data_value("sys_set.send_pack_flag"));
	u8 __old___hmi_var_72 = __hmi_var_72;
	u8 __hmi_var_73 = (*(u8 *)hmidb_get_data_value("sys_set.hear_send_count"));
	u8 __old___hmi_var_73 = __hmi_var_73;
	u8 * __hmi_var_74 = ((u8 *)hmidb_get_data_value("sys_set.send_pack"));
		char * __hmi_var_75 = ((char *)hmidb_get_data_value("sys_set.station_add"));
		char * __hmi_var_76 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:timer,事件:timer"
__hmi_var_68++;
if(__hmi_var_68 == __hmi_var_69)
__hmi_var_68 = 1;

__hmi_var_70++;
__hmi_var_71++;
if((__hmi_var_72 == 0) && (__hmi_var_70 == 5))//20s,到计时时间，发送一个心跳包
{
    unsigned char data_buf[2];
    data_buf[0] = '0';
    data_buf[1] = __hmi_var_73++;
    __hmi_var_70 = 0;
    package_send_pack(__hmi_var_74 , __hmi_var_75 ,HEART_BEAT , data_buf , 2);
    __hmi_var_72 = 1;//置发送标志位，开始发送
debug_printf("system OK\n");

}

if(__hmi_var_71 > 11)//超时未返回心跳包，认为通讯中断
{
    strcpy(__hmi_var_76,"通讯中断");
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_76);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_75);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_74);
	if(__old___hmi_var_73 != __hmi_var_73)
	{
		hmidb_set_data_value("sys_set.hear_send_count",&__hmi_var_73);
		__old___hmi_var_73 = __hmi_var_73;
	}
	if(__old___hmi_var_72 != __hmi_var_72)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_72);
		__old___hmi_var_72 = __hmi_var_72;
	}
	if(__old___hmi_var_71 != __hmi_var_71)
	{
		hmidb_set_data_value("sys_set.heart_delay_count",&__hmi_var_71);
		__old___hmi_var_71 = __hmi_var_71;
	}
	if(__old___hmi_var_70 != __hmi_var_70)
	{
		hmidb_set_data_value("sys_set.heart_count",&__hmi_var_70);
		__old___hmi_var_70 = __hmi_var_70;
	}
	if(__old___hmi_var_69 != __hmi_var_69)
	{
		hmidb_set_data_value("picture_ctrl.win_logo_pic_num",&__hmi_var_69);
		__old___hmi_var_69 = __hmi_var_69;
	}
	if(__old___hmi_var_68 != __hmi_var_68)
	{
		hmidb_set_data_value("picture_ctrl.logo_ctrl",&__hmi_var_68);
		__old___hmi_var_68 = __hmi_var_68;
	}
}

    hmi_window_show("win_tip");
    __hmi_var_71=0;
}


	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_76);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_75);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_74);
	if(__old___hmi_var_73 != __hmi_var_73)
	{
		hmidb_set_data_value("sys_set.hear_send_count",&__hmi_var_73);
	}
	if(__old___hmi_var_72 != __hmi_var_72)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_72);
	}
	if(__old___hmi_var_71 != __hmi_var_71)
	{
		hmidb_set_data_value("sys_set.heart_delay_count",&__hmi_var_71);
	}
	if(__old___hmi_var_70 != __hmi_var_70)
	{
		hmidb_set_data_value("sys_set.heart_count",&__hmi_var_70);
	}
	if(__old___hmi_var_69 != __hmi_var_69)
	{
		hmidb_set_data_value("picture_ctrl.win_logo_pic_num",&__hmi_var_69);
	}
	if(__old___hmi_var_68 != __hmi_var_68)
	{
		hmidb_set_data_value("picture_ctrl.logo_ctrl",&__hmi_var_68);
	}
}
}

#endif
