/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_mulpicture_index(void *value);

hmi_widget_func_t hmi_window_6C6F676F_prop_funcs[]={
{"mulpicture_index",(void *)widget_set_mulpicture_index},
{NULL,NULL}
};

static int widget_set_mulpicture_index(void *value)
{
	static void *__hmi_var_77_ptr;
	u8 __hmi_var_77 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.logo_ctrl",&__hmi_var_77_ptr));
#line 1 "¿Ø¼þ:mulpicture,ÊôÐÔ:index"
	u8 __hmi_retval = (u8)(__hmi_var_77-1);
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

#endif
