/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_IC_check_script(void);
static void widget_recv_pack_check_script(void);
static void widget_send_pack_check_script(void);
static void widget_send_tm_check_script(void);
static void widget_get_pack_4_click(void);
static void widget_admin_btn_click(void);
static void widget_get_pack_2_click(void);
static void widget_get_pack_3_click(void);
static void widget_window_open(void);

hmi_widget_func_t hmi_window_6D61696E_event_funcs[]={
{"IC_check_script",(void *)widget_IC_check_script},
{"recv_pack_check_script",(void *)widget_recv_pack_check_script},
{"send_pack_check_script",(void *)widget_send_pack_check_script},
{"send_tm_check_script",(void *)widget_send_tm_check_script},
{"get_pack_4_click",(void *)widget_get_pack_4_click},
{"admin_btn_click",(void *)widget_admin_btn_click},
{"get_pack_2_click",(void *)widget_get_pack_2_click},
{"get_pack_3_click",(void *)widget_get_pack_3_click},
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_IC_check_script(void)
{
	u8 __hmi_var_1 = (*(u8 *)hmidb_get_data_value("system.IsMouseDown"));
	u8 __old___hmi_var_1 = __hmi_var_1;
	u16 __hmi_var_2 = (*(u16 *)hmidb_get_data_value("ARM_info.user_id0"));
	u16 __old___hmi_var_2 = __hmi_var_2;
	u16 __hmi_var_3 = (*(u16 *)hmidb_get_data_value("ARM_info.user_id1"));
	u16 __old___hmi_var_3 = __hmi_var_3;
	u8 __hmi_var_4 = (*(u8 *)hmidb_get_data_value("sys_set.user_ic_enable_flag"));
	u8 __old___hmi_var_4 = __hmi_var_4;
	char * __hmi_var_5 = ((char *)hmidb_get_data_value("box_msg.user_id"));
		u32 __hmi_var_6 = (*(u32 *)hmidb_get_data_value("system.CurDateTime"));
	u32 __old___hmi_var_6 = __hmi_var_6;
	u16 __hmi_var_7 = (*(u16 *)hmidb_get_data_value("ARM_info.station_num"));
	u16 __old___hmi_var_7 = __hmi_var_7;
	u16 __hmi_var_8 = (*(u16 *)hmidb_get_data_value("ARM_info.station_port"));
	u16 __old___hmi_var_8 = __hmi_var_8;
	u16 __hmi_var_9 = (*(u16 *)hmidb_get_data_value("ARM_info.back_comm"));
	u16 __old___hmi_var_9 = __hmi_var_9;
	u16 __hmi_var_10 = (*(u16 *)hmidb_get_data_value("ARM_info.send_comm"));
	u16 __old___hmi_var_10 = __hmi_var_10;
	char * __hmi_var_11 = ((char *)hmidb_get_data_value("picture_ctrl.open_box_tip"));
		u8 * __hmi_var_12 = ((u8 *)hmidb_get_data_value("sys_set.send_pack"));
		char * __hmi_var_13 = ((char *)hmidb_get_data_value("sys_set.station_add"));
		u8 __hmi_var_14 = (*(u8 *)hmidb_get_data_value("sys_set.send_pack_flag"));
	u8 __old___hmi_var_14 = __hmi_var_14;
	char * __hmi_var_15 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		char * __hmi_var_16 = ((char *)hmidb_get_data_value("picture_ctrl.win_wait_tip"));
		u8 __hmi_var_17 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_wait_sw"));
	u8 __old___hmi_var_17 = __hmi_var_17;
	u16 __hmi_var_18 = (*(u16 *)hmidb_get_data_value("ARM_info.user_id_flag"));
	u16 __old___hmi_var_18 = __hmi_var_18;
	{
#line 1 "控件:IC_check,事件:script"
unsigned char IC_buf[12];
unsigned long IC_data;//设定一个32位的数
int i;
__hmi_var_1 = 1;
hmi_window_hide("win_ad");//隐藏广告窗口
IC_buf[0] = __hmi_var_2>>8;
IC_buf[1] = __hmi_var_2%256;
IC_buf[2] = __hmi_var_3>>8;
IC_buf[3] = __hmi_var_3%256;

IC_data = (unsigned long)IC_buf[0]*16777216 + (unsigned long)IC_buf[1]*65536 + (unsigned long)IC_buf[2]*256 + (unsigned long)IC_buf[3];
debug_printf("IC_data = %ld\n",IC_data);
debug_printf("IC_buf = %d %d %d %d\n",IC_buf[0] , IC_buf[1] , IC_buf[2] , IC_buf[3]);
memset(IC_buf , 0 , 12);//清空buf，方便装入ASCII值
for(i=0;i<10;i++)
{
    IC_buf[9-i] = IC_data%10 + '0';
    IC_data = IC_data/10;
}
debug_printf("recv IC OK\n");
debug_printf(IC_buf);
debug_printf("\n");
if(__hmi_var_4 == 1)//用户IC
{
    BOX_MSG box_info;
    int data_len;
    unsigned char data_buf[sizeof(USER_INFO)];
    memcpy(__hmi_var_5 , IC_buf , USERID_LENGTH);//将ID卡号复制到用户ID信息中
    if(1 == read_box_info_user_id(__hmi_var_5 , &box_info))
    {
    //密码正确，执行开箱操作，同时发送数据给服务器
    //write_box_info(&box_info);
    HISTORY_MSG history_info;
    memcpy((char *)&history_info.box_info , (char *)&box_info , sizeof(BOX_MSG));//复制信息到历史记录中
    history_info.box_info.status = BOX_IDLE;//为防止记录与GPRS协议冲突，这里一律认为用户存物
    history_info.data_time = __hmi_var_6;//记录时间
    write_history_info(&history_info);

    __hmi_var_7 = box_info.station_num;
    __hmi_var_8 = box_info.station_port;
    __hmi_var_9 = 0;
    __hmi_var_10 = 1;
    memset(__hmi_var_11,0,30);
    memcpy(__hmi_var_11 , box_info.virtualnumber,VIRTUAL_NUM_LENGTH);
    strcat(__hmi_var_11 ,"号箱门已开");
    {
	if(__old___hmi_var_18 != __hmi_var_18)
	{
		hmidb_set_data_value("ARM_info.user_id_flag",&__hmi_var_18);
		__old___hmi_var_18 = __hmi_var_18;
	}
	if(__old___hmi_var_17 != __hmi_var_17)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_sw",&__hmi_var_17);
		__old___hmi_var_17 = __hmi_var_17;
	}
		hmidb_set_data_value("picture_ctrl.win_wait_tip",__hmi_var_16);
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_15);
	if(__old___hmi_var_14 != __hmi_var_14)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_14);
		__old___hmi_var_14 = __hmi_var_14;
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_13);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_12);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_11);
	if(__old___hmi_var_10 != __hmi_var_10)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_10);
		__old___hmi_var_10 = __hmi_var_10;
	}
	if(__old___hmi_var_9 != __hmi_var_9)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_9);
		__old___hmi_var_9 = __hmi_var_9;
	}
	if(__old___hmi_var_8 != __hmi_var_8)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_8);
		__old___hmi_var_8 = __hmi_var_8;
	}
	if(__old___hmi_var_7 != __hmi_var_7)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_7);
		__old___hmi_var_7 = __hmi_var_7;
	}
	if(__old___hmi_var_6 != __hmi_var_6)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_6);
		__old___hmi_var_6 = __hmi_var_6;
	}
		hmidb_set_data_value("box_msg.user_id",__hmi_var_5);
	if(__old___hmi_var_4 != __hmi_var_4)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_4);
		__old___hmi_var_4 = __hmi_var_4;
	}
	if(__old___hmi_var_3 != __hmi_var_3)
	{
		hmidb_set_data_value("ARM_info.user_id1",&__hmi_var_3);
		__old___hmi_var_3 = __hmi_var_3;
	}
	if(__old___hmi_var_2 != __hmi_var_2)
	{
		hmidb_set_data_value("ARM_info.user_id0",&__hmi_var_2);
		__old___hmi_var_2 = __hmi_var_2;
	}
	if(__old___hmi_var_1 != __hmi_var_1)
	{
		hmidb_set_data_value("system.IsMouseDown",&__hmi_var_1);
		__old___hmi_var_1 = __hmi_var_1;
	}
}

    hmi_window_show("win_box_tip");  

    data_len = package_user_data_pack(data_buf , CLEAR_ASK , &box_info);//封装数据部分
    package_send_pack(__hmi_var_12 , __hmi_var_13 ,GETOUT_USER_INFO , data_buf , data_len);//封装整包
    __hmi_var_14 = 1;//发送包
  
    }else
    {
    strcpy(__hmi_var_15 , "卡号错误，请核对后重试");
    {
	if(__old___hmi_var_18 != __hmi_var_18)
	{
		hmidb_set_data_value("ARM_info.user_id_flag",&__hmi_var_18);
		__old___hmi_var_18 = __hmi_var_18;
	}
	if(__old___hmi_var_17 != __hmi_var_17)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_sw",&__hmi_var_17);
		__old___hmi_var_17 = __hmi_var_17;
	}
		hmidb_set_data_value("picture_ctrl.win_wait_tip",__hmi_var_16);
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_15);
	if(__old___hmi_var_14 != __hmi_var_14)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_14);
		__old___hmi_var_14 = __hmi_var_14;
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_13);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_12);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_11);
	if(__old___hmi_var_10 != __hmi_var_10)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_10);
		__old___hmi_var_10 = __hmi_var_10;
	}
	if(__old___hmi_var_9 != __hmi_var_9)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_9);
		__old___hmi_var_9 = __hmi_var_9;
	}
	if(__old___hmi_var_8 != __hmi_var_8)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_8);
		__old___hmi_var_8 = __hmi_var_8;
	}
	if(__old___hmi_var_7 != __hmi_var_7)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_7);
		__old___hmi_var_7 = __hmi_var_7;
	}
	if(__old___hmi_var_6 != __hmi_var_6)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_6);
		__old___hmi_var_6 = __hmi_var_6;
	}
		hmidb_set_data_value("box_msg.user_id",__hmi_var_5);
	if(__old___hmi_var_4 != __hmi_var_4)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_4);
		__old___hmi_var_4 = __hmi_var_4;
	}
	if(__old___hmi_var_3 != __hmi_var_3)
	{
		hmidb_set_data_value("ARM_info.user_id1",&__hmi_var_3);
		__old___hmi_var_3 = __hmi_var_3;
	}
	if(__old___hmi_var_2 != __hmi_var_2)
	{
		hmidb_set_data_value("ARM_info.user_id0",&__hmi_var_2);
		__old___hmi_var_2 = __hmi_var_2;
	}
	if(__old___hmi_var_1 != __hmi_var_1)
	{
		hmidb_set_data_value("system.IsMouseDown",&__hmi_var_1);
		__old___hmi_var_1 = __hmi_var_1;
	}
}

    hmi_window_show("win_tip");    
    }

}
else//送货员IC
{
    SENDER_INFO sender_msg;
__hmi_var_4 = 1;//用户IC使能置1，防止多次进入送货员模式
memset((unsigned char *)&sender_msg , 0xff , sizeof(SENDER_INFO));

sender_msg.flag = SENDER_ASK;//标志，请求权限
memcpy(sender_msg.send_id , IC_buf , SEND_NUM_LENGTH);//IC卡号复制

package_send_pack(__hmi_var_12 , __hmi_var_13 , SENDER_CONFIRM , (unsigned char *)&sender_msg , sizeof(SENDER_INFO));

__hmi_var_14 = 1;
hmi_window_hide("win_sender_psd");
strcpy(__hmi_var_16,"后台处理中，请耐心等待");
__hmi_var_17 = 0;
__hmi_var_4 = 0;
{
	if(__old___hmi_var_18 != __hmi_var_18)
	{
		hmidb_set_data_value("ARM_info.user_id_flag",&__hmi_var_18);
		__old___hmi_var_18 = __hmi_var_18;
	}
	if(__old___hmi_var_17 != __hmi_var_17)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_sw",&__hmi_var_17);
		__old___hmi_var_17 = __hmi_var_17;
	}
		hmidb_set_data_value("picture_ctrl.win_wait_tip",__hmi_var_16);
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_15);
	if(__old___hmi_var_14 != __hmi_var_14)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_14);
		__old___hmi_var_14 = __hmi_var_14;
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_13);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_12);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_11);
	if(__old___hmi_var_10 != __hmi_var_10)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_10);
		__old___hmi_var_10 = __hmi_var_10;
	}
	if(__old___hmi_var_9 != __hmi_var_9)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_9);
		__old___hmi_var_9 = __hmi_var_9;
	}
	if(__old___hmi_var_8 != __hmi_var_8)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_8);
		__old___hmi_var_8 = __hmi_var_8;
	}
	if(__old___hmi_var_7 != __hmi_var_7)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_7);
		__old___hmi_var_7 = __hmi_var_7;
	}
	if(__old___hmi_var_6 != __hmi_var_6)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_6);
		__old___hmi_var_6 = __hmi_var_6;
	}
		hmidb_set_data_value("box_msg.user_id",__hmi_var_5);
	if(__old___hmi_var_4 != __hmi_var_4)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_4);
		__old___hmi_var_4 = __hmi_var_4;
	}
	if(__old___hmi_var_3 != __hmi_var_3)
	{
		hmidb_set_data_value("ARM_info.user_id1",&__hmi_var_3);
		__old___hmi_var_3 = __hmi_var_3;
	}
	if(__old___hmi_var_2 != __hmi_var_2)
	{
		hmidb_set_data_value("ARM_info.user_id0",&__hmi_var_2);
		__old___hmi_var_2 = __hmi_var_2;
	}
	if(__old___hmi_var_1 != __hmi_var_1)
	{
		hmidb_set_data_value("system.IsMouseDown",&__hmi_var_1);
		__old___hmi_var_1 = __hmi_var_1;
	}
}

hmi_window_show("win_wait_tip");    
}

__hmi_var_18 = 0;

	}
{
	if(__old___hmi_var_18 != __hmi_var_18)
	{
		hmidb_set_data_value("ARM_info.user_id_flag",&__hmi_var_18);
	}
	if(__old___hmi_var_17 != __hmi_var_17)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_sw",&__hmi_var_17);
	}
		hmidb_set_data_value("picture_ctrl.win_wait_tip",__hmi_var_16);
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_15);
	if(__old___hmi_var_14 != __hmi_var_14)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_14);
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_13);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_12);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_11);
	if(__old___hmi_var_10 != __hmi_var_10)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_10);
	}
	if(__old___hmi_var_9 != __hmi_var_9)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_9);
	}
	if(__old___hmi_var_8 != __hmi_var_8)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_8);
	}
	if(__old___hmi_var_7 != __hmi_var_7)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_7);
	}
	if(__old___hmi_var_6 != __hmi_var_6)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_6);
	}
		hmidb_set_data_value("box_msg.user_id",__hmi_var_5);
	if(__old___hmi_var_4 != __hmi_var_4)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_4);
	}
	if(__old___hmi_var_3 != __hmi_var_3)
	{
		hmidb_set_data_value("ARM_info.user_id1",&__hmi_var_3);
	}
	if(__old___hmi_var_2 != __hmi_var_2)
	{
		hmidb_set_data_value("ARM_info.user_id0",&__hmi_var_2);
	}
	if(__old___hmi_var_1 != __hmi_var_1)
	{
		hmidb_set_data_value("system.IsMouseDown",&__hmi_var_1);
	}
}
}

static void widget_recv_pack_check_script(void)
{
	u8 __hmi_var_19 = (*(u8 *)hmidb_get_data_value("sys_set.heart_delay_count"));
	u8 __old___hmi_var_19 = __hmi_var_19;
	u8 __hmi_var_20 = (*(u8 *)hmidb_get_data_value("sys_set.recv_pack_flag"));
	u8 __old___hmi_var_20 = __hmi_var_20;
	u8 * __hmi_var_21 = ((u8 *)hmidb_get_data_value("sys_set.recv_pack"));
		char * __hmi_var_22 = ((char *)hmidb_get_data_value("sys_set.station_add"));
		char * __hmi_var_23 = ((char *)hmidb_get_data_value("box_msg.send_num"));
		char * __hmi_var_24 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		u32 __hmi_var_25 = (*(u32 *)hmidb_get_data_value("system.CurDateTime"));
	u32 __old___hmi_var_25 = __hmi_var_25;
	u16 __hmi_var_26 = (*(u16 *)hmidb_get_data_value("ARM_info.station_num"));
	u16 __old___hmi_var_26 = __hmi_var_26;
	u16 __hmi_var_27 = (*(u16 *)hmidb_get_data_value("ARM_info.station_port"));
	u16 __old___hmi_var_27 = __hmi_var_27;
	u16 __hmi_var_28 = (*(u16 *)hmidb_get_data_value("ARM_info.back_comm"));
	u16 __old___hmi_var_28 = __hmi_var_28;
	u16 __hmi_var_29 = (*(u16 *)hmidb_get_data_value("ARM_info.send_comm"));
	u16 __old___hmi_var_29 = __hmi_var_29;
	char * __hmi_var_30 = ((char *)hmidb_get_data_value("picture_ctrl.open_box_tip"));
		u8 __hmi_var_31 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_save_next_flag"));
	u8 __old___hmi_var_31 = __hmi_var_31;
	char * __hmi_var_32 = ((char *)hmidb_get_data_value("sys_set.admin_psd"));
		u8 __hmi_var_33 = (*(u8 *)hmidb_get_data_value("sys_set.box_num"));
	u8 __old___hmi_var_33 = __hmi_var_33;
	u8 __hmi_var_34 = (*(u8 *)hmidb_get_data_value("sys_set.init_flag"));
	u8 __old___hmi_var_34 = __hmi_var_34;
	u8 * __hmi_var_35 = ((u8 *)hmidb_get_data_value("sys_set.send_pack"));
		u8 __hmi_var_36 = (*(u8 *)hmidb_get_data_value("sys_set.send_pack_flag"));
	u8 __old___hmi_var_36 = __hmi_var_36;
	{
#line 1 "控件:recv_pack_check,事件:script"
unsigned char recv_buf[128];
PACK_HEAD_INFO *pack_head_msg;
unsigned char *data_buf;//指向数据部分的指针
BOX_MSG box_info;
__hmi_var_19 = 0;//有数据返回

__hmi_var_20 = 0;//接收标志置零，便于下次接收
{
	if(__old___hmi_var_36 != __hmi_var_36)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_36);
		__old___hmi_var_36 = __hmi_var_36;
	}
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_35);
	if(__old___hmi_var_34 != __hmi_var_34)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_34);
		__old___hmi_var_34 = __hmi_var_34;
	}
	if(__old___hmi_var_33 != __hmi_var_33)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_33);
		__old___hmi_var_33 = __hmi_var_33;
	}
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_32);
	if(__old___hmi_var_31 != __hmi_var_31)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_31);
		__old___hmi_var_31 = __hmi_var_31;
	}
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_30);
	if(__old___hmi_var_29 != __hmi_var_29)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_29);
		__old___hmi_var_29 = __hmi_var_29;
	}
	if(__old___hmi_var_28 != __hmi_var_28)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_28);
		__old___hmi_var_28 = __hmi_var_28;
	}
	if(__old___hmi_var_27 != __hmi_var_27)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_27);
		__old___hmi_var_27 = __hmi_var_27;
	}
	if(__old___hmi_var_26 != __hmi_var_26)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_26);
		__old___hmi_var_26 = __hmi_var_26;
	}
	if(__old___hmi_var_25 != __hmi_var_25)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_25);
		__old___hmi_var_25 = __hmi_var_25;
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_24);
		hmidb_set_data_value("box_msg.send_num",__hmi_var_23);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_22);
		hmidb_set_data_value("sys_set.recv_pack",__hmi_var_21);
	if(__old___hmi_var_20 != __hmi_var_20)
	{
		hmidb_set_data_value("sys_set.recv_pack_flag",&__hmi_var_20);
		__old___hmi_var_20 = __hmi_var_20;
	}
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.heart_delay_count",&__hmi_var_19);
		__old___hmi_var_19 = __hmi_var_19;
	}
}


debug_printf("heart_delay_count = 0;recv_pack_flag = 0\n");

memcpy(recv_buf,__hmi_var_21,128);//复制buf
ex_pack_head_msg.comm_type = 'A';

pack_head_msg = (PACK_HEAD_INFO *)recv_buf;//指针指向包头
if(0 != memcmp(pack_head_msg->cabinet_num , __hmi_var_22 , CAB_NUM_LEN))
{
    return;//站号不对，直接退出
}
data_buf = &recv_buf[sizeof(PACK_HEAD_INFO)];//指向数据部分
switch(pack_head_msg->comm_type)
{
    case HEART_BEAT:
          
        break;
    case SENDER_CONFIRM: 
        //运货员信息确认
        hmi_window_hide("win_sender_psd");
        hmi_window_hide("win_wait_tip");//关闭相关窗口
        if(1 == confirm_sender(data_buf , __hmi_var_23))
        {
            //运货员确认成功，显示下一个窗口，提示输入运单号或刷条码
            hmi_window_show("win_input_send_tm");
        }
        else
        {
            //运货员确认失败，显示信息
            strcpy(__hmi_var_24,"卡号或密码错误，请核对后输入");
            {
	if(__old___hmi_var_36 != __hmi_var_36)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_36);
		__old___hmi_var_36 = __hmi_var_36;
	}
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_35);
	if(__old___hmi_var_34 != __hmi_var_34)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_34);
		__old___hmi_var_34 = __hmi_var_34;
	}
	if(__old___hmi_var_33 != __hmi_var_33)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_33);
		__old___hmi_var_33 = __hmi_var_33;
	}
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_32);
	if(__old___hmi_var_31 != __hmi_var_31)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_31);
		__old___hmi_var_31 = __hmi_var_31;
	}
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_30);
	if(__old___hmi_var_29 != __hmi_var_29)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_29);
		__old___hmi_var_29 = __hmi_var_29;
	}
	if(__old___hmi_var_28 != __hmi_var_28)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_28);
		__old___hmi_var_28 = __hmi_var_28;
	}
	if(__old___hmi_var_27 != __hmi_var_27)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_27);
		__old___hmi_var_27 = __hmi_var_27;
	}
	if(__old___hmi_var_26 != __hmi_var_26)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_26);
		__old___hmi_var_26 = __hmi_var_26;
	}
	if(__old___hmi_var_25 != __hmi_var_25)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_25);
		__old___hmi_var_25 = __hmi_var_25;
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_24);
		hmidb_set_data_value("box_msg.send_num",__hmi_var_23);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_22);
		hmidb_set_data_value("sys_set.recv_pack",__hmi_var_21);
	if(__old___hmi_var_20 != __hmi_var_20)
	{
		hmidb_set_data_value("sys_set.recv_pack_flag",&__hmi_var_20);
		__old___hmi_var_20 = __hmi_var_20;
	}
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.heart_delay_count",&__hmi_var_19);
		__old___hmi_var_19 = __hmi_var_19;
	}
}

            hmi_window_show("win_tip");
        }
        break;
    case SAVE_USER_INFO: 
        //存包时用户信息返回
        hmi_window_hide("win_wait_tip");//关闭相关窗口
        if(1 == save_pack_server_back(data_buf , &box_info))
        {
            HISTORY_MSG history_info;
            //信息完全正确，执行存储和开箱操作
            box_info.status = BOX_USED;//修改箱子状态

            memcpy((char *)&history_info.box_info , (char *)&box_info , sizeof(BOX_MSG));//复制信息到历史记录中
            history_info.data_time = __hmi_var_25;//记录时间

            write_box_info(&box_info);
            write_history_info(&history_info);
            __hmi_var_26 = box_info.station_num;
            __hmi_var_27 = box_info.station_port;
            __hmi_var_28 = 0;
            __hmi_var_29 = 1;
            memset(__hmi_var_30,0,30);
            memcpy(__hmi_var_30 , box_info.virtualnumber,VIRTUAL_NUM_LENGTH);
            strcat(__hmi_var_30 ,"号箱门已开");
            {
	if(__old___hmi_var_36 != __hmi_var_36)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_36);
		__old___hmi_var_36 = __hmi_var_36;
	}
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_35);
	if(__old___hmi_var_34 != __hmi_var_34)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_34);
		__old___hmi_var_34 = __hmi_var_34;
	}
	if(__old___hmi_var_33 != __hmi_var_33)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_33);
		__old___hmi_var_33 = __hmi_var_33;
	}
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_32);
	if(__old___hmi_var_31 != __hmi_var_31)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_31);
		__old___hmi_var_31 = __hmi_var_31;
	}
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_30);
	if(__old___hmi_var_29 != __hmi_var_29)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_29);
		__old___hmi_var_29 = __hmi_var_29;
	}
	if(__old___hmi_var_28 != __hmi_var_28)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_28);
		__old___hmi_var_28 = __hmi_var_28;
	}
	if(__old___hmi_var_27 != __hmi_var_27)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_27);
		__old___hmi_var_27 = __hmi_var_27;
	}
	if(__old___hmi_var_26 != __hmi_var_26)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_26);
		__old___hmi_var_26 = __hmi_var_26;
	}
	if(__old___hmi_var_25 != __hmi_var_25)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_25);
		__old___hmi_var_25 = __hmi_var_25;
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_24);
		hmidb_set_data_value("box_msg.send_num",__hmi_var_23);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_22);
		hmidb_set_data_value("sys_set.recv_pack",__hmi_var_21);
	if(__old___hmi_var_20 != __hmi_var_20)
	{
		hmidb_set_data_value("sys_set.recv_pack_flag",&__hmi_var_20);
		__old___hmi_var_20 = __hmi_var_20;
	}
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.heart_delay_count",&__hmi_var_19);
		__old___hmi_var_19 = __hmi_var_19;
	}
}

            hmi_window_show("win_box_tip");
            __hmi_var_31 = 1;//允许继续存物
        }else
        {
              //数据解析失败或服务器禁止开箱
            hmi_window_show("win_input_send_tm"); //进入单号输入界面
            strcpy(__hmi_var_24,"单号或手机号错误，请核对后输入");
            {
	if(__old___hmi_var_36 != __hmi_var_36)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_36);
		__old___hmi_var_36 = __hmi_var_36;
	}
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_35);
	if(__old___hmi_var_34 != __hmi_var_34)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_34);
		__old___hmi_var_34 = __hmi_var_34;
	}
	if(__old___hmi_var_33 != __hmi_var_33)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_33);
		__old___hmi_var_33 = __hmi_var_33;
	}
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_32);
	if(__old___hmi_var_31 != __hmi_var_31)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_31);
		__old___hmi_var_31 = __hmi_var_31;
	}
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_30);
	if(__old___hmi_var_29 != __hmi_var_29)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_29);
		__old___hmi_var_29 = __hmi_var_29;
	}
	if(__old___hmi_var_28 != __hmi_var_28)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_28);
		__old___hmi_var_28 = __hmi_var_28;
	}
	if(__old___hmi_var_27 != __hmi_var_27)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_27);
		__old___hmi_var_27 = __hmi_var_27;
	}
	if(__old___hmi_var_26 != __hmi_var_26)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_26);
		__old___hmi_var_26 = __hmi_var_26;
	}
	if(__old___hmi_var_25 != __hmi_var_25)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_25);
		__old___hmi_var_25 = __hmi_var_25;
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_24);
		hmidb_set_data_value("box_msg.send_num",__hmi_var_23);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_22);
		hmidb_set_data_value("sys_set.recv_pack",__hmi_var_21);
	if(__old___hmi_var_20 != __hmi_var_20)
	{
		hmidb_set_data_value("sys_set.recv_pack_flag",&__hmi_var_20);
		__old___hmi_var_20 = __hmi_var_20;
	}
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.heart_delay_count",&__hmi_var_19);
		__old___hmi_var_19 = __hmi_var_19;
	}
}

            hmi_window_show("win_tip");          
        }
        break;
    case GETOUT_USER_INFO: 
        //取包时服务器确认信息返回
        if(1 == getout_pack_server_back(data_buf , &box_info))//函数中已经改好了箱子信息，可以直接存储
        {
            write_box_info(&box_info);//修改箱子状态后重新写入
        }
        break;
    case RW_CAB_INFO://存取系统信息
        {
        CAB_INFO cab_msg;
        //读取当前系统信息
        memcpy(cab_msg.cabinet_num , __hmi_var_22 , GPRS_CAB_NUM_LEN);
        memcpy(cab_msg.admin_psd , __hmi_var_32 , GPRS_ADMIN_PSD_LENGTH);
        cab_msg.box_num = __hmi_var_33;

        if(RW_OK == rw_cab_server_back(data_buf , &cab_msg))
        {
            memcpy(__hmi_var_22 , cab_msg.cabinet_num , GPRS_CAB_NUM_LEN);
            memcpy(__hmi_var_32 , cab_msg.admin_psd , GPRS_ADMIN_PSD_LENGTH);
            __hmi_var_33 = cab_msg.box_num; //无论有没有修改系统信息，都可以更新一下
            if(cab_msg.restart_flag == RESTART)
            {
                __hmi_var_34 = 0;//下次开机时初始化箱子信息
            }
            {
	if(__old___hmi_var_36 != __hmi_var_36)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_36);
		__old___hmi_var_36 = __hmi_var_36;
	}
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_35);
	if(__old___hmi_var_34 != __hmi_var_34)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_34);
		__old___hmi_var_34 = __hmi_var_34;
	}
	if(__old___hmi_var_33 != __hmi_var_33)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_33);
		__old___hmi_var_33 = __hmi_var_33;
	}
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_32);
	if(__old___hmi_var_31 != __hmi_var_31)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_31);
		__old___hmi_var_31 = __hmi_var_31;
	}
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_30);
	if(__old___hmi_var_29 != __hmi_var_29)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_29);
		__old___hmi_var_29 = __hmi_var_29;
	}
	if(__old___hmi_var_28 != __hmi_var_28)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_28);
		__old___hmi_var_28 = __hmi_var_28;
	}
	if(__old___hmi_var_27 != __hmi_var_27)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_27);
		__old___hmi_var_27 = __hmi_var_27;
	}
	if(__old___hmi_var_26 != __hmi_var_26)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_26);
		__old___hmi_var_26 = __hmi_var_26;
	}
	if(__old___hmi_var_25 != __hmi_var_25)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_25);
		__old___hmi_var_25 = __hmi_var_25;
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_24);
		hmidb_set_data_value("box_msg.send_num",__hmi_var_23);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_22);
		hmidb_set_data_value("sys_set.recv_pack",__hmi_var_21);
	if(__old___hmi_var_20 != __hmi_var_20)
	{
		hmidb_set_data_value("sys_set.recv_pack_flag",&__hmi_var_20);
		__old___hmi_var_20 = __hmi_var_20;
	}
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.heart_delay_count",&__hmi_var_19);
		__old___hmi_var_19 = __hmi_var_19;
	}
}
  
            sys_save_params();//保存好系统信息    
            if(cab_msg.restart_flag == RESTART)
            {
                sys_shutdown(3);//重启系统
                return;
            }                 
        }else
        {
            cab_msg.flag = RW_ERR;
        }
        package_send_pack(__hmi_var_35 , __hmi_var_22 , RW_CAB_INFO , (unsigned char *)(&cab_msg) , sizeof(CAB_INFO));
        __hmi_var_36 = 1;//开始发送
        }
        break;
    case RW_USER_INFO://存取用户信息
        if(RW_OK == rw_pack_server_back(data_buf , &box_info))
        {
           package_user_data_pack(data_buf , RW_OK , &box_info); 
        }else
        {
            package_user_data_pack(data_buf , RW_ERR , &box_info);//封装数据
        }
        
        package_send_pack(__hmi_var_35 , __hmi_var_22 , RW_USER_INFO , data_buf , sizeof(USER_INFO));//数据打包
        __hmi_var_36 = 1;//开始发送
        break;

    case SERVER_OPEN_BOX://远程开箱
        {
            SERVER_OPEN_INFO server_open_msg;
            if(SERVER_OPEN_OK == server_open_box_back(data_buf , &server_open_msg , &box_info))//解析数据，把数据存放在server_open_msg，box_info中
            {
                //执行开箱操作
                __hmi_var_26 = box_info.station_num;
                __hmi_var_27 = box_info.station_port;
                __hmi_var_28 = 0;
                __hmi_var_29 = 1;               
            }
            package_send_pack(__hmi_var_35 , __hmi_var_22 , SERVER_OPEN_BOX , (unsigned char *)&server_open_msg , sizeof(SERVER_OPEN_INFO));//数据打包
            __hmi_var_36 = 1;//开始发送            
        }

        break;
    default: break;
}

memset(__hmi_var_21,0,128);

	}
{
	if(__old___hmi_var_36 != __hmi_var_36)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_36);
	}
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_35);
	if(__old___hmi_var_34 != __hmi_var_34)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_34);
	}
	if(__old___hmi_var_33 != __hmi_var_33)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_33);
	}
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_32);
	if(__old___hmi_var_31 != __hmi_var_31)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_31);
	}
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_30);
	if(__old___hmi_var_29 != __hmi_var_29)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_29);
	}
	if(__old___hmi_var_28 != __hmi_var_28)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_28);
	}
	if(__old___hmi_var_27 != __hmi_var_27)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_27);
	}
	if(__old___hmi_var_26 != __hmi_var_26)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_26);
	}
	if(__old___hmi_var_25 != __hmi_var_25)
	{
		hmidb_set_data_value("system.CurDateTime",&__hmi_var_25);
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_24);
		hmidb_set_data_value("box_msg.send_num",__hmi_var_23);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_22);
		hmidb_set_data_value("sys_set.recv_pack",__hmi_var_21);
	if(__old___hmi_var_20 != __hmi_var_20)
	{
		hmidb_set_data_value("sys_set.recv_pack_flag",&__hmi_var_20);
	}
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.heart_delay_count",&__hmi_var_19);
	}
}
}

static void widget_send_pack_check_script(void)
{
	u8 __hmi_var_37 = (*(u8 *)hmidb_get_data_value("sys_set.heart_count"));
	u8 __old___hmi_var_37 = __hmi_var_37;
	{
#line 1 "控件:send_pack_check,事件:script"
__hmi_var_37 = 0;//若有其他包发送，暂不发送心跳包

	}
{
	if(__old___hmi_var_37 != __hmi_var_37)
	{
		hmidb_set_data_value("sys_set.heart_count",&__hmi_var_37);
	}
}
}

static void widget_send_tm_check_script(void)
{
	u8 __hmi_var_38 = (*(u8 *)hmidb_get_data_value("sys_set.send_tm_enable_flag"));
	u8 __old___hmi_var_38 = __hmi_var_38;
	u16 __hmi_var_39 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id0"));
	u16 __old___hmi_var_39 = __hmi_var_39;
	u16 __hmi_var_40 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id1"));
	u16 __old___hmi_var_40 = __hmi_var_40;
	u16 __hmi_var_41 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id2"));
	u16 __old___hmi_var_41 = __hmi_var_41;
	u16 __hmi_var_42 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id3"));
	u16 __old___hmi_var_42 = __hmi_var_42;
	u16 __hmi_var_43 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id4"));
	u16 __old___hmi_var_43 = __hmi_var_43;
	u16 __hmi_var_44 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id5"));
	u16 __old___hmi_var_44 = __hmi_var_44;
	u16 __hmi_var_45 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id6"));
	u16 __old___hmi_var_45 = __hmi_var_45;
	u16 __hmi_var_46 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id7"));
	u16 __old___hmi_var_46 = __hmi_var_46;
	u16 __hmi_var_47 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id8"));
	u16 __old___hmi_var_47 = __hmi_var_47;
	u16 __hmi_var_48 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id9"));
	u16 __old___hmi_var_48 = __hmi_var_48;
	u16 __hmi_var_49 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id10"));
	u16 __old___hmi_var_49 = __hmi_var_49;
	u16 __hmi_var_50 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id11"));
	u16 __old___hmi_var_50 = __hmi_var_50;
	char * __hmi_var_51 = ((char *)hmidb_get_data_value("box_msg.send_id"));
		u16 __hmi_var_52 = (*(u16 *)hmidb_get_data_value("ARM_info.send_id_flag"));
	u16 __old___hmi_var_52 = __hmi_var_52;
	u8 __hmi_var_53 = (*(u8 *)hmidb_get_data_value("system.IsMouseDown"));
	u8 __old___hmi_var_53 = __hmi_var_53;
	{
#line 1 "控件:send_tm_check,事件:script"
char send_buf[24];
if(__hmi_var_38 == 1)
{
__hmi_var_38 = 0;
send_buf[0] = __hmi_var_39>>8;
send_buf[1] = __hmi_var_39%256;
send_buf[2] = __hmi_var_40>>8;
send_buf[3] = __hmi_var_40%256;
send_buf[4] = __hmi_var_41>>8;
send_buf[5] = __hmi_var_41%256;
send_buf[6] = __hmi_var_42>>8;
send_buf[7] = __hmi_var_42%256;
send_buf[8] = __hmi_var_43>>8;
send_buf[9] = __hmi_var_43%256;
send_buf[10] = __hmi_var_44>>8;
send_buf[11] = __hmi_var_44%256;
send_buf[12] = __hmi_var_45>>8;
send_buf[13] = __hmi_var_45%256;
send_buf[14] = __hmi_var_46>>8;
send_buf[15] = __hmi_var_46%256;
send_buf[16] = __hmi_var_47>>8;
send_buf[17] = __hmi_var_47%256;
send_buf[18] = __hmi_var_48>>8;
send_buf[19] = __hmi_var_48%256;
send_buf[20] = __hmi_var_49>>8;
send_buf[21] = __hmi_var_49%256;
send_buf[22] = __hmi_var_50>>8;
send_buf[23] = __hmi_var_50%256;
memcpy(__hmi_var_51,send_buf,24);
//memcpy(__hmi_var_51,"23456789011",10);
hmi_window_hide("win_input_send_tm");//关闭触发窗口
hmi_window_show("win_input_pnum_type");
}
__hmi_var_52 = 0;
__hmi_var_53 = 1;
	}
{
	if(__old___hmi_var_53 != __hmi_var_53)
	{
		hmidb_set_data_value("system.IsMouseDown",&__hmi_var_53);
	}
	if(__old___hmi_var_52 != __hmi_var_52)
	{
		hmidb_set_data_value("ARM_info.send_id_flag",&__hmi_var_52);
	}
		hmidb_set_data_value("box_msg.send_id",__hmi_var_51);
	if(__old___hmi_var_50 != __hmi_var_50)
	{
		hmidb_set_data_value("ARM_info.send_id11",&__hmi_var_50);
	}
	if(__old___hmi_var_49 != __hmi_var_49)
	{
		hmidb_set_data_value("ARM_info.send_id10",&__hmi_var_49);
	}
	if(__old___hmi_var_48 != __hmi_var_48)
	{
		hmidb_set_data_value("ARM_info.send_id9",&__hmi_var_48);
	}
	if(__old___hmi_var_47 != __hmi_var_47)
	{
		hmidb_set_data_value("ARM_info.send_id8",&__hmi_var_47);
	}
	if(__old___hmi_var_46 != __hmi_var_46)
	{
		hmidb_set_data_value("ARM_info.send_id7",&__hmi_var_46);
	}
	if(__old___hmi_var_45 != __hmi_var_45)
	{
		hmidb_set_data_value("ARM_info.send_id6",&__hmi_var_45);
	}
	if(__old___hmi_var_44 != __hmi_var_44)
	{
		hmidb_set_data_value("ARM_info.send_id5",&__hmi_var_44);
	}
	if(__old___hmi_var_43 != __hmi_var_43)
	{
		hmidb_set_data_value("ARM_info.send_id4",&__hmi_var_43);
	}
	if(__old___hmi_var_42 != __hmi_var_42)
	{
		hmidb_set_data_value("ARM_info.send_id3",&__hmi_var_42);
	}
	if(__old___hmi_var_41 != __hmi_var_41)
	{
		hmidb_set_data_value("ARM_info.send_id2",&__hmi_var_41);
	}
	if(__old___hmi_var_40 != __hmi_var_40)
	{
		hmidb_set_data_value("ARM_info.send_id1",&__hmi_var_40);
	}
	if(__old___hmi_var_39 != __hmi_var_39)
	{
		hmidb_set_data_value("ARM_info.send_id0",&__hmi_var_39);
	}
	if(__old___hmi_var_38 != __hmi_var_38)
	{
		hmidb_set_data_value("sys_set.send_tm_enable_flag",&__hmi_var_38);
	}
}
}

static void widget_get_pack_4_click(void)
{
	{
#line 1 "控件:get_pack_4,事件:click"
hmi_window_show("win_test");

	}
{
}
}

static void widget_admin_btn_click(void)
{
	char * __hmi_var_56 = ((char *)hmidb_get_data_value("picture_ctrl.input_psd"));
		char * __hmi_var_57 = ((char *)hmidb_get_data_value("picture_ctrl.input_password_str"));
		{
#line 1 "控件:admin_btn,事件:click"

hmi_window_show("win_input_password");
memset(__hmi_var_56 , 0 , 10);
strcpy(__hmi_var_57,"请输入密码");
//hmi_window_show("win_admin");

	}
{
		hmidb_set_data_value("picture_ctrl.input_password_str",__hmi_var_57);
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_56);
}
}

static void widget_get_pack_2_click(void)
{
	u8 __hmi_var_58 = (*(u8 *)hmidb_get_data_value("sys_set.user_ic_enable_flag"));
	u8 __old___hmi_var_58 = __hmi_var_58;
	{
#line 1 "控件:get_pack_2,事件:click"
hmi_window_show("win_sender_psd");
__hmi_var_58 = 0;//等待用户ＩＣ输入

	}
{
	if(__old___hmi_var_58 != __hmi_var_58)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_58);
	}
}
}

static void widget_get_pack_3_click(void)
{
	{
#line 1 "控件:get_pack_3,事件:click"
hmi_window_show("win_get_pack");

	}
{
}
}

static void widget_window_open(void)
{
	u8 __hmi_var_59 = (*(u8 *)hmidb_get_data_value("sys_set.box_num"));
	u8 __old___hmi_var_59 = __hmi_var_59;
	u8 __hmi_var_60 = (*(u8 *)hmidb_get_data_value("sys_set.init_flag"));
	u8 __old___hmi_var_60 = __hmi_var_60;
	u8 __hmi_var_61 = (*(u8 *)hmidb_get_data_value("test_parm.creat_file"));
	u8 __old___hmi_var_61 = __hmi_var_61;
	u8 __hmi_var_62 = (*(u8 *)hmidb_get_data_value("system.HideWindowCursor"));
	u8 __old___hmi_var_62 = __hmi_var_62;
	char * __hmi_var_63 = ((char *)hmidb_get_data_value("sys_set.station_add"));
		char * __hmi_var_64 = ((char *)hmidb_get_data_value("sys_set.admin_psd"));
		u8 * __hmi_var_65 = ((u8 *)hmidb_get_data_value("sys_set.send_pack"));
		u8 __hmi_var_66 = (*(u8 *)hmidb_get_data_value("sys_set.send_pack_flag"));
	u8 __old___hmi_var_66 = __hmi_var_66;
	{
#line 1 "控件:window,事件:open"
CAB_INFO cab_msg;

if(1 == box_info_init(__hmi_var_59 , __hmi_var_60))
{
    history_info_init();
    __hmi_var_61 = 1;
    __hmi_var_60 = 1;
    {
	if(__old___hmi_var_66 != __hmi_var_66)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_66);
		__old___hmi_var_66 = __hmi_var_66;
	}
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_65);
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_64);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_63);
	if(__old___hmi_var_62 != __hmi_var_62)
	{
		hmidb_set_data_value("system.HideWindowCursor",&__hmi_var_62);
		__old___hmi_var_62 = __hmi_var_62;
	}
	if(__old___hmi_var_61 != __hmi_var_61)
	{
		hmidb_set_data_value("test_parm.creat_file",&__hmi_var_61);
		__old___hmi_var_61 = __hmi_var_61;
	}
	if(__old___hmi_var_60 != __hmi_var_60)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_60);
		__old___hmi_var_60 = __hmi_var_60;
	}
	if(__old___hmi_var_59 != __hmi_var_59)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_59);
		__old___hmi_var_59 = __hmi_var_59;
	}
}

    sys_save_params();   
}
else
{
    __hmi_var_61 = 0;
}
__hmi_var_62 = 1;//隐藏光标


        //读取当前系统信息
memcpy(cab_msg.cabinet_num , __hmi_var_63 , GPRS_CAB_NUM_LEN);
memcpy(cab_msg.admin_psd , __hmi_var_64 , GPRS_ADMIN_PSD_LENGTH);
cab_msg.box_num = __hmi_var_59;
cab_msg.flag = RW_OK;
cab_msg.restart_flag = SYS_START;
package_send_pack(__hmi_var_65 , __hmi_var_63 , RW_CAB_INFO , (unsigned char *)(&cab_msg) , sizeof(CAB_INFO));
__hmi_var_66 = 1;//开始发送

debug_set_ip("192.168.1.200");

debug_printf("system start\n");

	}
{
	if(__old___hmi_var_66 != __hmi_var_66)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_66);
	}
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_65);
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_64);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_63);
	if(__old___hmi_var_62 != __hmi_var_62)
	{
		hmidb_set_data_value("system.HideWindowCursor",&__hmi_var_62);
	}
	if(__old___hmi_var_61 != __hmi_var_61)
	{
		hmidb_set_data_value("test_parm.creat_file",&__hmi_var_61);
	}
	if(__old___hmi_var_60 != __hmi_var_60)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_60);
	}
	if(__old___hmi_var_59 != __hmi_var_59)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_59);
	}
}
}

#endif
