/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_text_3_text(void *value);
static int widget_set_text_text(void *value);
static int widget_set_text_2_text(void *value);

hmi_widget_func_t hmi_window_6D61696E_prop_funcs[]={
{"text_3_text",(void *)widget_set_text_3_text},
{"text_text",(void *)widget_set_text_text},
{"text_2_text",(void *)widget_set_text_2_text},
{NULL,NULL}
};

static int widget_set_text_3_text(void *value)
{
	static void *__hmi_var_0_ptr;
	u32 __hmi_var_0 = (*(u32 *)hmidb_get_data_value_by_ptr("system.CurDateTime",&__hmi_var_0_ptr));
#line 1 "控件:text_3,属性:text"
	char * __hmi_retval = (char *)(datetime2str(__hmi_var_0));
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_text(void *value)
{
	static void *__hmi_var_54_ptr;
	char * __hmi_var_54 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.main_tip",&__hmi_var_54_ptr));
#line 1 "控件:text,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_54);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,30);
		((char *)value)[30-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_2_text(void *value)
{
	static void *__hmi_var_55_ptr;
	char * __hmi_var_55 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.welcome",&__hmi_var_55_ptr));
#line 1 "控件:text_2,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_55);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

#endif
