/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_12_click(void);
static void widget_button_2_click(void);
static void widget_button_click(void);

hmi_widget_func_t hmi_window_7465737431_event_funcs[]={
{"button_12_click",(void *)widget_button_12_click},
{"button_2_click",(void *)widget_button_2_click},
{"button_click",(void *)widget_button_click},
{NULL,NULL}
};

static void widget_button_12_click(void)
{
	{
#line 1 "控件:button_12,事件:click"
hmi_window_hide("test1");
	}
{
}
}

static void widget_button_2_click(void)
{
	u8 __hmi_var_271 = (*(u8 *)hmidb_get_data_value("picture_ctrl.page_count"));
	u8 __old___hmi_var_271 = __hmi_var_271;
	{
#line 1 "控件:button_2,事件:click"
__hmi_var_271++;

	}
{
	if(__old___hmi_var_271 != __hmi_var_271)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_271);
	}
}
}

static void widget_button_click(void)
{
	u8 __hmi_var_274 = (*(u8 *)hmidb_get_data_value("picture_ctrl.page_count"));
	u8 __old___hmi_var_274 = __hmi_var_274;
	{
#line 1 "控件:button,事件:click"
__hmi_var_274--;

	}
{
	if(__old___hmi_var_274 != __hmi_var_274)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_274);
	}
}
}

#endif
