/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_window_open(void);

hmi_widget_func_t hmi_window_546578744B6579626F61726436_event_funcs[]={
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_window_open(void)
{
	char * __hmi_var_87 = ((char *)hmidb_get_data_value("syskeyboard.KeyboardBuffer"));
		{
#line 1 "¿Ø¼þ:window,ÊÂ¼þ:open"
__hmi_var_87 = "\0";
	}
{
		hmidb_set_data_value("syskeyboard.KeyboardBuffer",__hmi_var_87);
}
}

#endif
