/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_text_2_text(void *value);
static int widget_set_text_text(void *value);

hmi_widget_func_t hmi_window_546578744B6579626F61726434_prop_funcs[]={
{"text_2_text",(void *)widget_set_text_2_text},
{"text_text",(void *)widget_set_text_text},
{NULL,NULL}
};

static int widget_set_text_2_text(void *value)
{
	static void *__hmi_var_86_ptr;
	char * __hmi_var_86 = ((char *)hmidb_get_data_value_by_ptr("syskeyboard.KeyboardBuffer",&__hmi_var_86_ptr));
#line 1 "控件:text_2,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_86);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_text(void *value)
{
	static void *__hmi_var_87_ptr;
	char * __hmi_var_87 = ((char *)hmidb_get_data_value_by_ptr("syskeyboard.Prompt",&__hmi_var_87_ptr));
#line 1 "控件:text,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_87);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

#endif
