/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_text_text(void *value);

hmi_widget_func_t hmi_window_77696E5F626F785F7461626C65_prop_funcs[]={
{"text_text",(void *)widget_set_text_text},
{NULL,NULL}
};

static int widget_set_text_text(void *value)
{
	static void *__hmi_var_7_ptr;
	char * __hmi_var_7 = ((char *)hmidb_get_data_value_by_ptr("sys_set.sys_file_dir",&__hmi_var_7_ptr));
#line 1 "¿Ø¼þ:text,ÊôÐÔ:text"
	char * __hmi_retval = (char *)(__hmi_var_7);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,50);
		((char *)value)[50-1]=0;
		return 1;
	}
	return 0;
}

#endif
