/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_7_click(void);
static void widget_button_6_click(void);
static void widget_window_open(void);

hmi_widget_func_t hmi_window_77696E5F636162696E65745F736574_event_funcs[]={
{"button_7_click",(void *)widget_button_7_click},
{"button_6_click",(void *)widget_button_6_click},
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_button_7_click(void)
{
	{
#line 1 "控件:button_7,事件:click"
hmi_window_hide("win_cabinet_set");

	}
{
}
}

static void widget_button_6_click(void)
{
	u8 __hmi_var_65 = (*(u8 *)hmidb_get_data_value("sys_set.box_num"));
	u8 __old___hmi_var_65 = __hmi_var_65;
	u8 __hmi_var_66 = (*(u8 *)hmidb_get_data_value("picture_ctrl.type_temp"));
	u8 __old___hmi_var_66 = __hmi_var_66;
	char * __hmi_var_67 = ((char *)hmidb_get_data_value("sys_set.station_add"));
		char * __hmi_var_68 = ((char *)hmidb_get_data_value("picture_ctrl.input_psd"));
		u8 __hmi_var_69 = (*(u8 *)hmidb_get_data_value("sys_set.init_flag"));
	u8 __old___hmi_var_69 = __hmi_var_69;
	char * __hmi_var_70 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button_6,事件:click"
__hmi_var_65 = __hmi_var_66;
memcpy( __hmi_var_67 , __hmi_var_68 , 6);
__hmi_var_69 = 0;
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_70);
	if(__old___hmi_var_69 != __hmi_var_69)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_69);
		__old___hmi_var_69 = __hmi_var_69;
	}
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_68);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_67);
	if(__old___hmi_var_66 != __hmi_var_66)
	{
		hmidb_set_data_value("picture_ctrl.type_temp",&__hmi_var_66);
		__old___hmi_var_66 = __hmi_var_66;
	}
	if(__old___hmi_var_65 != __hmi_var_65)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_65);
		__old___hmi_var_65 = __hmi_var_65;
	}
}
  
sys_save_params();//保存好系统信息  

strcpy(__hmi_var_70,"设置成功，请重新启动");
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_70);
	if(__old___hmi_var_69 != __hmi_var_69)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_69);
		__old___hmi_var_69 = __hmi_var_69;
	}
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_68);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_67);
	if(__old___hmi_var_66 != __hmi_var_66)
	{
		hmidb_set_data_value("picture_ctrl.type_temp",&__hmi_var_66);
		__old___hmi_var_66 = __hmi_var_66;
	}
	if(__old___hmi_var_65 != __hmi_var_65)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_65);
		__old___hmi_var_65 = __hmi_var_65;
	}
}

hmi_window_show("win_tip");
	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_70);
	if(__old___hmi_var_69 != __hmi_var_69)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_69);
	}
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_68);
		hmidb_set_data_value("sys_set.station_add",__hmi_var_67);
	if(__old___hmi_var_66 != __hmi_var_66)
	{
		hmidb_set_data_value("picture_ctrl.type_temp",&__hmi_var_66);
	}
	if(__old___hmi_var_65 != __hmi_var_65)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_65);
	}
}
}

static void widget_window_open(void)
{
	u8 __hmi_var_71 = (*(u8 *)hmidb_get_data_value("picture_ctrl.type_temp"));
	u8 __old___hmi_var_71 = __hmi_var_71;
	u8 __hmi_var_72 = (*(u8 *)hmidb_get_data_value("sys_set.box_num"));
	u8 __old___hmi_var_72 = __hmi_var_72;
	char * __hmi_var_73 = ((char *)hmidb_get_data_value("picture_ctrl.input_psd"));
		char * __hmi_var_74 = ((char *)hmidb_get_data_value("sys_set.station_add"));
		{
#line 1 "控件:window,事件:open"
__hmi_var_71 = __hmi_var_72;
memset(__hmi_var_73 , 0 ,10);
memcpy(__hmi_var_73 , __hmi_var_74 , 6);

	}
{
		hmidb_set_data_value("sys_set.station_add",__hmi_var_74);
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_73);
	if(__old___hmi_var_72 != __hmi_var_72)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_72);
	}
	if(__old___hmi_var_71 != __hmi_var_71)
	{
		hmidb_set_data_value("picture_ctrl.type_temp",&__hmi_var_71);
	}
}
}

#endif
