/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_timer_timer(void);
static void widget_mulpicture_click(void);
static void widget_window_close(void);

hmi_widget_func_t hmi_window_77696E5F6164_event_funcs[]={
{"timer_timer",(void *)widget_timer_timer},
{"mulpicture_click",(void *)widget_mulpicture_click},
{"window_close",(void *)widget_window_close},
{NULL,NULL}
};

static void widget_timer_timer(void)
{
	u8 __hmi_var_104 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_ad_pic_ctrol_count"));
	u8 __old___hmi_var_104 = __hmi_var_104;
	u8 __hmi_var_105 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_ad_pic_num"));
	u8 __old___hmi_var_105 = __hmi_var_105;
	{
#line 1 "控件:timer,事件:timer"
__hmi_var_104++;
if(__hmi_var_104 == __hmi_var_105)
{
    __hmi_var_104 = 0;
}


	}
{
	if(__old___hmi_var_105 != __hmi_var_105)
	{
		hmidb_set_data_value("picture_ctrl.win_ad_pic_num",&__hmi_var_105);
	}
	if(__old___hmi_var_104 != __hmi_var_104)
	{
		hmidb_set_data_value("picture_ctrl.win_ad_pic_ctrol_count",&__hmi_var_104);
	}
}
}

static void widget_mulpicture_click(void)
{
	{
#line 1 "控件:mulpicture,事件:click"
hmi_window_show("logo");
hmi_window_hide("win_ad");

	}
{
}
}

static void widget_window_close(void)
{
	{
#line 1 "控件:window,事件:close"
hmi_window_show("logo");
	}
{
}
}

#endif
