/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_click(void);

hmi_widget_func_t hmi_window_77696E5F746970_event_funcs[]={
{"button_click",(void *)widget_button_click},
{NULL,NULL}
};

static void widget_button_click(void)
{
	{
#line 1 "¿Ø¼þ:button,ÊÂ¼þ:click"
hmi_window_hide("win_tip");

	}
{
}
}

#endif
