/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE

hmi_widget_func_t hmi_window_77696E5F736176655F7061636B5F6E6578745F746970_prop_funcs[]={
{NULL,NULL}
};

#endif
