/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_2_click(void);
static void widget_button_click(void);

hmi_widget_func_t hmi_window_77696E5F696E7075745F70617373776F7264_event_funcs[]={
{"button_2_click",(void *)widget_button_2_click},
{"button_click",(void *)widget_button_click},
{NULL,NULL}
};

static void widget_button_2_click(void)
{
	{
#line 1 "控件:button_2,事件:click"
hmi_window_hide("win_input_password");
	}
{
}
}

static void widget_button_click(void)
{
	char * __hmi_var_10 = ((char *)hmidb_get_data_value("picture_ctrl.input_psd"));
		char * __hmi_var_11 = ((char *)hmidb_get_data_value("sys_set.admin_psd"));
		char * __hmi_var_12 = ((char *)hmidb_get_data_value("picture_ctrl.input_password_str"));
		{
#line 1 "控件:button,事件:click"
if(0 == memcmp(__hmi_var_10 , __hmi_var_11 , 6))
{
    hmi_window_hide("win_input_password");
    hmi_window_show("win_admin");
}
else
{
    memcpy(__hmi_var_12 , "密码错误,请重新输入",strlen("密码错误,请重新输入"));
    memset(__hmi_var_10 , 0 , 10);
}


	}
{
		hmidb_set_data_value("picture_ctrl.input_password_str",__hmi_var_12);
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_11);
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_10);
}
}

#endif
