/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_2_click(void);
static void widget_button_click(void);
static void widget_window_open(void);
static void widget_window_close(void);

hmi_widget_func_t hmi_window_77696E5F6765745F7061636B_event_funcs[]={
{"button_2_click",(void *)widget_button_2_click},
{"button_click",(void *)widget_button_click},
{"window_open",(void *)widget_window_open},
{"window_close",(void *)widget_window_close},
{NULL,NULL}
};

static void widget_button_2_click(void)
{
	{
#line 1 "控件:button_2,事件:click"
hmi_window_hide("win_get_pack");
	}
{
}
}

static void widget_button_click(void)
{
	char * __hmi_var_11 = ((char *)hmidb_get_data_value("box_msg.pass_word"));
		u16 __hmi_var_12 = (*(u16 *)hmidb_get_data_value("ARM_info.station_num"));
	u16 __old___hmi_var_12 = __hmi_var_12;
	u16 __hmi_var_13 = (*(u16 *)hmidb_get_data_value("ARM_info.station_port"));
	u16 __old___hmi_var_13 = __hmi_var_13;
	u16 __hmi_var_14 = (*(u16 *)hmidb_get_data_value("ARM_info.back_comm"));
	u16 __old___hmi_var_14 = __hmi_var_14;
	u16 __hmi_var_15 = (*(u16 *)hmidb_get_data_value("ARM_info.send_comm"));
	u16 __old___hmi_var_15 = __hmi_var_15;
	char * __hmi_var_16 = ((char *)hmidb_get_data_value("picture_ctrl.open_box_tip"));
		u8 * __hmi_var_17 = ((u8 *)hmidb_get_data_value("sys_set.send_pack"));
		char * __hmi_var_18 = ((char *)hmidb_get_data_value("sys_set.station_add"));
		u8 __hmi_var_19 = (*(u8 *)hmidb_get_data_value("sys_set.send_pack_flag"));
	u8 __old___hmi_var_19 = __hmi_var_19;
	char * __hmi_var_20 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button,事件:click"
BOX_MSG box_info;
int data_len;
unsigned char data_buf[sizeof(USER_INFO)];
if(1 == read_box_info_pass_word(__hmi_var_11,  &box_info))
{
    //密码正确，执行开箱操作，同时发送数据给服务器
    write_box_info(&box_info);
    __hmi_var_12 = box_info.station_num;
    __hmi_var_13 = box_info.station_port;
    __hmi_var_14 = 0;
    __hmi_var_15 = 1;
    memset(__hmi_var_16,0,30);
    memcpy(__hmi_var_16 , box_info.virtualnumber,VIRTUAL_NUM_LENGTH);
    strcat(__hmi_var_16 ,"号箱门已开");
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_20);
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_19);
		__old___hmi_var_19 = __hmi_var_19;
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_18);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_17);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_16);
	if(__old___hmi_var_15 != __hmi_var_15)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_15);
		__old___hmi_var_15 = __hmi_var_15;
	}
	if(__old___hmi_var_14 != __hmi_var_14)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_14);
		__old___hmi_var_14 = __hmi_var_14;
	}
	if(__old___hmi_var_13 != __hmi_var_13)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_13);
		__old___hmi_var_13 = __hmi_var_13;
	}
	if(__old___hmi_var_12 != __hmi_var_12)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_12);
		__old___hmi_var_12 = __hmi_var_12;
	}
		hmidb_set_data_value("box_msg.pass_word",__hmi_var_11);
}

    hmi_window_show("win_box_tip");  

    data_len = package_user_data_pack(data_buf , CLEAR_ASK , &box_info);//封装数据部分
    package_send_pack(__hmi_var_17 , __hmi_var_18 ,GETOUT_USER_INFO , data_buf , data_len);//封装整包
    __hmi_var_19 = 1;//发送包
    memset(__hmi_var_11 , 0 , 10);
    hmi_window_hide("win_get_pack");
  
}else
{
    memset(__hmi_var_11 , 0 , 10);
    strcpy(__hmi_var_20 , "密码错误，请核对后重试");
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_20);
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_19);
		__old___hmi_var_19 = __hmi_var_19;
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_18);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_17);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_16);
	if(__old___hmi_var_15 != __hmi_var_15)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_15);
		__old___hmi_var_15 = __hmi_var_15;
	}
	if(__old___hmi_var_14 != __hmi_var_14)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_14);
		__old___hmi_var_14 = __hmi_var_14;
	}
	if(__old___hmi_var_13 != __hmi_var_13)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_13);
		__old___hmi_var_13 = __hmi_var_13;
	}
	if(__old___hmi_var_12 != __hmi_var_12)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_12);
		__old___hmi_var_12 = __hmi_var_12;
	}
		hmidb_set_data_value("box_msg.pass_word",__hmi_var_11);
}

    hmi_window_show("win_tip");    
}

	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_20);
	if(__old___hmi_var_19 != __hmi_var_19)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_19);
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_18);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_17);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_16);
	if(__old___hmi_var_15 != __hmi_var_15)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_15);
	}
	if(__old___hmi_var_14 != __hmi_var_14)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_14);
	}
	if(__old___hmi_var_13 != __hmi_var_13)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_13);
	}
	if(__old___hmi_var_12 != __hmi_var_12)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_12);
	}
		hmidb_set_data_value("box_msg.pass_word",__hmi_var_11);
}
}

static void widget_window_open(void)
{
	char * __hmi_var_21 = ((char *)hmidb_get_data_value("box_msg.pass_word"));
		{
#line 1 "控件:window,事件:open"
 memset(__hmi_var_21 , 0 , 10);
	}
{
		hmidb_set_data_value("box_msg.pass_word",__hmi_var_21);
}
}

static void widget_window_close(void)
{
	{
#line 1 "控件:window,事件:close"
hmi_window_hide("TextKeyboard6");
	}
{
}
}

#endif
