/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_window_open(void);

hmi_widget_func_t hmi_window_77696E5F626F785F7461626C65_event_funcs[]={
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_window_open(void)
{
	char * __hmi_var_8 = ((char *)hmidb_get_data_value("sys_set.sys_file_dir"));
		{
#line 1 "¿Ø¼þ:window,ÊÂ¼þ:open"
void *handle;
memcpy(__hmi_var_8 , hmi_get_usr_data_dir() , strlen(hmi_get_usr_data_dir()));
/*
debug_printf("sizeof(__hmi_var_8)=%d",sizeof(__hmi_var_8));
debug_printf("strlen(hmi_get_usr_data_dir())=%d",strlen(hmi_get_usr_data_dir()));

if( NULL == create_table("test1",handle))
{
    msgbox("tip","create_table fail",MSG_MB_OK);
}
if( 0 == save_table_to_file(handle , "test1"))
{
    msgbox("tip","save_table fail",MSG_MB_OK);
}
*/

	}
{
		hmidb_set_data_value("sys_set.sys_file_dir",__hmi_var_8);
}
}

#endif
