/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_click(void);
static void widget_button_2_click(void);
static void widget_window_open(void);
static void widget_window_close(void);

hmi_widget_func_t hmi_window_77696E5F73656E6465725F707364_event_funcs[]={
{"button_click",(void *)widget_button_click},
{"button_2_click",(void *)widget_button_2_click},
{"window_open",(void *)widget_window_open},
{"window_close",(void *)widget_window_close},
{NULL,NULL}
};

static void widget_button_click(void)
{
	char * __hmi_var_116 = ((char *)hmidb_get_data_value("box_msg.send_psd"));
		u8 * __hmi_var_117 = ((u8 *)hmidb_get_data_value("sys_set.send_pack"));
		char * __hmi_var_118 = ((char *)hmidb_get_data_value("sys_set.station_add"));
		u8 __hmi_var_119 = (*(u8 *)hmidb_get_data_value("sys_set.send_pack_flag"));
	u8 __old___hmi_var_119 = __hmi_var_119;
	char * __hmi_var_120 = ((char *)hmidb_get_data_value("picture_ctrl.win_wait_tip"));
		u8 __hmi_var_121 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_wait_sw"));
	u8 __old___hmi_var_121 = __hmi_var_121;
	u8 __hmi_var_122 = (*(u8 *)hmidb_get_data_value("sys_set.user_ic_enable_flag"));
	u8 __old___hmi_var_122 = __hmi_var_122;
	{
#line 1 "控件:button,事件:click"
//运货员输入密码后确认，发送请求信息
SENDER_INFO sender_msg;
memset((unsigned char *)&sender_msg , 0xff , sizeof(SENDER_INFO));

sender_msg.flag = SENDER_ASK;//标志，请求权限
memcpy(sender_msg.send_psd , __hmi_var_116 , SEND_PSD_LEN);//密码

package_send_pack(__hmi_var_117 , __hmi_var_118 , SENDER_CONFIRM , (unsigned char *)&sender_msg , sizeof(SENDER_INFO));

__hmi_var_119 = 1;
hmi_window_hide("win_sender_psd");
strcpy(__hmi_var_120,"后台处理中，请耐心等待");
__hmi_var_121 = 0;
//__hmi_var_122 = 1;
{
	if(__old___hmi_var_122 != __hmi_var_122)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_122);
		__old___hmi_var_122 = __hmi_var_122;
	}
	if(__old___hmi_var_121 != __hmi_var_121)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_sw",&__hmi_var_121);
		__old___hmi_var_121 = __hmi_var_121;
	}
		hmidb_set_data_value("picture_ctrl.win_wait_tip",__hmi_var_120);
	if(__old___hmi_var_119 != __hmi_var_119)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_119);
		__old___hmi_var_119 = __hmi_var_119;
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_118);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_117);
		hmidb_set_data_value("box_msg.send_psd",__hmi_var_116);
}

hmi_window_show("win_wait_tip");

	}
{
	if(__old___hmi_var_122 != __hmi_var_122)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_122);
	}
	if(__old___hmi_var_121 != __hmi_var_121)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_sw",&__hmi_var_121);
	}
		hmidb_set_data_value("picture_ctrl.win_wait_tip",__hmi_var_120);
	if(__old___hmi_var_119 != __hmi_var_119)
	{
		hmidb_set_data_value("sys_set.send_pack_flag",&__hmi_var_119);
	}
		hmidb_set_data_value("sys_set.station_add",__hmi_var_118);
		hmidb_set_data_value("sys_set.send_pack",__hmi_var_117);
		hmidb_set_data_value("box_msg.send_psd",__hmi_var_116);
}
}

static void widget_button_2_click(void)
{
	{
#line 1 "控件:button_2,事件:click"
hmi_window_hide("win_sender_psd");
	}
{
}
}

static void widget_window_open(void)
{
	u8 __hmi_var_123 = (*(u8 *)hmidb_get_data_value("sys_set.user_ic_enable_flag"));
	u8 __old___hmi_var_123 = __hmi_var_123;
	char * __hmi_var_124 = ((char *)hmidb_get_data_value("box_msg.send_psd"));
		{
#line 1 "控件:window,事件:open"
__hmi_var_123 = 0;//允许运货员IC刷入
memset(__hmi_var_124 , 0 , 10);//清除相关信息

	}
{
		hmidb_set_data_value("box_msg.send_psd",__hmi_var_124);
	if(__old___hmi_var_123 != __hmi_var_123)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_123);
	}
}
}

static void widget_window_close(void)
{
	u8 __hmi_var_125 = (*(u8 *)hmidb_get_data_value("sys_set.user_ic_enable_flag"));
	u8 __old___hmi_var_125 = __hmi_var_125;
	{
#line 1 "控件:window,事件:close"
__hmi_var_125 = 1;//允许用户IC刷入
	}
{
	if(__old___hmi_var_125 != __hmi_var_125)
	{
		hmidb_set_data_value("sys_set.user_ic_enable_flag",&__hmi_var_125);
	}
}
}

#endif
