/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_12_click(void);
static void widget_button_11_click(void);
static void widget_window_open(void);

hmi_widget_func_t hmi_window_77696E5F6368616E67655F61646D696E5F707364_event_funcs[]={
{"button_12_click",(void *)widget_button_12_click},
{"button_11_click",(void *)widget_button_11_click},
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_button_12_click(void)
{
	{
#line 1 "控件:button_12,事件:click"
hmi_window_hide("win_change_admin_psd");
	}
{
}
}

static void widget_button_11_click(void)
{
	char * __hmi_var_203 = ((char *)hmidb_get_data_value("picture_ctrl.input_psd_again"));
		char * __hmi_var_204 = ((char *)hmidb_get_data_value("picture_ctrl.input_psd"));
		char * __hmi_var_205 = ((char *)hmidb_get_data_value("sys_set.admin_psd"));
		char * __hmi_var_206 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button_11,事件:click"
if(0 == memcmp(__hmi_var_203 , __hmi_var_204 , 10))
{
    //两次输入密码正确
    memcpy(__hmi_var_205 , __hmi_var_204 , 6);//复制密码到管理员密码
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_206);
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_205);
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_204);
		hmidb_set_data_value("picture_ctrl.input_psd_again",__hmi_var_203);
}
  
    sys_save_params();//保存好系统信息  

    strcpy(__hmi_var_206 , "管理员密码修改成功");   
}
else
{
    strcpy(__hmi_var_206 , "两次输入不匹配，请重新输入");
    
}
memset(__hmi_var_204,0,10);
memset(__hmi_var_203,0,10);
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_206);
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_205);
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_204);
		hmidb_set_data_value("picture_ctrl.input_psd_again",__hmi_var_203);
}

hmi_window_show("win_tip"); 

	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_206);
		hmidb_set_data_value("sys_set.admin_psd",__hmi_var_205);
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_204);
		hmidb_set_data_value("picture_ctrl.input_psd_again",__hmi_var_203);
}
}

static void widget_window_open(void)
{
	char * __hmi_var_207 = ((char *)hmidb_get_data_value("picture_ctrl.input_psd"));
		char * __hmi_var_208 = ((char *)hmidb_get_data_value("picture_ctrl.input_psd_again"));
		{
#line 1 "控件:window,事件:open"
memset(__hmi_var_207,0,10);
memset(__hmi_var_208,0,10);

	}
{
		hmidb_set_data_value("picture_ctrl.input_psd_again",__hmi_var_208);
		hmidb_set_data_value("picture_ctrl.input_psd",__hmi_var_207);
}
}

#endif
