/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_text_8_text(void *value);
static int widget_set_text_7_text(void *value);
static int widget_set_text_6_text(void *value);
static int widget_set_text_5_text(void *value);
static int widget_set_text_4_text(void *value);
static int widget_set_text_3_text(void *value);
static int widget_set_text_2_text(void *value);
static int widget_set_text_text(void *value);

hmi_widget_func_t hmi_window_77696E5F74657374_prop_funcs[]={
{"text_8_text",(void *)widget_set_text_8_text},
{"text_7_text",(void *)widget_set_text_7_text},
{"text_6_text",(void *)widget_set_text_6_text},
{"text_5_text",(void *)widget_set_text_5_text},
{"text_4_text",(void *)widget_set_text_4_text},
{"text_3_text",(void *)widget_set_text_3_text},
{"text_2_text",(void *)widget_set_text_2_text},
{"text_text",(void *)widget_set_text_text},
{NULL,NULL}
};

static int widget_set_text_8_text(void *value)
{
	static void *__hmi_var_0_ptr;
	char * __hmi_var_0 = ((char *)hmidb_get_data_value_by_ptr("test_parm.send_id",&__hmi_var_0_ptr));
#line 1 "控件:text_8,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_0);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_7_text(void *value)
{
	static void *__hmi_var_1_ptr;
	char * __hmi_var_1 = ((char *)hmidb_get_data_value_by_ptr("test_parm.send_num",&__hmi_var_1_ptr));
#line 1 "控件:text_7,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_1);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_6_text(void *value)
{
	static void *__hmi_var_2_ptr;
	char * __hmi_var_2 = ((char *)hmidb_get_data_value_by_ptr("test_parm.pass_word",&__hmi_var_2_ptr));
#line 1 "控件:text_6,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_2);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_5_text(void *value)
{
	static void *__hmi_var_3_ptr;
	char * __hmi_var_3 = ((char *)hmidb_get_data_value_by_ptr("test_parm.user_phnum",&__hmi_var_3_ptr));
#line 1 "控件:text_5,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_3);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_4_text(void *value)
{
	static void *__hmi_var_4_ptr;
	char * __hmi_var_4 = ((char *)hmidb_get_data_value_by_ptr("test_parm.user_id",&__hmi_var_4_ptr));
#line 1 "控件:text_4,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_4);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_3_text(void *value)
{
	static void *__hmi_var_5_ptr;
	char * __hmi_var_5 = ((char *)hmidb_get_data_value_by_ptr("test_parm.status",&__hmi_var_5_ptr));
#line 1 "控件:text_3,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_5);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_2_text(void *value)
{
	static void *__hmi_var_6_ptr;
	char * __hmi_var_6 = ((char *)hmidb_get_data_value_by_ptr("test_parm.type",&__hmi_var_6_ptr));
#line 1 "控件:text_2,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_6);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_text(void *value)
{
	static void *__hmi_var_7_ptr;
	char * __hmi_var_7 = ((char *)hmidb_get_data_value_by_ptr("test_parm.virtualnumber",&__hmi_var_7_ptr));
#line 1 "控件:text,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_7);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

#endif
