/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_get_pack_6_click(void);
static void widget_get_pack_5_click(void);
static void widget_get_pack_4_click(void);
static void widget_button_6_click(void);
static void widget_button_5_click(void);
static void widget_button_4_click(void);
static void widget_button_3_click(void);
static void widget_button_2_click(void);
static void widget_button_click(void);

hmi_widget_func_t hmi_window_77696E5F61646D696E_event_funcs[]={
{"get_pack_6_click",(void *)widget_get_pack_6_click},
{"get_pack_5_click",(void *)widget_get_pack_5_click},
{"get_pack_4_click",(void *)widget_get_pack_4_click},
{"button_6_click",(void *)widget_button_6_click},
{"button_5_click",(void *)widget_button_5_click},
{"button_4_click",(void *)widget_button_4_click},
{"button_3_click",(void *)widget_button_3_click},
{"button_2_click",(void *)widget_button_2_click},
{"button_click",(void *)widget_button_click},
{NULL,NULL}
};

static void widget_get_pack_6_click(void)
{
	{
#line 1 "控件:get_pack_6,事件:click"
sys_shutdown(3);

	}
{
}
}

static void widget_get_pack_5_click(void)
{
	{
#line 1 "控件:get_pack_5,事件:click"
hmi_window_show("win_disp_box_status");
	}
{
}
}

static void widget_get_pack_4_click(void)
{
	{
#line 1 "控件:get_pack_4,事件:click"
hmi_window_show("win_test");

	}
{
}
}

static void widget_button_6_click(void)
{
	{
#line 1 "控件:button_6,事件:click"
hmi_window_hide("win_admin");
	}
{
}
}

static void widget_button_5_click(void)
{
	{
#line 1 "控件:button_5,事件:click"
hmi_window_show("win_history");
	}
{
}
}

static void widget_button_4_click(void)
{
	{
#line 1 "控件:button_4,事件:click"
hmi_window_show("win_sys_set");
	}
{
}
}

static void widget_button_3_click(void)
{
	{
#line 1 "控件:button_3,事件:click"
hmi_window_show("win_box_operate");
	}
{
}
}

static void widget_button_2_click(void)
{
	{
#line 1 "控件:button_2,事件:click"
hmi_window_show("win_box_set");
	}
{
}
}

static void widget_button_click(void)
{
	{
#line 1 "控件:button,事件:click"
hmi_window_show("win_cabinet_set");
	}
{
}
}

#endif
