/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_16_click(void);
static void widget_button_2_click(void);
static void widget_button_click(void);
static void widget_button_15_click(void);
static void widget_button_14_click(void);
static void widget_button_13_click(void);
static void widget_button_12_click(void);
static void widget_window_open(void);

hmi_widget_func_t hmi_window_77696E5F686973746F7279_event_funcs[]={
{"button_16_click",(void *)widget_button_16_click},
{"button_2_click",(void *)widget_button_2_click},
{"button_click",(void *)widget_button_click},
{"button_15_click",(void *)widget_button_15_click},
{"button_14_click",(void *)widget_button_14_click},
{"button_13_click",(void *)widget_button_13_click},
{"button_12_click",(void *)widget_button_12_click},
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_button_16_click(void)
{
	{
#line 1 "控件:button_16,事件:click"
hmi_window_hide("win_history");
	}
{
}
}

static void widget_button_2_click(void)
{
	u8 __hmi_var_50 = (*(u8 *)hmidb_get_data_value("picture_ctrl.page_count"));
	u8 __old___hmi_var_50 = __hmi_var_50;
	{
#line 1 "控件:button_2,事件:click"
__hmi_var_50++;

	}
{
	if(__old___hmi_var_50 != __hmi_var_50)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_50);
	}
}
}

static void widget_button_click(void)
{
	u8 __hmi_var_53 = (*(u8 *)hmidb_get_data_value("picture_ctrl.page_count"));
	u8 __old___hmi_var_53 = __hmi_var_53;
	{
#line 1 "控件:button,事件:click"
__hmi_var_53--;

	}
{
	if(__old___hmi_var_53 != __hmi_var_53)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_53);
	}
}
}

static void widget_button_15_click(void)
{
	u8 __hmi_var_56 = (*(u8 *)hmidb_get_data_value("picture_ctrl.history_detail_index"));
	u8 __old___hmi_var_56 = __hmi_var_56;
	u8 __hmi_var_57 = (*(u8 *)hmidb_get_data_value("picture_ctrl.page_count"));
	u8 __old___hmi_var_57 = __hmi_var_57;
	{
#line 1 "控件:button_15,事件:click"

__hmi_var_56 = __hmi_var_57*4+4;
{
	if(__old___hmi_var_57 != __hmi_var_57)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_57);
		__old___hmi_var_57 = __hmi_var_57;
	}
	if(__old___hmi_var_56 != __hmi_var_56)
	{
		hmidb_set_data_value("picture_ctrl.history_detail_index",&__hmi_var_56);
		__old___hmi_var_56 = __hmi_var_56;
	}
}

hmi_window_show("win_history_detail");

	}
{
	if(__old___hmi_var_57 != __hmi_var_57)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_57);
	}
	if(__old___hmi_var_56 != __hmi_var_56)
	{
		hmidb_set_data_value("picture_ctrl.history_detail_index",&__hmi_var_56);
	}
}
}

static void widget_button_14_click(void)
{
	u8 __hmi_var_74 = (*(u8 *)hmidb_get_data_value("picture_ctrl.history_detail_index"));
	u8 __old___hmi_var_74 = __hmi_var_74;
	u8 __hmi_var_75 = (*(u8 *)hmidb_get_data_value("picture_ctrl.page_count"));
	u8 __old___hmi_var_75 = __hmi_var_75;
	{
#line 1 "控件:button_14,事件:click"

__hmi_var_74 = __hmi_var_75*4+3;
{
	if(__old___hmi_var_75 != __hmi_var_75)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_75);
		__old___hmi_var_75 = __hmi_var_75;
	}
	if(__old___hmi_var_74 != __hmi_var_74)
	{
		hmidb_set_data_value("picture_ctrl.history_detail_index",&__hmi_var_74);
		__old___hmi_var_74 = __hmi_var_74;
	}
}

hmi_window_show("win_history_detail");

	}
{
	if(__old___hmi_var_75 != __hmi_var_75)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_75);
	}
	if(__old___hmi_var_74 != __hmi_var_74)
	{
		hmidb_set_data_value("picture_ctrl.history_detail_index",&__hmi_var_74);
	}
}
}

static void widget_button_13_click(void)
{
	u8 __hmi_var_92 = (*(u8 *)hmidb_get_data_value("picture_ctrl.history_detail_index"));
	u8 __old___hmi_var_92 = __hmi_var_92;
	u8 __hmi_var_93 = (*(u8 *)hmidb_get_data_value("picture_ctrl.page_count"));
	u8 __old___hmi_var_93 = __hmi_var_93;
	{
#line 1 "控件:button_13,事件:click"

__hmi_var_92 = __hmi_var_93*4+2;
{
	if(__old___hmi_var_93 != __hmi_var_93)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_93);
		__old___hmi_var_93 = __hmi_var_93;
	}
	if(__old___hmi_var_92 != __hmi_var_92)
	{
		hmidb_set_data_value("picture_ctrl.history_detail_index",&__hmi_var_92);
		__old___hmi_var_92 = __hmi_var_92;
	}
}

hmi_window_show("win_history_detail");

	}
{
	if(__old___hmi_var_93 != __hmi_var_93)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_93);
	}
	if(__old___hmi_var_92 != __hmi_var_92)
	{
		hmidb_set_data_value("picture_ctrl.history_detail_index",&__hmi_var_92);
	}
}
}

static void widget_button_12_click(void)
{
	u8 __hmi_var_110 = (*(u8 *)hmidb_get_data_value("picture_ctrl.history_detail_index"));
	u8 __old___hmi_var_110 = __hmi_var_110;
	u8 __hmi_var_111 = (*(u8 *)hmidb_get_data_value("picture_ctrl.page_count"));
	u8 __old___hmi_var_111 = __hmi_var_111;
	{
#line 1 "控件:button_12,事件:click"

__hmi_var_110 = __hmi_var_111*4+1;
{
	if(__old___hmi_var_111 != __hmi_var_111)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_111);
		__old___hmi_var_111 = __hmi_var_111;
	}
	if(__old___hmi_var_110 != __hmi_var_110)
	{
		hmidb_set_data_value("picture_ctrl.history_detail_index",&__hmi_var_110);
		__old___hmi_var_110 = __hmi_var_110;
	}
}

hmi_window_show("win_history_detail");

	}
{
	if(__old___hmi_var_111 != __hmi_var_111)
	{
		hmidb_set_data_value("picture_ctrl.page_count",&__hmi_var_111);
	}
	if(__old___hmi_var_110 != __hmi_var_110)
	{
		hmidb_set_data_value("picture_ctrl.history_detail_index",&__hmi_var_110);
	}
}
}

static void widget_window_open(void)
{
	u8 __hmi_var_126 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_history_count"));
	u8 __old___hmi_var_126 = __hmi_var_126;
	{
#line 1 "控件:window,事件:open"

__hmi_var_126 = read_history_count();//读取最大历史记录


	}
{
	if(__old___hmi_var_126 != __hmi_var_126)
	{
		hmidb_set_data_value("picture_ctrl.win_history_count",&__hmi_var_126);
	}
}
}

#endif
