/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_button_visible(void *value);
static int widget_set_button_enable(void *value);
static int widget_set_text_text(void *value);

hmi_widget_func_t hmi_window_77696E5F626F785F746970_prop_funcs[]={
{"button_visible",(void *)widget_set_button_visible},
{"button_enable",(void *)widget_set_button_enable},
{"text_text",(void *)widget_set_text_text},
{NULL,NULL}
};

static int widget_set_button_visible(void *value)
{
	static void *__hmi_var_25_ptr;
	u16 __hmi_var_25 = (*(u16 *)hmidb_get_data_value_by_ptr("ARM_info.back_comm",&__hmi_var_25_ptr));
#line 1 "控件:button,属性:visible"
	u8 __hmi_retval = (u8)(__hmi_var_25);
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static int widget_set_button_enable(void *value)
{
	static void *__hmi_var_26_ptr;
	u16 __hmi_var_26 = (*(u16 *)hmidb_get_data_value_by_ptr("ARM_info.back_comm",&__hmi_var_26_ptr));
#line 1 "控件:button,属性:enable"
	u8 __hmi_retval = (u8)(__hmi_var_26);
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_text__()
{
	static void *__hmi_var_28_ptr;
	u16 __hmi_var_28 = (*(u16 *)hmidb_get_data_value_by_ptr("ARM_info.back_comm",&__hmi_var_28_ptr));
	static void *__hmi_var_29_ptr;
	char * __hmi_var_29 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.open_box_tip",&__hmi_var_29_ptr));
	static void *__hmi_var_30_ptr;
	char * __hmi_var_30 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.open_box_wait",&__hmi_var_30_ptr));
	{
#line 1 "控件:text,属性:text"
if(1 == __hmi_var_28)
{
    return __hmi_var_29;
}
else
{
    return __hmi_var_30;
}
	}
}

static int widget_set_text_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

#endif
