/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_timer_timer(void);
static void widget_button_click(void);
static void widget_window_open(void);

hmi_widget_func_t hmi_window_77696E5F776169745F746970_event_funcs[]={
{"timer_timer",(void *)widget_timer_timer},
{"button_click",(void *)widget_button_click},
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_timer_timer(void)
{
	u8 __hmi_var_15 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_wait_count"));
	u8 __old___hmi_var_15 = __hmi_var_15;
	u8 __hmi_var_16 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_wait_sw"));
	u8 __old___hmi_var_16 = __hmi_var_16;
	char * __hmi_var_17 = ((char *)hmidb_get_data_value("picture_ctrl.win_wait_tip"));
		{
#line 1 "控件:timer,事件:timer"
__hmi_var_15++;
if(__hmi_var_15 > 10)//10s无回复
{
    __hmi_var_16 = 1;
    strcpy(__hmi_var_17,"后台忙碌，请稍后再试");
    __hmi_var_15 = 0;
}

	}
{
		hmidb_set_data_value("picture_ctrl.win_wait_tip",__hmi_var_17);
	if(__old___hmi_var_16 != __hmi_var_16)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_sw",&__hmi_var_16);
	}
	if(__old___hmi_var_15 != __hmi_var_15)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_count",&__hmi_var_15);
	}
}
}

static void widget_button_click(void)
{
	{
#line 1 "控件:button,事件:click"
hmi_window_hide("win_wait_tip");

	}
{
}
}

static void widget_window_open(void)
{
	u8 __hmi_var_21 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_wait_count"));
	u8 __old___hmi_var_21 = __hmi_var_21;
	{
#line 1 "控件:window,事件:open"
__hmi_var_21 = 0;
	}
{
	if(__old___hmi_var_21 != __hmi_var_21)
	{
		hmidb_set_data_value("picture_ctrl.win_wait_count",&__hmi_var_21);
	}
}
}

#endif
