/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_timer_timer(void);
static void widget_button_click(void);
static void widget_window_open(void);

hmi_widget_func_t hmi_window_77696E5F626F785F746970_event_funcs[]={
{"timer_timer",(void *)widget_timer_timer},
{"button_click",(void *)widget_button_click},
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_timer_timer(void)
{
	u16 __hmi_var_20 = (*(u16 *)hmidb_get_data_value("ARM_info.back_comm"));
	u16 __old___hmi_var_20 = __hmi_var_20;
	u8 __hmi_var_21 = (*(u8 *)hmidb_get_data_value("sys_set.box_open_count"));
	u8 __old___hmi_var_21 = __hmi_var_21;
	u8 __hmi_var_22 = (*(u8 *)hmidb_get_data_value("picture_ctrl.open_box_delay"));
	u8 __old___hmi_var_22 = __hmi_var_22;
	char * __hmi_var_23 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		u8 __hmi_var_24 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_save_next_flag"));
	u8 __old___hmi_var_24 = __hmi_var_24;
	{
#line 1 "控件:timer,事件:timer"
//定时器计时，当等待开箱时间过长，弹出再次开箱窗口
if(0 == __hmi_var_20)
{
    __hmi_var_21++;
}else
{
    __hmi_var_22++;
}
if(__hmi_var_21 == 3)//3s超时
{
    hmi_window_hide("win_box_tip");
    strcpy(__hmi_var_23,"开箱失败");
    {
	if(__old___hmi_var_24 != __hmi_var_24)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_24);
		__old___hmi_var_24 = __hmi_var_24;
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_23);
	if(__old___hmi_var_22 != __hmi_var_22)
	{
		hmidb_set_data_value("picture_ctrl.open_box_delay",&__hmi_var_22);
		__old___hmi_var_22 = __hmi_var_22;
	}
	if(__old___hmi_var_21 != __hmi_var_21)
	{
		hmidb_set_data_value("sys_set.box_open_count",&__hmi_var_21);
		__old___hmi_var_21 = __hmi_var_21;
	}
	if(__old___hmi_var_20 != __hmi_var_20)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_20);
		__old___hmi_var_20 = __hmi_var_20;
	}
}

    hmi_window_show("win_tip");      
}
if(__hmi_var_22 == 3)
{
    hmi_window_hide("win_box_tip");
    if(1 == __hmi_var_24)
    {
    //继续存物窗口
     __hmi_var_24 = 0;
     hmi_window_show("win_save_pack_next_tip");
    }
}

	}
{
	if(__old___hmi_var_24 != __hmi_var_24)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_24);
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_23);
	if(__old___hmi_var_22 != __hmi_var_22)
	{
		hmidb_set_data_value("picture_ctrl.open_box_delay",&__hmi_var_22);
	}
	if(__old___hmi_var_21 != __hmi_var_21)
	{
		hmidb_set_data_value("sys_set.box_open_count",&__hmi_var_21);
	}
	if(__old___hmi_var_20 != __hmi_var_20)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_20);
	}
}
}

static void widget_button_click(void)
{
	u8 __hmi_var_27 = (*(u8 *)hmidb_get_data_value("picture_ctrl.win_save_next_flag"));
	u8 __old___hmi_var_27 = __hmi_var_27;
	{
#line 1 "控件:button,事件:click"
hmi_window_hide("win_box_tip");
if(1 == __hmi_var_27)
{
    //继续存物窗口
    __hmi_var_27 = 0;
    hmi_window_show("win_save_pack_next_tip");
}

	}
{
	if(__old___hmi_var_27 != __hmi_var_27)
	{
		hmidb_set_data_value("picture_ctrl.win_save_next_flag",&__hmi_var_27);
	}
}
}

static void widget_window_open(void)
{
	u8 __hmi_var_31 = (*(u8 *)hmidb_get_data_value("sys_set.box_open_count"));
	u8 __old___hmi_var_31 = __hmi_var_31;
	u8 __hmi_var_32 = (*(u8 *)hmidb_get_data_value("picture_ctrl.open_box_delay"));
	u8 __old___hmi_var_32 = __hmi_var_32;
	{
#line 1 "控件:window,事件:open"
__hmi_var_31 = 0;
__hmi_var_32 = 0;
	}
{
	if(__old___hmi_var_32 != __hmi_var_32)
	{
		hmidb_set_data_value("picture_ctrl.open_box_delay",&__hmi_var_32);
	}
	if(__old___hmi_var_31 != __hmi_var_31)
	{
		hmidb_set_data_value("sys_set.box_open_count",&__hmi_var_31);
	}
}
}

#endif
