/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_12_click(void);
static void widget_button_11_click(void);
static void widget_window_open(void);

hmi_widget_func_t hmi_window_77696E5F7379735F7365745F74696D65_event_funcs[]={
{"button_12_click",(void *)widget_button_12_click},
{"button_11_click",(void *)widget_button_11_click},
{"window_open",(void *)widget_window_open},
{NULL,NULL}
};

static void widget_button_12_click(void)
{
	{
#line 1 "控件:button_12,事件:click"
hmi_window_hide("win_sys_set_time");
	}
{
}
}

static void widget_button_11_click(void)
{
	long __hmi_var_209 = (*(long *)hmidb_get_data_value("picture_ctrl.set_year"));
	long __old___hmi_var_209 = __hmi_var_209;
	u8 __hmi_var_210 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_month"));
	u8 __old___hmi_var_210 = __hmi_var_210;
	u8 __hmi_var_211 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_day"));
	u8 __old___hmi_var_211 = __hmi_var_211;
	u8 __hmi_var_212 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_hour"));
	u8 __old___hmi_var_212 = __hmi_var_212;
	u8 __hmi_var_213 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_min"));
	u8 __old___hmi_var_213 = __hmi_var_213;
	u8 __hmi_var_214 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_sec"));
	u8 __old___hmi_var_214 = __hmi_var_214;
	char * __hmi_var_215 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button_11,事件:click"
if(1 == setsystime(__hmi_var_209,__hmi_var_210,__hmi_var_211,__hmi_var_212,__hmi_var_213,__hmi_var_214))
{
    //设置成功
        strcpy(__hmi_var_215 , "系统时间设置成功");
}else
{
   strcpy(__hmi_var_215 , "系统时间设置失败"); 
}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_215);
	if(__old___hmi_var_214 != __hmi_var_214)
	{
		hmidb_set_data_value("picture_ctrl.set_sec",&__hmi_var_214);
		__old___hmi_var_214 = __hmi_var_214;
	}
	if(__old___hmi_var_213 != __hmi_var_213)
	{
		hmidb_set_data_value("picture_ctrl.set_min",&__hmi_var_213);
		__old___hmi_var_213 = __hmi_var_213;
	}
	if(__old___hmi_var_212 != __hmi_var_212)
	{
		hmidb_set_data_value("picture_ctrl.set_hour",&__hmi_var_212);
		__old___hmi_var_212 = __hmi_var_212;
	}
	if(__old___hmi_var_211 != __hmi_var_211)
	{
		hmidb_set_data_value("picture_ctrl.set_day",&__hmi_var_211);
		__old___hmi_var_211 = __hmi_var_211;
	}
	if(__old___hmi_var_210 != __hmi_var_210)
	{
		hmidb_set_data_value("picture_ctrl.set_month",&__hmi_var_210);
		__old___hmi_var_210 = __hmi_var_210;
	}
	if(__old___hmi_var_209 != __hmi_var_209)
	{
		hmidb_set_data_value("picture_ctrl.set_year",&__hmi_var_209);
		__old___hmi_var_209 = __hmi_var_209;
	}
}

hmi_window_show("win_tip"); 

	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_215);
	if(__old___hmi_var_214 != __hmi_var_214)
	{
		hmidb_set_data_value("picture_ctrl.set_sec",&__hmi_var_214);
	}
	if(__old___hmi_var_213 != __hmi_var_213)
	{
		hmidb_set_data_value("picture_ctrl.set_min",&__hmi_var_213);
	}
	if(__old___hmi_var_212 != __hmi_var_212)
	{
		hmidb_set_data_value("picture_ctrl.set_hour",&__hmi_var_212);
	}
	if(__old___hmi_var_211 != __hmi_var_211)
	{
		hmidb_set_data_value("picture_ctrl.set_day",&__hmi_var_211);
	}
	if(__old___hmi_var_210 != __hmi_var_210)
	{
		hmidb_set_data_value("picture_ctrl.set_month",&__hmi_var_210);
	}
	if(__old___hmi_var_209 != __hmi_var_209)
	{
		hmidb_set_data_value("picture_ctrl.set_year",&__hmi_var_209);
	}
}
}

static void widget_window_open(void)
{
	long __hmi_var_216 = (*(long *)hmidb_get_data_value("picture_ctrl.set_year"));
	long __old___hmi_var_216 = __hmi_var_216;
	u16 __hmi_var_217 = (*(u16 *)hmidb_get_data_value("system.Year"));
	u16 __old___hmi_var_217 = __hmi_var_217;
	u8 __hmi_var_218 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_month"));
	u8 __old___hmi_var_218 = __hmi_var_218;
	u8 __hmi_var_219 = (*(u8 *)hmidb_get_data_value("system.Month"));
	u8 __old___hmi_var_219 = __hmi_var_219;
	u8 __hmi_var_220 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_day"));
	u8 __old___hmi_var_220 = __hmi_var_220;
	u8 __hmi_var_221 = (*(u8 *)hmidb_get_data_value("system.Day"));
	u8 __old___hmi_var_221 = __hmi_var_221;
	u8 __hmi_var_222 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_hour"));
	u8 __old___hmi_var_222 = __hmi_var_222;
	u8 __hmi_var_223 = (*(u8 *)hmidb_get_data_value("system.Hour"));
	u8 __old___hmi_var_223 = __hmi_var_223;
	u8 __hmi_var_224 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_min"));
	u8 __old___hmi_var_224 = __hmi_var_224;
	u8 __hmi_var_225 = (*(u8 *)hmidb_get_data_value("system.Minute"));
	u8 __old___hmi_var_225 = __hmi_var_225;
	u8 __hmi_var_226 = (*(u8 *)hmidb_get_data_value("picture_ctrl.set_sec"));
	u8 __old___hmi_var_226 = __hmi_var_226;
	u8 __hmi_var_227 = (*(u8 *)hmidb_get_data_value("system.Second"));
	u8 __old___hmi_var_227 = __hmi_var_227;
	{
#line 1 "控件:window,事件:open"
__hmi_var_216 = __hmi_var_217;
__hmi_var_218 = __hmi_var_219;
__hmi_var_220 = __hmi_var_221;
__hmi_var_222 = __hmi_var_223;
__hmi_var_224 = __hmi_var_225;
__hmi_var_226 = __hmi_var_227;

	}
{
	if(__old___hmi_var_227 != __hmi_var_227)
	{
		hmidb_set_data_value("system.Second",&__hmi_var_227);
	}
	if(__old___hmi_var_226 != __hmi_var_226)
	{
		hmidb_set_data_value("picture_ctrl.set_sec",&__hmi_var_226);
	}
	if(__old___hmi_var_225 != __hmi_var_225)
	{
		hmidb_set_data_value("system.Minute",&__hmi_var_225);
	}
	if(__old___hmi_var_224 != __hmi_var_224)
	{
		hmidb_set_data_value("picture_ctrl.set_min",&__hmi_var_224);
	}
	if(__old___hmi_var_223 != __hmi_var_223)
	{
		hmidb_set_data_value("system.Hour",&__hmi_var_223);
	}
	if(__old___hmi_var_222 != __hmi_var_222)
	{
		hmidb_set_data_value("picture_ctrl.set_hour",&__hmi_var_222);
	}
	if(__old___hmi_var_221 != __hmi_var_221)
	{
		hmidb_set_data_value("system.Day",&__hmi_var_221);
	}
	if(__old___hmi_var_220 != __hmi_var_220)
	{
		hmidb_set_data_value("picture_ctrl.set_day",&__hmi_var_220);
	}
	if(__old___hmi_var_219 != __hmi_var_219)
	{
		hmidb_set_data_value("system.Month",&__hmi_var_219);
	}
	if(__old___hmi_var_218 != __hmi_var_218)
	{
		hmidb_set_data_value("picture_ctrl.set_month",&__hmi_var_218);
	}
	if(__old___hmi_var_217 != __hmi_var_217)
	{
		hmidb_set_data_value("system.Year",&__hmi_var_217);
	}
	if(__old___hmi_var_216 != __hmi_var_216)
	{
		hmidb_set_data_value("picture_ctrl.set_year",&__hmi_var_216);
	}
}
}

#endif
