/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_click(void);
static void widget_button_7_click(void);
static void widget_button_6_click(void);

hmi_widget_func_t hmi_window_77696E5F626F785F736574_event_funcs[]={
{"button_click",(void *)widget_button_click},
{"button_7_click",(void *)widget_button_7_click},
{"button_6_click",(void *)widget_button_6_click},
{NULL,NULL}
};

static void widget_button_click(void)
{
	u8 __hmi_var_111 = (*(u8 *)hmidb_get_data_value("box_msg.station_num"));
	u8 __old___hmi_var_111 = __hmi_var_111;
	char * __hmi_var_112 = ((char *)hmidb_get_data_value("box_msg.virtualnumber"));
		u8 __hmi_var_113 = (*(u8 *)hmidb_get_data_value("box_msg.station_port"));
	u8 __old___hmi_var_113 = __hmi_var_113;
	char __hmi_var_114 = (*(char *)hmidb_get_data_value("box_msg.type"));
	char __old___hmi_var_114 = __hmi_var_114;
	u8 __hmi_var_115 = (*(u8 *)hmidb_get_data_value("picture_ctrl.type_temp"));
	u8 __old___hmi_var_115 = __hmi_var_115;
	char * __hmi_var_116 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button,事件:click"
BOX_MSG box_info;
if(1 == read_box_info_station_num(__hmi_var_111 , &box_info))
{
    memcpy(__hmi_var_112 ,box_info.virtualnumber , VIRTUAL_NUM_LENGTH);//虚拟箱号
    __hmi_var_113 = box_info.station_port;//端口号
    __hmi_var_114 = box_info.type;//箱格类型
    __hmi_var_115 = box_info.type - '1';
}
else
{
    
    strcpy(__hmi_var_116,"箱格序列号错误");
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_116);
	if(__old___hmi_var_115 != __hmi_var_115)
	{
		hmidb_set_data_value("picture_ctrl.type_temp",&__hmi_var_115);
		__old___hmi_var_115 = __hmi_var_115;
	}
	if(__old___hmi_var_114 != __hmi_var_114)
	{
		hmidb_set_data_value("box_msg.type",&__hmi_var_114);
		__old___hmi_var_114 = __hmi_var_114;
	}
	if(__old___hmi_var_113 != __hmi_var_113)
	{
		hmidb_set_data_value("box_msg.station_port",&__hmi_var_113);
		__old___hmi_var_113 = __hmi_var_113;
	}
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_112);
	if(__old___hmi_var_111 != __hmi_var_111)
	{
		hmidb_set_data_value("box_msg.station_num",&__hmi_var_111);
		__old___hmi_var_111 = __hmi_var_111;
	}
}

    hmi_window_show("win_tip");
}

	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_116);
	if(__old___hmi_var_115 != __hmi_var_115)
	{
		hmidb_set_data_value("picture_ctrl.type_temp",&__hmi_var_115);
	}
	if(__old___hmi_var_114 != __hmi_var_114)
	{
		hmidb_set_data_value("box_msg.type",&__hmi_var_114);
	}
	if(__old___hmi_var_113 != __hmi_var_113)
	{
		hmidb_set_data_value("box_msg.station_port",&__hmi_var_113);
	}
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_112);
	if(__old___hmi_var_111 != __hmi_var_111)
	{
		hmidb_set_data_value("box_msg.station_num",&__hmi_var_111);
	}
}
}

static void widget_button_7_click(void)
{
	{
#line 1 "控件:button_7,事件:click"
hmi_window_hide("win_box_set");
	}
{
}
}

static void widget_button_6_click(void)
{
	u8 __hmi_var_117 = (*(u8 *)hmidb_get_data_value("box_msg.station_num"));
	u8 __old___hmi_var_117 = __hmi_var_117;
	char * __hmi_var_118 = ((char *)hmidb_get_data_value("box_msg.virtualnumber"));
		u8 __hmi_var_119 = (*(u8 *)hmidb_get_data_value("box_msg.station_port"));
	u8 __old___hmi_var_119 = __hmi_var_119;
	u8 __hmi_var_120 = (*(u8 *)hmidb_get_data_value("picture_ctrl.type_temp"));
	u8 __old___hmi_var_120 = __hmi_var_120;
	char __hmi_var_121 = (*(char *)hmidb_get_data_value("box_msg.type"));
	char __old___hmi_var_121 = __hmi_var_121;
	char * __hmi_var_122 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button_6,事件:click"
BOX_MSG box_info;
if(1 == read_box_info_station_num(__hmi_var_117 , &box_info))
{
    memcpy(box_info.virtualnumber , __hmi_var_118 , VIRTUAL_NUM_LENGTH);//虚拟箱号
    box_info.station_port = __hmi_var_119;//端口号
    box_info.type = __hmi_var_120 + '1';
    __hmi_var_121 = box_info.type;//箱格类型
    write_box_info(&box_info);//写入箱格信息
    strcpy(__hmi_var_122,"箱格设置成功");
}
else
{
    
    strcpy(__hmi_var_122,"箱格序列号错误");
}
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_122);
	if(__old___hmi_var_121 != __hmi_var_121)
	{
		hmidb_set_data_value("box_msg.type",&__hmi_var_121);
		__old___hmi_var_121 = __hmi_var_121;
	}
	if(__old___hmi_var_120 != __hmi_var_120)
	{
		hmidb_set_data_value("picture_ctrl.type_temp",&__hmi_var_120);
		__old___hmi_var_120 = __hmi_var_120;
	}
	if(__old___hmi_var_119 != __hmi_var_119)
	{
		hmidb_set_data_value("box_msg.station_port",&__hmi_var_119);
		__old___hmi_var_119 = __hmi_var_119;
	}
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_118);
	if(__old___hmi_var_117 != __hmi_var_117)
	{
		hmidb_set_data_value("box_msg.station_num",&__hmi_var_117);
		__old___hmi_var_117 = __hmi_var_117;
	}
}

    hmi_window_show("win_tip");


	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_122);
	if(__old___hmi_var_121 != __hmi_var_121)
	{
		hmidb_set_data_value("box_msg.type",&__hmi_var_121);
	}
	if(__old___hmi_var_120 != __hmi_var_120)
	{
		hmidb_set_data_value("picture_ctrl.type_temp",&__hmi_var_120);
	}
	if(__old___hmi_var_119 != __hmi_var_119)
	{
		hmidb_set_data_value("box_msg.station_port",&__hmi_var_119);
	}
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_118);
	if(__old___hmi_var_117 != __hmi_var_117)
	{
		hmidb_set_data_value("box_msg.station_num",&__hmi_var_117);
	}
}
}

#endif
