/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_timer_timer(void);
static void widget_button_9_click(void);
static void widget_button_8_click(void);
static void widget_button_7_click(void);
static void widget_button_6_click(void);
static void widget_button_5_click(void);
static void widget_button_4_click(void);
static void widget_button_3_click(void);

hmi_widget_func_t hmi_window_77696E5F626F785F6F706572617465_event_funcs[]={
{"timer_timer",(void *)widget_timer_timer},
{"button_9_click",(void *)widget_button_9_click},
{"button_8_click",(void *)widget_button_8_click},
{"button_7_click",(void *)widget_button_7_click},
{"button_6_click",(void *)widget_button_6_click},
{"button_5_click",(void *)widget_button_5_click},
{"button_4_click",(void *)widget_button_4_click},
{"button_3_click",(void *)widget_button_3_click},
{NULL,NULL}
};

static void widget_timer_timer(void)
{
	u16 __hmi_var_124 = (*(u16 *)hmidb_get_data_value("ARM_info.back_comm"));
	u16 __old___hmi_var_124 = __hmi_var_124;
	u16 __hmi_var_125 = (*(u16 *)hmidb_get_data_value("ARM_info.station_num"));
	u16 __old___hmi_var_125 = __hmi_var_125;
	u16 __hmi_var_126 = (*(u16 *)hmidb_get_data_value("ARM_info.station_port"));
	u16 __old___hmi_var_126 = __hmi_var_126;
	u16 __hmi_var_127 = (*(u16 *)hmidb_get_data_value("ARM_info.send_comm"));
	u16 __old___hmi_var_127 = __hmi_var_127;
	char * __hmi_var_128 = ((char *)hmidb_get_data_value("picture_ctrl.open_box_tip"));
		u8 __hmi_var_129 = (*(u8 *)hmidb_get_data_value("sys_set.box_num"));
	u8 __old___hmi_var_129 = __hmi_var_129;
	u8 __hmi_var_130 = (*(u8 *)hmidb_get_data_value("sys_set.open_all_box_flag"));
	u8 __old___hmi_var_130 = __hmi_var_130;
	{
#line 1 "控件:timer,事件:timer"
BOX_MSG box_info;
static int index = 0;

if(1 == __hmi_var_124 || index == 0)
{
    index++;
    if(1 == read_box_info_station_num(index , &box_info))
    {
    __hmi_var_125 = box_info.station_num;
    __hmi_var_126 = box_info.station_port;
    __hmi_var_127 = 1;//发送开箱指令
    __hmi_var_124 = 0;//将返回指令置0
    memset(__hmi_var_128,0,30);
    memcpy(__hmi_var_128 , box_info.virtualnumber,VIRTUAL_NUM_LENGTH);
    strcat(__hmi_var_128 ,"号箱门已开");
    {
	if(__old___hmi_var_130 != __hmi_var_130)
	{
		hmidb_set_data_value("sys_set.open_all_box_flag",&__hmi_var_130);
		__old___hmi_var_130 = __hmi_var_130;
	}
	if(__old___hmi_var_129 != __hmi_var_129)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_129);
		__old___hmi_var_129 = __hmi_var_129;
	}
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_128);
	if(__old___hmi_var_127 != __hmi_var_127)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_127);
		__old___hmi_var_127 = __hmi_var_127;
	}
	if(__old___hmi_var_126 != __hmi_var_126)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_126);
		__old___hmi_var_126 = __hmi_var_126;
	}
	if(__old___hmi_var_125 != __hmi_var_125)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_125);
		__old___hmi_var_125 = __hmi_var_125;
	}
	if(__old___hmi_var_124 != __hmi_var_124)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_124);
		__old___hmi_var_124 = __hmi_var_124;
	}
}

    hmi_window_show("win_box_tip"); 
    }
    if(index == __hmi_var_129)
    {
        __hmi_var_130 = 0;
        index = 0;
    }
}



	}
{
	if(__old___hmi_var_130 != __hmi_var_130)
	{
		hmidb_set_data_value("sys_set.open_all_box_flag",&__hmi_var_130);
	}
	if(__old___hmi_var_129 != __hmi_var_129)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_129);
	}
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_128);
	if(__old___hmi_var_127 != __hmi_var_127)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_127);
	}
	if(__old___hmi_var_126 != __hmi_var_126)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_126);
	}
	if(__old___hmi_var_125 != __hmi_var_125)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_125);
	}
	if(__old___hmi_var_124 != __hmi_var_124)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_124);
	}
}
}

static void widget_button_9_click(void)
{
	{
#line 1 "控件:button_9,事件:click"
hmi_window_hide("win_box_operate");
	}
{
}
}

static void widget_button_8_click(void)
{
	char * __hmi_var_131 = ((char *)hmidb_get_data_value("box_msg.virtualnumber"));
		char * __hmi_var_132 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button_8,事件:click"
BOX_MSG box_info;
text_input_window("box_msg.virtualnumber","请输入箱号",0);
if(1 == read_box_info_virtualnumber(__hmi_var_131 , &box_info))
{
    box_info.status = BOX_IDLE;
    write_box_info(&box_info);
    strcpy(__hmi_var_132 , __hmi_var_131);
    strcat(__hmi_var_132 , "箱号已解锁");
}
else
{
   strcpy(__hmi_var_132 , "箱号输入错误，请重新输入");
}
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_132);
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_131);
}

    hmi_window_show("win_tip"); 

	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_132);
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_131);
}
}

static void widget_button_7_click(void)
{
	char * __hmi_var_133 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		u8 __hmi_var_134 = (*(u8 *)hmidb_get_data_value("sys_set.box_num"));
	u8 __old___hmi_var_134 = __hmi_var_134;
	{
#line 1 "控件:button_7,事件:click"
BOX_MSG box_info;
int index;
strcpy(__hmi_var_133 , "所有箱格解锁成功");
for(index = 1;index <= __hmi_var_134;index++)
{
if(1 == read_box_info_station_num(index , &box_info))
{
    box_info.status = BOX_IDLE;
    write_box_info(&box_info);
}
else
{
   strcpy(__hmi_var_133 , "设置异常");
}
}
    {
	if(__old___hmi_var_134 != __hmi_var_134)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_134);
		__old___hmi_var_134 = __hmi_var_134;
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_133);
}

    hmi_window_show("win_tip"); 

	}
{
	if(__old___hmi_var_134 != __hmi_var_134)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_134);
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_133);
}
}

static void widget_button_6_click(void)
{
	u8 __hmi_var_135 = (*(u8 *)hmidb_get_data_value("sys_set.open_all_box_flag"));
	u8 __old___hmi_var_135 = __hmi_var_135;
	{
#line 1 "控件:button_6,事件:click"
__hmi_var_135 = 1;

	}
{
	if(__old___hmi_var_135 != __hmi_var_135)
	{
		hmidb_set_data_value("sys_set.open_all_box_flag",&__hmi_var_135);
	}
}
}

static void widget_button_5_click(void)
{
	char * __hmi_var_136 = ((char *)hmidb_get_data_value("box_msg.virtualnumber"));
		char * __hmi_var_137 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button_5,事件:click"
BOX_MSG box_info;
text_input_window("box_msg.virtualnumber","请输入箱号",0);
if(1 == read_box_info_virtualnumber(__hmi_var_136 , &box_info))
{
    box_info.status = BOX_LOCK;
    write_box_info(&box_info);
    strcpy(__hmi_var_137 , __hmi_var_136);
    strcat(__hmi_var_137 , "箱号已锁定");
}
else
{
   strcpy(__hmi_var_137 , "箱号输入错误，请重新输入");
}
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_137);
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_136);
}

    hmi_window_show("win_tip"); 

	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_137);
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_136);
}
}

static void widget_button_4_click(void)
{
	char * __hmi_var_138 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		u8 __hmi_var_139 = (*(u8 *)hmidb_get_data_value("sys_set.box_num"));
	u8 __old___hmi_var_139 = __hmi_var_139;
	{
#line 1 "控件:button_4,事件:click"
BOX_MSG box_info;
int index;
strcpy(__hmi_var_138 , "所有箱格锁定成功");
for(index = 1;index <= __hmi_var_139;index++)
{
if(1 == read_box_info_station_num(index , &box_info))
{
    box_info.status = BOX_LOCK;
    write_box_info(&box_info);
}
else
{
   strcpy(__hmi_var_138 , "设置异常");
}
}
    {
	if(__old___hmi_var_139 != __hmi_var_139)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_139);
		__old___hmi_var_139 = __hmi_var_139;
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_138);
}

    hmi_window_show("win_tip"); 

	}
{
	if(__old___hmi_var_139 != __hmi_var_139)
	{
		hmidb_set_data_value("sys_set.box_num",&__hmi_var_139);
	}
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_138);
}
}

static void widget_button_3_click(void)
{
	char * __hmi_var_140 = ((char *)hmidb_get_data_value("box_msg.virtualnumber"));
		u16 __hmi_var_141 = (*(u16 *)hmidb_get_data_value("ARM_info.station_num"));
	u16 __old___hmi_var_141 = __hmi_var_141;
	u16 __hmi_var_142 = (*(u16 *)hmidb_get_data_value("ARM_info.station_port"));
	u16 __old___hmi_var_142 = __hmi_var_142;
	u16 __hmi_var_143 = (*(u16 *)hmidb_get_data_value("ARM_info.send_comm"));
	u16 __old___hmi_var_143 = __hmi_var_143;
	u16 __hmi_var_144 = (*(u16 *)hmidb_get_data_value("ARM_info.back_comm"));
	u16 __old___hmi_var_144 = __hmi_var_144;
	char * __hmi_var_145 = ((char *)hmidb_get_data_value("picture_ctrl.open_box_tip"));
		char * __hmi_var_146 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button_3,事件:click"
BOX_MSG box_info;
text_input_window("box_msg.virtualnumber","请输入箱号",0);
if(1 == read_box_info_virtualnumber(__hmi_var_140 , &box_info))
{
    __hmi_var_141 = box_info.station_num;
    __hmi_var_142 = box_info.station_port;
    __hmi_var_143 = 1;//发送开箱指令
    __hmi_var_144 = 0;//将返回指令置0
    memset(__hmi_var_145,0,30);
    memcpy(__hmi_var_145 , __hmi_var_140,VIRTUAL_NUM_LENGTH);
    strcat(__hmi_var_145 ,"号箱门已开");
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_146);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_145);
	if(__old___hmi_var_144 != __hmi_var_144)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_144);
		__old___hmi_var_144 = __hmi_var_144;
	}
	if(__old___hmi_var_143 != __hmi_var_143)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_143);
		__old___hmi_var_143 = __hmi_var_143;
	}
	if(__old___hmi_var_142 != __hmi_var_142)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_142);
		__old___hmi_var_142 = __hmi_var_142;
	}
	if(__old___hmi_var_141 != __hmi_var_141)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_141);
		__old___hmi_var_141 = __hmi_var_141;
	}
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_140);
}

    hmi_window_show("win_box_tip");    
}
else
{
   strcpy(__hmi_var_146 , "箱号输入错误，请重新输入");
    {
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_146);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_145);
	if(__old___hmi_var_144 != __hmi_var_144)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_144);
		__old___hmi_var_144 = __hmi_var_144;
	}
	if(__old___hmi_var_143 != __hmi_var_143)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_143);
		__old___hmi_var_143 = __hmi_var_143;
	}
	if(__old___hmi_var_142 != __hmi_var_142)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_142);
		__old___hmi_var_142 = __hmi_var_142;
	}
	if(__old___hmi_var_141 != __hmi_var_141)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_141);
		__old___hmi_var_141 = __hmi_var_141;
	}
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_140);
}

    hmi_window_show("win_tip"); 
}
	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_146);
		hmidb_set_data_value("picture_ctrl.open_box_tip",__hmi_var_145);
	if(__old___hmi_var_144 != __hmi_var_144)
	{
		hmidb_set_data_value("ARM_info.back_comm",&__hmi_var_144);
	}
	if(__old___hmi_var_143 != __hmi_var_143)
	{
		hmidb_set_data_value("ARM_info.send_comm",&__hmi_var_143);
	}
	if(__old___hmi_var_142 != __hmi_var_142)
	{
		hmidb_set_data_value("ARM_info.station_port",&__hmi_var_142);
	}
	if(__old___hmi_var_141 != __hmi_var_141)
	{
		hmidb_set_data_value("ARM_info.station_num",&__hmi_var_141);
	}
		hmidb_set_data_value("box_msg.virtualnumber",__hmi_var_140);
}
}

#endif
