/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_button_2_visible(void *value);
static int widget_set_button_2_enable(void *value);
static int widget_set_button_visible(void *value);
static int widget_set_button_enable(void *value);
static int widget_set_text_13_visible(void *value);
static int widget_set_text_13_enable(void *value);
static int widget_set_text_13_text(void *value);
static int widget_set_text_29_visible(void *value);
static int widget_set_text_29_enable(void *value);
static int widget_set_text_29_text(void *value);
static int widget_set_text_12_visible(void *value);
static int widget_set_text_12_enable(void *value);
static int widget_set_text_12_text(void *value);
static int widget_set_text_11_visible(void *value);
static int widget_set_text_11_enable(void *value);
static int widget_set_text_11_text(void *value);
static int widget_set_text_28_visible(void *value);
static int widget_set_text_28_enable(void *value);
static int widget_set_text_28_text(void *value);
static int widget_set_text_10_visible(void *value);
static int widget_set_text_10_enable(void *value);
static int widget_set_text_10_text(void *value);
static int widget_set_text_8_visible(void *value);
static int widget_set_text_8_enable(void *value);
static int widget_set_text_8_text(void *value);
static int widget_set_text_27_visible(void *value);
static int widget_set_text_27_enable(void *value);
static int widget_set_text_27_text(void *value);
static int widget_set_text_7_visible(void *value);
static int widget_set_text_7_enable(void *value);
static int widget_set_text_7_text(void *value);
static int widget_set_text_25_visible(void *value);
static int widget_set_text_25_enable(void *value);
static int widget_set_text_25_text(void *value);
static int widget_set_text_6_visible(void *value);
static int widget_set_text_6_enable(void *value);
static int widget_set_text_6_text(void *value);
static int widget_set_text_5_visible(void *value);
static int widget_set_text_5_enable(void *value);
static int widget_set_text_5_text(void *value);
static int widget_set_text_20_visible(void *value);
static int widget_set_text_20_enable(void *value);
static int widget_set_text_20_text(void *value);
static int widget_set_text_33_visible(void *value);
static int widget_set_text_33_enable(void *value);
static int widget_set_text_33_text(void *value);
static int widget_set_text_18_visible(void *value);
static int widget_set_text_18_enable(void *value);
static int widget_set_text_18_text(void *value);
static int widget_set_text_17_visible(void *value);
static int widget_set_text_17_enable(void *value);
static int widget_set_text_17_text(void *value);
static int widget_set_text_32_visible(void *value);
static int widget_set_text_32_enable(void *value);
static int widget_set_text_32_text(void *value);
static int widget_set_text_16_visible(void *value);
static int widget_set_text_16_enable(void *value);
static int widget_set_text_16_text(void *value);
static int widget_set_text_15_visible(void *value);
static int widget_set_text_15_enable(void *value);
static int widget_set_text_15_text(void *value);
static int widget_set_text_31_visible(void *value);
static int widget_set_text_31_enable(void *value);
static int widget_set_text_31_text(void *value);
static int widget_set_text_14_visible(void *value);
static int widget_set_text_14_enable(void *value);
static int widget_set_text_14_text(void *value);
static int widget_set_text_30_visible(void *value);
static int widget_set_text_30_enable(void *value);
static int widget_set_text_30_text(void *value);
static int widget_set_text_19_visible(void *value);
static int widget_set_text_19_enable(void *value);
static int widget_set_text_19_text(void *value);
static int widget_set_text_9_visible(void *value);
static int widget_set_text_9_enable(void *value);
static int widget_set_text_9_text(void *value);

hmi_widget_func_t hmi_window_77696E5F646973705F626F785F737461747573_prop_funcs[]={
{"button_2_visible",(void *)widget_set_button_2_visible},
{"button_2_enable",(void *)widget_set_button_2_enable},
{"button_visible",(void *)widget_set_button_visible},
{"button_enable",(void *)widget_set_button_enable},
{"text_13_visible",(void *)widget_set_text_13_visible},
{"text_13_enable",(void *)widget_set_text_13_enable},
{"text_13_text",(void *)widget_set_text_13_text},
{"text_29_visible",(void *)widget_set_text_29_visible},
{"text_29_enable",(void *)widget_set_text_29_enable},
{"text_29_text",(void *)widget_set_text_29_text},
{"text_12_visible",(void *)widget_set_text_12_visible},
{"text_12_enable",(void *)widget_set_text_12_enable},
{"text_12_text",(void *)widget_set_text_12_text},
{"text_11_visible",(void *)widget_set_text_11_visible},
{"text_11_enable",(void *)widget_set_text_11_enable},
{"text_11_text",(void *)widget_set_text_11_text},
{"text_28_visible",(void *)widget_set_text_28_visible},
{"text_28_enable",(void *)widget_set_text_28_enable},
{"text_28_text",(void *)widget_set_text_28_text},
{"text_10_visible",(void *)widget_set_text_10_visible},
{"text_10_enable",(void *)widget_set_text_10_enable},
{"text_10_text",(void *)widget_set_text_10_text},
{"text_8_visible",(void *)widget_set_text_8_visible},
{"text_8_enable",(void *)widget_set_text_8_enable},
{"text_8_text",(void *)widget_set_text_8_text},
{"text_27_visible",(void *)widget_set_text_27_visible},
{"text_27_enable",(void *)widget_set_text_27_enable},
{"text_27_text",(void *)widget_set_text_27_text},
{"text_7_visible",(void *)widget_set_text_7_visible},
{"text_7_enable",(void *)widget_set_text_7_enable},
{"text_7_text",(void *)widget_set_text_7_text},
{"text_25_visible",(void *)widget_set_text_25_visible},
{"text_25_enable",(void *)widget_set_text_25_enable},
{"text_25_text",(void *)widget_set_text_25_text},
{"text_6_visible",(void *)widget_set_text_6_visible},
{"text_6_enable",(void *)widget_set_text_6_enable},
{"text_6_text",(void *)widget_set_text_6_text},
{"text_5_visible",(void *)widget_set_text_5_visible},
{"text_5_enable",(void *)widget_set_text_5_enable},
{"text_5_text",(void *)widget_set_text_5_text},
{"text_20_visible",(void *)widget_set_text_20_visible},
{"text_20_enable",(void *)widget_set_text_20_enable},
{"text_20_text",(void *)widget_set_text_20_text},
{"text_33_visible",(void *)widget_set_text_33_visible},
{"text_33_enable",(void *)widget_set_text_33_enable},
{"text_33_text",(void *)widget_set_text_33_text},
{"text_18_visible",(void *)widget_set_text_18_visible},
{"text_18_enable",(void *)widget_set_text_18_enable},
{"text_18_text",(void *)widget_set_text_18_text},
{"text_17_visible",(void *)widget_set_text_17_visible},
{"text_17_enable",(void *)widget_set_text_17_enable},
{"text_17_text",(void *)widget_set_text_17_text},
{"text_32_visible",(void *)widget_set_text_32_visible},
{"text_32_enable",(void *)widget_set_text_32_enable},
{"text_32_text",(void *)widget_set_text_32_text},
{"text_16_visible",(void *)widget_set_text_16_visible},
{"text_16_enable",(void *)widget_set_text_16_enable},
{"text_16_text",(void *)widget_set_text_16_text},
{"text_15_visible",(void *)widget_set_text_15_visible},
{"text_15_enable",(void *)widget_set_text_15_enable},
{"text_15_text",(void *)widget_set_text_15_text},
{"text_31_visible",(void *)widget_set_text_31_visible},
{"text_31_enable",(void *)widget_set_text_31_enable},
{"text_31_text",(void *)widget_set_text_31_text},
{"text_14_visible",(void *)widget_set_text_14_visible},
{"text_14_enable",(void *)widget_set_text_14_enable},
{"text_14_text",(void *)widget_set_text_14_text},
{"text_30_visible",(void *)widget_set_text_30_visible},
{"text_30_enable",(void *)widget_set_text_30_enable},
{"text_30_text",(void *)widget_set_text_30_text},
{"text_19_visible",(void *)widget_set_text_19_visible},
{"text_19_enable",(void *)widget_set_text_19_enable},
{"text_19_text",(void *)widget_set_text_19_text},
{"text_9_visible",(void *)widget_set_text_9_visible},
{"text_9_enable",(void *)widget_set_text_9_enable},
{"text_9_text",(void *)widget_set_text_9_text},
{NULL,NULL}
};

static u8 widget_set_button_2_visible__()
{
	static void *__hmi_var_0_ptr;
	u8 __hmi_var_0 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_0_ptr));
	static void *__hmi_var_1_ptr;
	u8 __hmi_var_1 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_1_ptr));
	{
#line 1 "控件:button_2,属性:visible"
if(((__hmi_var_0+1)*8) >= __hmi_var_1)
{
    return 0;
}
return 1;

	}
}

static int widget_set_button_2_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_2_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_2_enable__()
{
	static void *__hmi_var_2_ptr;
	u8 __hmi_var_2 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_2_ptr));
	static void *__hmi_var_3_ptr;
	u8 __hmi_var_3 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_3_ptr));
	{
#line 1 "控件:button_2,属性:enable"
if(((__hmi_var_2+1)*8) >= __hmi_var_3)
{
    return 0;
}
return 1;

	}
}

static int widget_set_button_2_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_2_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_visible__()
{
	static void *__hmi_var_5_ptr;
	u8 __hmi_var_5 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_5_ptr));
	{
#line 1 "控件:button,属性:visible"
if(__hmi_var_5 == 0)
{
    return 0;
}
return 1;
	}
}

static int widget_set_button_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_enable__()
{
	static void *__hmi_var_6_ptr;
	u8 __hmi_var_6 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_6_ptr));
	{
#line 1 "控件:button,属性:enable"
if(__hmi_var_6 == 0)
{
    return 0;
}
return 1;
	}
}

static int widget_set_button_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_13_visible__()
{
	static void *__hmi_var_8_ptr;
	u8 __hmi_var_8 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_8_ptr));
	static void *__hmi_var_9_ptr;
	u8 __hmi_var_9 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_9_ptr));
	{
#line 1 "控件:text_13,属性:visible"
if((__hmi_var_8*8 + 4) > __hmi_var_9)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_13_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_13_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_13_enable__()
{
	static void *__hmi_var_10_ptr;
	u8 __hmi_var_10 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_10_ptr));
	static void *__hmi_var_11_ptr;
	u8 __hmi_var_11 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_11_ptr));
	{
#line 1 "控件:text_13,属性:enable"
if((__hmi_var_10*8 + 4) > __hmi_var_11)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_13_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_13_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_13_text__()
{
	static void *__hmi_var_12_ptr;
	u8 __hmi_var_12 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_12_ptr));
	static void *__hmi_var_13_ptr;
	char * __hmi_var_13 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_idle",&__hmi_var_13_ptr));
	static void *__hmi_var_14_ptr;
	char * __hmi_var_14 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_use",&__hmi_var_14_ptr));
	static void *__hmi_var_15_ptr;
	char * __hmi_var_15 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_lock",&__hmi_var_15_ptr));
	static void *__hmi_var_16_ptr;
	char * __hmi_var_16 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_16_ptr));
	{
#line 1 "控件:text_13,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_12*8 + 4;
read_box_info_station_num(box_index , &box_info);
if(box_info.status == BOX_IDLE)
{
    return __hmi_var_13;
}
if(box_info.status == BOX_USED)
{
    return __hmi_var_14;
}
if(box_info.status == BOX_LOCK)
{
    return __hmi_var_15;
}
return __hmi_var_16;

	}
}

static int widget_set_text_13_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_13_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_29_visible__()
{
	static void *__hmi_var_17_ptr;
	u8 __hmi_var_17 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_17_ptr));
	static void *__hmi_var_18_ptr;
	u8 __hmi_var_18 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_18_ptr));
	{
#line 1 "控件:text_29,属性:visible"
if((__hmi_var_17*8 + 4) > __hmi_var_18)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_29_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_29_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_29_enable__()
{
	static void *__hmi_var_19_ptr;
	u8 __hmi_var_19 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_19_ptr));
	static void *__hmi_var_20_ptr;
	u8 __hmi_var_20 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_20_ptr));
	{
#line 1 "控件:text_29,属性:enable"
if((__hmi_var_19*8 + 4) > __hmi_var_20)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_29_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_29_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_29_text__()
{
	static void *__hmi_var_21_ptr;
	u8 __hmi_var_21 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_21_ptr));
	static void *__hmi_var_22_ptr;
	char * __hmi_var_22 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_22_ptr));
	static void *__hmi_var_23_ptr;
	char * __hmi_var_23 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_23_ptr));
	static void *__hmi_var_24_ptr;
	char * __hmi_var_24 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_24_ptr));
	static void *__hmi_var_25_ptr;
	char * __hmi_var_25 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_25_ptr));
	{
#line 1 "控件:text_29,属性:text"
u8 box_index;
BOX_MSG box_info;


box_index = __hmi_var_21*8 + 4;
read_box_info_station_num(box_index , &box_info);
if(box_info.type == BOX_TYPE_MIN)
{
    return __hmi_var_22;
}
if(box_info.type == BOX_TYPE_MID)
{
    return __hmi_var_23;
}
if(box_info.type == BOX_TYPE_MAX)
{
    return __hmi_var_24;
}
return __hmi_var_25;

	}
}

static int widget_set_text_29_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_29_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_12_visible__()
{
	static void *__hmi_var_26_ptr;
	u8 __hmi_var_26 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_26_ptr));
	static void *__hmi_var_27_ptr;
	u8 __hmi_var_27 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_27_ptr));
	{
#line 1 "控件:text_12,属性:visible"
if((__hmi_var_26*8 + 4) > __hmi_var_27)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_12_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_12_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_12_enable__()
{
	static void *__hmi_var_28_ptr;
	u8 __hmi_var_28 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_28_ptr));
	static void *__hmi_var_29_ptr;
	u8 __hmi_var_29 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_29_ptr));
	{
#line 1 "控件:text_12,属性:enable"
if((__hmi_var_28*8 + 4) > __hmi_var_29)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_12_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_12_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_12_text__()
{
	static void *__hmi_var_30_ptr;
	u8 __hmi_var_30 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_30_ptr));
	{
#line 1 "控件:text_12,属性:text"
static char box_vir_num[5];
u8 box_index;
BOX_MSG box_info;

memset(box_vir_num , 0 , 5);
box_index = __hmi_var_30*8 + 4;
if(1 == read_box_info_station_num(box_index , &box_info))
{
    memcpy(box_vir_num , box_info.virtualnumber,4);
}
return box_vir_num;

	}
}

static int widget_set_text_12_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_12_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_11_visible__()
{
	static void *__hmi_var_31_ptr;
	u8 __hmi_var_31 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_31_ptr));
	static void *__hmi_var_32_ptr;
	u8 __hmi_var_32 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_32_ptr));
	{
#line 1 "控件:text_11,属性:visible"
if((__hmi_var_31*8 + 3) > __hmi_var_32)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_11_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_11_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_11_enable__()
{
	static void *__hmi_var_33_ptr;
	u8 __hmi_var_33 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_33_ptr));
	static void *__hmi_var_34_ptr;
	u8 __hmi_var_34 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_34_ptr));
	{
#line 1 "控件:text_11,属性:enable"
if((__hmi_var_33*8 + 3) > __hmi_var_34)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_11_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_11_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_11_text__()
{
	static void *__hmi_var_35_ptr;
	u8 __hmi_var_35 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_35_ptr));
	static void *__hmi_var_36_ptr;
	char * __hmi_var_36 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_idle",&__hmi_var_36_ptr));
	static void *__hmi_var_37_ptr;
	char * __hmi_var_37 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_use",&__hmi_var_37_ptr));
	static void *__hmi_var_38_ptr;
	char * __hmi_var_38 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_lock",&__hmi_var_38_ptr));
	static void *__hmi_var_39_ptr;
	char * __hmi_var_39 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_39_ptr));
	{
#line 1 "控件:text_11,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_35*8 + 3;
read_box_info_station_num(box_index , &box_info);
if(box_info.status == BOX_IDLE)
{
    return __hmi_var_36;
}
if(box_info.status == BOX_USED)
{
    return __hmi_var_37;
}
if(box_info.status == BOX_LOCK)
{
    return __hmi_var_38;
}
return __hmi_var_39;

	}
}

static int widget_set_text_11_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_11_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_28_visible__()
{
	static void *__hmi_var_40_ptr;
	u8 __hmi_var_40 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_40_ptr));
	static void *__hmi_var_41_ptr;
	u8 __hmi_var_41 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_41_ptr));
	{
#line 1 "控件:text_28,属性:visible"
if((__hmi_var_40*8 + 3) > __hmi_var_41)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_28_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_28_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_28_enable__()
{
	static void *__hmi_var_42_ptr;
	u8 __hmi_var_42 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_42_ptr));
	static void *__hmi_var_43_ptr;
	u8 __hmi_var_43 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_43_ptr));
	{
#line 1 "控件:text_28,属性:enable"
if((__hmi_var_42*8 + 3) > __hmi_var_43)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_28_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_28_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_28_text__()
{
	static void *__hmi_var_44_ptr;
	u8 __hmi_var_44 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_44_ptr));
	static void *__hmi_var_45_ptr;
	char * __hmi_var_45 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_45_ptr));
	static void *__hmi_var_46_ptr;
	char * __hmi_var_46 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_46_ptr));
	static void *__hmi_var_47_ptr;
	char * __hmi_var_47 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_47_ptr));
	static void *__hmi_var_48_ptr;
	char * __hmi_var_48 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_48_ptr));
	{
#line 1 "控件:text_28,属性:text"
u8 box_index;
BOX_MSG box_info;


box_index = __hmi_var_44*8 + 3;
read_box_info_station_num(box_index , &box_info);
if(box_info.type == BOX_TYPE_MIN)
{
    return __hmi_var_45;
}
if(box_info.type == BOX_TYPE_MID)
{
    return __hmi_var_46;
}
if(box_info.type == BOX_TYPE_MAX)
{
    return __hmi_var_47;
}
return __hmi_var_48;

	}
}

static int widget_set_text_28_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_28_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_10_visible__()
{
	static void *__hmi_var_49_ptr;
	u8 __hmi_var_49 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_49_ptr));
	static void *__hmi_var_50_ptr;
	u8 __hmi_var_50 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_50_ptr));
	{
#line 1 "控件:text_10,属性:visible"
if((__hmi_var_49*8 + 3) > __hmi_var_50)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_10_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_10_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_10_enable__()
{
	static void *__hmi_var_51_ptr;
	u8 __hmi_var_51 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_51_ptr));
	static void *__hmi_var_52_ptr;
	u8 __hmi_var_52 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_52_ptr));
	{
#line 1 "控件:text_10,属性:enable"
if((__hmi_var_51*8 + 3) > __hmi_var_52)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_10_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_10_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_10_text__()
{
	static void *__hmi_var_53_ptr;
	u8 __hmi_var_53 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_53_ptr));
	{
#line 1 "控件:text_10,属性:text"
static char box_vir_num[5];
u8 box_index;
BOX_MSG box_info;

memset(box_vir_num , 0 , 5);
box_index = __hmi_var_53*8 + 3;
if(1 == read_box_info_station_num(box_index , &box_info))
{
    memcpy(box_vir_num , box_info.virtualnumber,4);
}
return box_vir_num;

	}
}

static int widget_set_text_10_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_10_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_8_visible__()
{
	static void *__hmi_var_54_ptr;
	u8 __hmi_var_54 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_54_ptr));
	static void *__hmi_var_55_ptr;
	u8 __hmi_var_55 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_55_ptr));
	{
#line 1 "控件:text_8,属性:visible"
if((__hmi_var_54*8 + 2) > __hmi_var_55)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_8_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_8_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_8_enable__()
{
	static void *__hmi_var_56_ptr;
	u8 __hmi_var_56 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_56_ptr));
	static void *__hmi_var_57_ptr;
	u8 __hmi_var_57 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_57_ptr));
	{
#line 1 "控件:text_8,属性:enable"
if((__hmi_var_56*8 + 2) > __hmi_var_57)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_8_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_8_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_8_text__()
{
	static void *__hmi_var_58_ptr;
	u8 __hmi_var_58 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_58_ptr));
	static void *__hmi_var_59_ptr;
	char * __hmi_var_59 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_idle",&__hmi_var_59_ptr));
	static void *__hmi_var_60_ptr;
	char * __hmi_var_60 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_use",&__hmi_var_60_ptr));
	static void *__hmi_var_61_ptr;
	char * __hmi_var_61 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_lock",&__hmi_var_61_ptr));
	static void *__hmi_var_62_ptr;
	char * __hmi_var_62 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_62_ptr));
	{
#line 1 "控件:text_8,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_58*8 + 2;
read_box_info_station_num(box_index , &box_info);
if(box_info.status == BOX_IDLE)
{
    return __hmi_var_59;
}
if(box_info.status == BOX_USED)
{
    return __hmi_var_60;
}
if(box_info.status == BOX_LOCK)
{
    return __hmi_var_61;
}
return __hmi_var_62;

	}
}

static int widget_set_text_8_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_8_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_27_visible__()
{
	static void *__hmi_var_63_ptr;
	u8 __hmi_var_63 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_63_ptr));
	static void *__hmi_var_64_ptr;
	u8 __hmi_var_64 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_64_ptr));
	{
#line 1 "控件:text_27,属性:visible"
if((__hmi_var_63*8 + 2) > __hmi_var_64)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_27_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_27_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_27_enable__()
{
	static void *__hmi_var_65_ptr;
	u8 __hmi_var_65 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_65_ptr));
	static void *__hmi_var_66_ptr;
	u8 __hmi_var_66 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_66_ptr));
	{
#line 1 "控件:text_27,属性:enable"
if((__hmi_var_65*8 + 2) > __hmi_var_66)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_27_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_27_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_27_text__()
{
	static void *__hmi_var_67_ptr;
	u8 __hmi_var_67 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_67_ptr));
	static void *__hmi_var_68_ptr;
	char * __hmi_var_68 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_68_ptr));
	static void *__hmi_var_69_ptr;
	char * __hmi_var_69 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_69_ptr));
	static void *__hmi_var_70_ptr;
	char * __hmi_var_70 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_70_ptr));
	static void *__hmi_var_71_ptr;
	char * __hmi_var_71 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_71_ptr));
	{
#line 1 "控件:text_27,属性:text"
u8 box_index;
BOX_MSG box_info;


box_index = __hmi_var_67*8 + 2;
read_box_info_station_num(box_index , &box_info);
if(box_info.type == BOX_TYPE_MIN)
{
    return __hmi_var_68;
}
if(box_info.type == BOX_TYPE_MID)
{
    return __hmi_var_69;
}
if(box_info.type == BOX_TYPE_MAX)
{
    return __hmi_var_70;
}
return __hmi_var_71;

	}
}

static int widget_set_text_27_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_27_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_7_visible__()
{
	static void *__hmi_var_72_ptr;
	u8 __hmi_var_72 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_72_ptr));
	static void *__hmi_var_73_ptr;
	u8 __hmi_var_73 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_73_ptr));
	{
#line 1 "控件:text_7,属性:visible"
if((__hmi_var_72*8 + 2) > __hmi_var_73)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_7_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_7_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_7_enable__()
{
	static void *__hmi_var_74_ptr;
	u8 __hmi_var_74 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_74_ptr));
	static void *__hmi_var_75_ptr;
	u8 __hmi_var_75 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_75_ptr));
	{
#line 1 "控件:text_7,属性:enable"
if((__hmi_var_74*8 + 2) > __hmi_var_75)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_7_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_7_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_7_text__()
{
	static void *__hmi_var_76_ptr;
	u8 __hmi_var_76 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_76_ptr));
	{
#line 1 "控件:text_7,属性:text"
static char box_vir_num[5];
u8 box_index;
BOX_MSG box_info;

memset(box_vir_num , 0 , 5);
box_index = __hmi_var_76*8 + 2;
if(1 == read_box_info_station_num(box_index , &box_info))
{
    memcpy(box_vir_num , box_info.virtualnumber,4);
}
return box_vir_num;

	}
}

static int widget_set_text_7_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_7_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_25_visible__()
{
	static void *__hmi_var_77_ptr;
	u8 __hmi_var_77 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_77_ptr));
	static void *__hmi_var_78_ptr;
	u8 __hmi_var_78 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_78_ptr));
	{
#line 1 "控件:text_25,属性:visible"
if((__hmi_var_77*8 + 1) > __hmi_var_78)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_25_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_25_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_25_enable__()
{
	static void *__hmi_var_79_ptr;
	u8 __hmi_var_79 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_79_ptr));
	static void *__hmi_var_80_ptr;
	u8 __hmi_var_80 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_80_ptr));
	{
#line 1 "控件:text_25,属性:enable"
if((__hmi_var_79*8 + 1) > __hmi_var_80)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_25_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_25_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_25_text__()
{
	static void *__hmi_var_81_ptr;
	u8 __hmi_var_81 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_81_ptr));
	static void *__hmi_var_82_ptr;
	char * __hmi_var_82 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_82_ptr));
	static void *__hmi_var_83_ptr;
	char * __hmi_var_83 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_83_ptr));
	static void *__hmi_var_84_ptr;
	char * __hmi_var_84 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_84_ptr));
	{
#line 1 "控件:text_25,属性:text"
u8 box_index;
BOX_MSG box_info;


box_index = __hmi_var_81*8 + 1;
read_box_info_station_num(box_index , &box_info);
if(box_info.type == BOX_TYPE_MIN)
{
    return __hmi_var_82;
}
if(box_info.type == BOX_TYPE_MID)
{
    return __hmi_var_83;
}
if(box_info.type == BOX_TYPE_MAX)
{
    return __hmi_var_84;
}

	}
}

static int widget_set_text_25_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_25_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_6_visible__()
{
	static void *__hmi_var_85_ptr;
	u8 __hmi_var_85 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_85_ptr));
	static void *__hmi_var_86_ptr;
	u8 __hmi_var_86 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_86_ptr));
	{
#line 1 "控件:text_6,属性:visible"
if((__hmi_var_85*8 + 1) > __hmi_var_86)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_6_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_6_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_6_enable__()
{
	static void *__hmi_var_87_ptr;
	u8 __hmi_var_87 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_87_ptr));
	static void *__hmi_var_88_ptr;
	u8 __hmi_var_88 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_88_ptr));
	{
#line 1 "控件:text_6,属性:enable"
if((__hmi_var_87*8 + 1) > __hmi_var_88)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_6_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_6_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_6_text__()
{
	static void *__hmi_var_89_ptr;
	u8 __hmi_var_89 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_89_ptr));
	static void *__hmi_var_90_ptr;
	char * __hmi_var_90 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_idle",&__hmi_var_90_ptr));
	static void *__hmi_var_91_ptr;
	char * __hmi_var_91 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_use",&__hmi_var_91_ptr));
	static void *__hmi_var_92_ptr;
	char * __hmi_var_92 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_lock",&__hmi_var_92_ptr));
	{
#line 1 "控件:text_6,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_89*8 + 1;
read_box_info_station_num(box_index , &box_info);
if(box_info.status == BOX_IDLE)
{
    return __hmi_var_90;
}
if(box_info.status == BOX_USED)
{
    return __hmi_var_91;
}
if(box_info.status == BOX_LOCK)
{
    return __hmi_var_92;
}

	}
}

static int widget_set_text_6_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_6_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_5_visible__()
{
	static void *__hmi_var_93_ptr;
	u8 __hmi_var_93 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_93_ptr));
	static void *__hmi_var_94_ptr;
	u8 __hmi_var_94 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_94_ptr));
	{
#line 1 "控件:text_5,属性:visible"
if((__hmi_var_93*8 + 1) > __hmi_var_94)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_5_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_5_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_5_enable__()
{
	static void *__hmi_var_95_ptr;
	u8 __hmi_var_95 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_95_ptr));
	static void *__hmi_var_96_ptr;
	u8 __hmi_var_96 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_96_ptr));
	{
#line 1 "控件:text_5,属性:enable"
if((__hmi_var_95*8 + 1) > __hmi_var_96)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_5_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_5_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_5_text__()
{
	static void *__hmi_var_97_ptr;
	u8 __hmi_var_97 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_97_ptr));
	{
#line 1 "控件:text_5,属性:text"
static char box_vir_num[5];
u8 box_index;
BOX_MSG box_info;

memset(box_vir_num , 0 , 5);
box_index = __hmi_var_97*8 + 1;
read_box_info_station_num(box_index , &box_info);
memcpy(box_vir_num , box_info.virtualnumber,4);
return box_vir_num;

	}
}

static int widget_set_text_5_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_5_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_20_visible__()
{
	static void *__hmi_var_98_ptr;
	u8 __hmi_var_98 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_98_ptr));
	static void *__hmi_var_99_ptr;
	u8 __hmi_var_99 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_99_ptr));
	{
#line 1 "控件:text_20,属性:visible"
if((__hmi_var_98*8 + 7) > __hmi_var_99)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_20_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_20_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_20_enable__()
{
	static void *__hmi_var_100_ptr;
	u8 __hmi_var_100 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_100_ptr));
	static void *__hmi_var_101_ptr;
	u8 __hmi_var_101 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_101_ptr));
	{
#line 1 "控件:text_20,属性:enable"
if((__hmi_var_100*8 + 7) > __hmi_var_101)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_20_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_20_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_20_text__()
{
	static void *__hmi_var_102_ptr;
	u8 __hmi_var_102 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_102_ptr));
	static void *__hmi_var_103_ptr;
	char * __hmi_var_103 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_idle",&__hmi_var_103_ptr));
	static void *__hmi_var_104_ptr;
	char * __hmi_var_104 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_use",&__hmi_var_104_ptr));
	static void *__hmi_var_105_ptr;
	char * __hmi_var_105 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_lock",&__hmi_var_105_ptr));
	static void *__hmi_var_106_ptr;
	char * __hmi_var_106 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_106_ptr));
	{
#line 1 "控件:text_20,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_102*8 + 7;
read_box_info_station_num(box_index , &box_info);
if(box_info.status == BOX_IDLE)
{
    return __hmi_var_103;
}
if(box_info.status == BOX_USED)
{
    return __hmi_var_104;
}
if(box_info.status == BOX_LOCK)
{
    return __hmi_var_105;
}
return __hmi_var_106;

	}
}

static int widget_set_text_20_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_20_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_33_visible__()
{
	static void *__hmi_var_107_ptr;
	u8 __hmi_var_107 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_107_ptr));
	static void *__hmi_var_108_ptr;
	u8 __hmi_var_108 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_108_ptr));
	{
#line 1 "控件:text_33,属性:visible"
if((__hmi_var_107*8 + 7) > __hmi_var_108)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_33_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_33_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_33_enable__()
{
	static void *__hmi_var_109_ptr;
	u8 __hmi_var_109 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_109_ptr));
	static void *__hmi_var_110_ptr;
	u8 __hmi_var_110 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_110_ptr));
	{
#line 1 "控件:text_33,属性:enable"
if((__hmi_var_109*8 + 7) > __hmi_var_110)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_33_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_33_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_33_text__()
{
	static void *__hmi_var_111_ptr;
	u8 __hmi_var_111 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_111_ptr));
	static void *__hmi_var_112_ptr;
	char * __hmi_var_112 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_112_ptr));
	static void *__hmi_var_113_ptr;
	char * __hmi_var_113 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_113_ptr));
	static void *__hmi_var_114_ptr;
	char * __hmi_var_114 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_114_ptr));
	static void *__hmi_var_115_ptr;
	char * __hmi_var_115 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_115_ptr));
	{
#line 1 "控件:text_33,属性:text"
u8 box_index;
BOX_MSG box_info;


box_index = __hmi_var_111*8 + 7;
read_box_info_station_num(box_index , &box_info);
if(box_info.type == BOX_TYPE_MIN)
{
    return __hmi_var_112;
}
if(box_info.type == BOX_TYPE_MID)
{
    return __hmi_var_113;
}
if(box_info.type == BOX_TYPE_MAX)
{
    return __hmi_var_114;
}
return __hmi_var_115;

	}
}

static int widget_set_text_33_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_33_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_18_visible__()
{
	static void *__hmi_var_116_ptr;
	u8 __hmi_var_116 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_116_ptr));
	static void *__hmi_var_117_ptr;
	u8 __hmi_var_117 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_117_ptr));
	{
#line 1 "控件:text_18,属性:visible"
if((__hmi_var_116*8 + 7) > __hmi_var_117)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_18_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_18_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_18_enable__()
{
	static void *__hmi_var_118_ptr;
	u8 __hmi_var_118 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_118_ptr));
	static void *__hmi_var_119_ptr;
	u8 __hmi_var_119 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_119_ptr));
	{
#line 1 "控件:text_18,属性:enable"
if((__hmi_var_118*8 + 7) > __hmi_var_119)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_18_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_18_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_18_text__()
{
	static void *__hmi_var_120_ptr;
	u8 __hmi_var_120 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_120_ptr));
	{
#line 1 "控件:text_18,属性:text"
static char box_vir_num[5];
u8 box_index;
BOX_MSG box_info;

memset(box_vir_num , 0 , 5);
box_index = __hmi_var_120*8 + 7;
if(1 == read_box_info_station_num(box_index , &box_info))
{
    memcpy(box_vir_num , box_info.virtualnumber,4);
}
return box_vir_num;

	}
}

static int widget_set_text_18_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_18_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_17_visible__()
{
	static void *__hmi_var_121_ptr;
	u8 __hmi_var_121 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_121_ptr));
	static void *__hmi_var_122_ptr;
	u8 __hmi_var_122 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_122_ptr));
	{
#line 1 "控件:text_17,属性:visible"
if((__hmi_var_121*8 + 6) > __hmi_var_122)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_17_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_17_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_17_enable__()
{
	static void *__hmi_var_123_ptr;
	u8 __hmi_var_123 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_123_ptr));
	static void *__hmi_var_124_ptr;
	u8 __hmi_var_124 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_124_ptr));
	{
#line 1 "控件:text_17,属性:enable"
if((__hmi_var_123*8 + 6) > __hmi_var_124)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_17_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_17_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_17_text__()
{
	static void *__hmi_var_125_ptr;
	u8 __hmi_var_125 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_125_ptr));
	static void *__hmi_var_126_ptr;
	char * __hmi_var_126 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_idle",&__hmi_var_126_ptr));
	static void *__hmi_var_127_ptr;
	char * __hmi_var_127 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_use",&__hmi_var_127_ptr));
	static void *__hmi_var_128_ptr;
	char * __hmi_var_128 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_lock",&__hmi_var_128_ptr));
	static void *__hmi_var_129_ptr;
	char * __hmi_var_129 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_129_ptr));
	{
#line 1 "控件:text_17,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_125*8 + 6;
read_box_info_station_num(box_index , &box_info);
if(box_info.status == BOX_IDLE)
{
    return __hmi_var_126;
}
if(box_info.status == BOX_USED)
{
    return __hmi_var_127;
}
if(box_info.status == BOX_LOCK)
{
    return __hmi_var_128;
}
return __hmi_var_129;

	}
}

static int widget_set_text_17_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_17_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_32_visible__()
{
	static void *__hmi_var_130_ptr;
	u8 __hmi_var_130 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_130_ptr));
	static void *__hmi_var_131_ptr;
	u8 __hmi_var_131 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_131_ptr));
	{
#line 1 "控件:text_32,属性:visible"
if((__hmi_var_130*8 + 6) > __hmi_var_131)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_32_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_32_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_32_enable__()
{
	static void *__hmi_var_132_ptr;
	u8 __hmi_var_132 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_132_ptr));
	static void *__hmi_var_133_ptr;
	u8 __hmi_var_133 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_133_ptr));
	{
#line 1 "控件:text_32,属性:enable"
if((__hmi_var_132*8 + 6) > __hmi_var_133)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_32_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_32_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_32_text__()
{
	static void *__hmi_var_134_ptr;
	u8 __hmi_var_134 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_134_ptr));
	static void *__hmi_var_135_ptr;
	char * __hmi_var_135 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_135_ptr));
	static void *__hmi_var_136_ptr;
	char * __hmi_var_136 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_136_ptr));
	static void *__hmi_var_137_ptr;
	char * __hmi_var_137 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_137_ptr));
	static void *__hmi_var_138_ptr;
	char * __hmi_var_138 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_138_ptr));
	{
#line 1 "控件:text_32,属性:text"
u8 box_index;
BOX_MSG box_info;


box_index = __hmi_var_134*8 + 6;
read_box_info_station_num(box_index , &box_info);
if(box_info.type == BOX_TYPE_MIN)
{
    return __hmi_var_135;
}
if(box_info.type == BOX_TYPE_MID)
{
    return __hmi_var_136;
}
if(box_info.type == BOX_TYPE_MAX)
{
    return __hmi_var_137;
}
return __hmi_var_138;

	}
}

static int widget_set_text_32_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_32_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_16_visible__()
{
	static void *__hmi_var_139_ptr;
	u8 __hmi_var_139 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_139_ptr));
	static void *__hmi_var_140_ptr;
	u8 __hmi_var_140 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_140_ptr));
	{
#line 1 "控件:text_16,属性:visible"
if((__hmi_var_139*8 + 6) > __hmi_var_140)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_16_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_16_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_16_enable__()
{
	static void *__hmi_var_141_ptr;
	u8 __hmi_var_141 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_141_ptr));
	static void *__hmi_var_142_ptr;
	u8 __hmi_var_142 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_142_ptr));
	{
#line 1 "控件:text_16,属性:enable"
if((__hmi_var_141*8 + 6) > __hmi_var_142)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_16_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_16_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_16_text__()
{
	static void *__hmi_var_143_ptr;
	u8 __hmi_var_143 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_143_ptr));
	{
#line 1 "控件:text_16,属性:text"
static char box_vir_num[5];
u8 box_index;
BOX_MSG box_info;

memset(box_vir_num , 0 , 5);
box_index = __hmi_var_143*8 + 6;
if(1 == read_box_info_station_num(box_index , &box_info))
{
    memcpy(box_vir_num , box_info.virtualnumber,4);
}
return box_vir_num;

	}
}

static int widget_set_text_16_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_16_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_15_visible__()
{
	static void *__hmi_var_144_ptr;
	u8 __hmi_var_144 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_144_ptr));
	static void *__hmi_var_145_ptr;
	u8 __hmi_var_145 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_145_ptr));
	{
#line 1 "控件:text_15,属性:visible"
if((__hmi_var_144*8 + 5) > __hmi_var_145)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_15_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_15_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_15_enable__()
{
	static void *__hmi_var_146_ptr;
	u8 __hmi_var_146 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_146_ptr));
	static void *__hmi_var_147_ptr;
	u8 __hmi_var_147 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_147_ptr));
	{
#line 1 "控件:text_15,属性:enable"
if((__hmi_var_146*8 + 5) > __hmi_var_147)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_15_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_15_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_15_text__()
{
	static void *__hmi_var_148_ptr;
	u8 __hmi_var_148 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_148_ptr));
	static void *__hmi_var_149_ptr;
	char * __hmi_var_149 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_idle",&__hmi_var_149_ptr));
	static void *__hmi_var_150_ptr;
	char * __hmi_var_150 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_use",&__hmi_var_150_ptr));
	static void *__hmi_var_151_ptr;
	char * __hmi_var_151 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_lock",&__hmi_var_151_ptr));
	static void *__hmi_var_152_ptr;
	char * __hmi_var_152 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_152_ptr));
	{
#line 1 "控件:text_15,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_148*8 + 5;
read_box_info_station_num(box_index , &box_info);
if(box_info.status == BOX_IDLE)
{
    return __hmi_var_149;
}
if(box_info.status == BOX_USED)
{
    return __hmi_var_150;
}
if(box_info.status == BOX_LOCK)
{
    return __hmi_var_151;
}
return __hmi_var_152;

	}
}

static int widget_set_text_15_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_15_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_31_visible__()
{
	static void *__hmi_var_153_ptr;
	u8 __hmi_var_153 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_153_ptr));
	static void *__hmi_var_154_ptr;
	u8 __hmi_var_154 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_154_ptr));
	{
#line 1 "控件:text_31,属性:visible"
if((__hmi_var_153*8 + 5) > __hmi_var_154)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_31_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_31_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_31_enable__()
{
	static void *__hmi_var_155_ptr;
	u8 __hmi_var_155 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_155_ptr));
	static void *__hmi_var_156_ptr;
	u8 __hmi_var_156 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_156_ptr));
	{
#line 1 "控件:text_31,属性:enable"
if((__hmi_var_155*8 + 5) > __hmi_var_156)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_31_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_31_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_31_text__()
{
	static void *__hmi_var_157_ptr;
	u8 __hmi_var_157 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_157_ptr));
	static void *__hmi_var_158_ptr;
	char * __hmi_var_158 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_158_ptr));
	static void *__hmi_var_159_ptr;
	char * __hmi_var_159 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_159_ptr));
	static void *__hmi_var_160_ptr;
	char * __hmi_var_160 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_160_ptr));
	static void *__hmi_var_161_ptr;
	char * __hmi_var_161 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_161_ptr));
	{
#line 1 "控件:text_31,属性:text"
u8 box_index;
BOX_MSG box_info;


box_index = __hmi_var_157*8 + 5;
read_box_info_station_num(box_index , &box_info);
if(box_info.type == BOX_TYPE_MIN)
{
    return __hmi_var_158;
}
if(box_info.type == BOX_TYPE_MID)
{
    return __hmi_var_159;
}
if(box_info.type == BOX_TYPE_MAX)
{
    return __hmi_var_160;
}
return __hmi_var_161;

	}
}

static int widget_set_text_31_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_31_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_14_visible__()
{
	static void *__hmi_var_162_ptr;
	u8 __hmi_var_162 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_162_ptr));
	static void *__hmi_var_163_ptr;
	u8 __hmi_var_163 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_163_ptr));
	{
#line 1 "控件:text_14,属性:visible"
if((__hmi_var_162*8 + 5) > __hmi_var_163)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_14_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_14_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_14_enable__()
{
	static void *__hmi_var_164_ptr;
	u8 __hmi_var_164 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_164_ptr));
	static void *__hmi_var_165_ptr;
	u8 __hmi_var_165 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_165_ptr));
	{
#line 1 "控件:text_14,属性:enable"
if((__hmi_var_164*8 + 5) > __hmi_var_165)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_14_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_14_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_14_text__()
{
	static void *__hmi_var_166_ptr;
	u8 __hmi_var_166 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_166_ptr));
	{
#line 1 "控件:text_14,属性:text"
static char box_vir_num[5];
u8 box_index;
BOX_MSG box_info;

memset(box_vir_num , 0 , 5);
box_index = __hmi_var_166*8 + 5;
if(1 == read_box_info_station_num(box_index , &box_info))
{
    memcpy(box_vir_num , box_info.virtualnumber,4);
}
return box_vir_num;

	}
}

static int widget_set_text_14_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_14_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_30_visible__()
{
	static void *__hmi_var_167_ptr;
	u8 __hmi_var_167 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_167_ptr));
	static void *__hmi_var_168_ptr;
	u8 __hmi_var_168 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_168_ptr));
	{
#line 1 "控件:text_30,属性:visible"
if((__hmi_var_167*8 + 8) > __hmi_var_168)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_30_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_30_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_30_enable__()
{
	static void *__hmi_var_169_ptr;
	u8 __hmi_var_169 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_169_ptr));
	static void *__hmi_var_170_ptr;
	u8 __hmi_var_170 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_170_ptr));
	{
#line 1 "控件:text_30,属性:enable"
if((__hmi_var_169*8 + 8) > __hmi_var_170)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_30_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_30_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_30_text__()
{
	static void *__hmi_var_171_ptr;
	u8 __hmi_var_171 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_171_ptr));
	static void *__hmi_var_172_ptr;
	char * __hmi_var_172 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_172_ptr));
	static void *__hmi_var_173_ptr;
	char * __hmi_var_173 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_173_ptr));
	static void *__hmi_var_174_ptr;
	char * __hmi_var_174 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_174_ptr));
	static void *__hmi_var_175_ptr;
	char * __hmi_var_175 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_175_ptr));
	{
#line 1 "控件:text_30,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_171*8 + 8;
read_box_info_station_num(box_index , &box_info);
if(box_info.type == BOX_TYPE_MIN)
{
    return __hmi_var_172;
}
if(box_info.type == BOX_TYPE_MID)
{
    return __hmi_var_173;
}
if(box_info.type == BOX_TYPE_MAX)
{
    return __hmi_var_174;
}
return __hmi_var_175;

	}
}

static int widget_set_text_30_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_30_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_19_visible__()
{
	static void *__hmi_var_176_ptr;
	u8 __hmi_var_176 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_176_ptr));
	static void *__hmi_var_177_ptr;
	u8 __hmi_var_177 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_177_ptr));
	{
#line 1 "控件:text_19,属性:visible"
if((__hmi_var_176*8 + 8) > __hmi_var_177)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_19_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_19_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_19_enable__()
{
	static void *__hmi_var_178_ptr;
	u8 __hmi_var_178 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_178_ptr));
	static void *__hmi_var_179_ptr;
	u8 __hmi_var_179 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_179_ptr));
	{
#line 1 "控件:text_19,属性:enable"
if((__hmi_var_178*8 + 8) > __hmi_var_179)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_19_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_19_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_19_text__()
{
	static void *__hmi_var_180_ptr;
	u8 __hmi_var_180 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_180_ptr));
	static void *__hmi_var_181_ptr;
	char * __hmi_var_181 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_idle",&__hmi_var_181_ptr));
	static void *__hmi_var_182_ptr;
	char * __hmi_var_182 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_use",&__hmi_var_182_ptr));
	static void *__hmi_var_183_ptr;
	char * __hmi_var_183 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_lock",&__hmi_var_183_ptr));
	static void *__hmi_var_184_ptr;
	char * __hmi_var_184 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_184_ptr));
	{
#line 1 "控件:text_19,属性:text"
u8 box_index;
BOX_MSG box_info;

box_index = __hmi_var_180*8 + 8;
read_box_info_station_num(box_index , &box_info);
if(box_info.status == BOX_IDLE)
{
    return __hmi_var_181;
}
if(box_info.status == BOX_USED)
{
    return __hmi_var_182;
}
if(box_info.status == BOX_LOCK)
{
    return __hmi_var_183;
}
return __hmi_var_184;

	}
}

static int widget_set_text_19_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_19_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_9_visible__()
{
	static void *__hmi_var_185_ptr;
	u8 __hmi_var_185 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_185_ptr));
	static void *__hmi_var_186_ptr;
	u8 __hmi_var_186 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_186_ptr));
	{
#line 1 "控件:text_9,属性:visible"
if((__hmi_var_185*8 + 8) > __hmi_var_186)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_9_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_9_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_9_enable__()
{
	static void *__hmi_var_187_ptr;
	u8 __hmi_var_187 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_187_ptr));
	static void *__hmi_var_188_ptr;
	u8 __hmi_var_188 = (*(u8 *)hmidb_get_data_value_by_ptr("sys_set.box_num",&__hmi_var_188_ptr));
	{
#line 1 "控件:text_9,属性:enable"
if((__hmi_var_187*8 + 8) > __hmi_var_188)//箱子编号大于箱子总数
{
    return 0;//不显示
}
return 1;

	}
}

static int widget_set_text_9_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_9_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_9_text__()
{
	static void *__hmi_var_189_ptr;
	u8 __hmi_var_189 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_189_ptr));
	{
#line 1 "控件:text_9,属性:text"
static char box_vir_num[5];
u8 box_index;
BOX_MSG box_info;

memset(box_vir_num , 0 , 5);
box_index = __hmi_var_189*8 + 8;
if(1 == read_box_info_station_num(box_index , &box_info))
{
    memcpy(box_vir_num , box_info.virtualnumber,4);
}
return box_vir_num;

	}
}

static int widget_set_text_9_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_9_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

#endif
