/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_text_20_visible(void *value);
static int widget_set_text_20_text(void *value);
static int widget_set_text_19_visible(void *value);
static int widget_set_text_19_text(void *value);
static int widget_set_text_18_visible(void *value);
static int widget_set_text_18_text(void *value);
static int widget_set_text_17_visible(void *value);
static int widget_set_text_17_text(void *value);
static int widget_set_button_2_visible(void *value);
static int widget_set_button_2_enable(void *value);
static int widget_set_button_visible(void *value);
static int widget_set_button_enable(void *value);
static int widget_set_button_15_visible(void *value);
static int widget_set_text_16_visible(void *value);
static int widget_set_text_16_text(void *value);
static int widget_set_text_15_visible(void *value);
static int widget_set_text_15_text(void *value);
static int widget_set_text_14_visible(void *value);
static int widget_set_text_14_text(void *value);
static int widget_set_button_14_visible(void *value);
static int widget_set_text_13_visible(void *value);
static int widget_set_text_13_text(void *value);
static int widget_set_text_12_visible(void *value);
static int widget_set_text_12_text(void *value);
static int widget_set_text_11_visible(void *value);
static int widget_set_text_11_text(void *value);
static int widget_set_button_13_visible(void *value);
static int widget_set_text_10_visible(void *value);
static int widget_set_text_10_text(void *value);
static int widget_set_text_9_visible(void *value);
static int widget_set_text_9_text(void *value);
static int widget_set_text_8_visible(void *value);
static int widget_set_text_8_text(void *value);
static int widget_set_button_12_visible(void *value);
static int widget_set_text_7_visible(void *value);
static int widget_set_text_7_text(void *value);
static int widget_set_text_6_visible(void *value);
static int widget_set_text_6_text(void *value);
static int widget_set_text_4_visible(void *value);
static int widget_set_text_4_text(void *value);

hmi_widget_func_t hmi_window_77696E5F686973746F7279_prop_funcs[]={
{"text_20_visible",(void *)widget_set_text_20_visible},
{"text_20_text",(void *)widget_set_text_20_text},
{"text_19_visible",(void *)widget_set_text_19_visible},
{"text_19_text",(void *)widget_set_text_19_text},
{"text_18_visible",(void *)widget_set_text_18_visible},
{"text_18_text",(void *)widget_set_text_18_text},
{"text_17_visible",(void *)widget_set_text_17_visible},
{"text_17_text",(void *)widget_set_text_17_text},
{"button_2_visible",(void *)widget_set_button_2_visible},
{"button_2_enable",(void *)widget_set_button_2_enable},
{"button_visible",(void *)widget_set_button_visible},
{"button_enable",(void *)widget_set_button_enable},
{"button_15_visible",(void *)widget_set_button_15_visible},
{"text_16_visible",(void *)widget_set_text_16_visible},
{"text_16_text",(void *)widget_set_text_16_text},
{"text_15_visible",(void *)widget_set_text_15_visible},
{"text_15_text",(void *)widget_set_text_15_text},
{"text_14_visible",(void *)widget_set_text_14_visible},
{"text_14_text",(void *)widget_set_text_14_text},
{"button_14_visible",(void *)widget_set_button_14_visible},
{"text_13_visible",(void *)widget_set_text_13_visible},
{"text_13_text",(void *)widget_set_text_13_text},
{"text_12_visible",(void *)widget_set_text_12_visible},
{"text_12_text",(void *)widget_set_text_12_text},
{"text_11_visible",(void *)widget_set_text_11_visible},
{"text_11_text",(void *)widget_set_text_11_text},
{"button_13_visible",(void *)widget_set_button_13_visible},
{"text_10_visible",(void *)widget_set_text_10_visible},
{"text_10_text",(void *)widget_set_text_10_text},
{"text_9_visible",(void *)widget_set_text_9_visible},
{"text_9_text",(void *)widget_set_text_9_text},
{"text_8_visible",(void *)widget_set_text_8_visible},
{"text_8_text",(void *)widget_set_text_8_text},
{"button_12_visible",(void *)widget_set_button_12_visible},
{"text_7_visible",(void *)widget_set_text_7_visible},
{"text_7_text",(void *)widget_set_text_7_text},
{"text_6_visible",(void *)widget_set_text_6_visible},
{"text_6_text",(void *)widget_set_text_6_text},
{"text_4_visible",(void *)widget_set_text_4_visible},
{"text_4_text",(void *)widget_set_text_4_text},
{NULL,NULL}
};

static u8 widget_set_text_20_visible__()
{
	static void *__hmi_var_34_ptr;
	u8 __hmi_var_34 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_34_ptr));
	static void *__hmi_var_35_ptr;
	u8 __hmi_var_35 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_35_ptr));
	{
#line 1 "控件:text_20,属性:visible"
unsigned char index;
index = __hmi_var_34*4+4;
if(index > __hmi_var_35)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_20_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_20_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_20_text__()
{
	static void *__hmi_var_36_ptr;
	u8 __hmi_var_36 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_36_ptr));
	{
#line 1 "控件:text_20,属性:text"
static char indexstr[4];
u8 index;
memset(indexstr , 0 , 4);
index = (__hmi_var_36*4)+4;
sprintf(indexstr , "%d" , index);
return indexstr;

	}
}

static int widget_set_text_20_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_20_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_19_visible__()
{
	static void *__hmi_var_37_ptr;
	u8 __hmi_var_37 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_37_ptr));
	static void *__hmi_var_38_ptr;
	u8 __hmi_var_38 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_38_ptr));
	{
#line 1 "控件:text_19,属性:visible"
unsigned char index;
index = __hmi_var_37*4+3;
if(index > __hmi_var_38)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_19_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_19_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_19_text__()
{
	static void *__hmi_var_39_ptr;
	u8 __hmi_var_39 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_39_ptr));
	{
#line 1 "控件:text_19,属性:text"
static char indexstr[4];
u8 index;
memset(indexstr , 0 , 4);
index = (__hmi_var_39*4)+3;
sprintf(indexstr , "%d" , index);
return indexstr;

	}
}

static int widget_set_text_19_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_19_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_18_visible__()
{
	static void *__hmi_var_40_ptr;
	u8 __hmi_var_40 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_40_ptr));
	static void *__hmi_var_41_ptr;
	u8 __hmi_var_41 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_41_ptr));
	{
#line 1 "控件:text_18,属性:visible"
unsigned char index;
index = __hmi_var_40*4+1;
if(index > __hmi_var_41)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_18_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_18_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_18_text__()
{
	static void *__hmi_var_42_ptr;
	u8 __hmi_var_42 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_42_ptr));
	{
#line 1 "控件:text_18,属性:text"
static char indexstr[4];
u8 index;
memset(indexstr , 0 , 4);
index = (__hmi_var_42*4)+1;
sprintf(indexstr , "%d" , index);
return indexstr;

	}
}

static int widget_set_text_18_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_18_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_17_visible__()
{
	static void *__hmi_var_43_ptr;
	u8 __hmi_var_43 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_43_ptr));
	static void *__hmi_var_44_ptr;
	u8 __hmi_var_44 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_44_ptr));
	{
#line 1 "控件:text_17,属性:visible"
unsigned char index;
index = __hmi_var_43*4+2;
if(index > __hmi_var_44)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_17_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_17_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_17_text__()
{
	static void *__hmi_var_45_ptr;
	u8 __hmi_var_45 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_45_ptr));
	{
#line 1 "控件:text_17,属性:text"
static char indexstr[4];
u8 index;
memset(indexstr , 0 , 4);
index = (__hmi_var_45*4)+2;
sprintf(indexstr , "%d" , index);
return indexstr;

	}
}

static int widget_set_text_17_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_17_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_2_visible__()
{
	static void *__hmi_var_46_ptr;
	u8 __hmi_var_46 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_46_ptr));
	static void *__hmi_var_47_ptr;
	u8 __hmi_var_47 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_47_ptr));
	{
#line 1 "控件:button_2,属性:visible"
if(((__hmi_var_46+1)*4) >= __hmi_var_47)
{
    return 0;
}
return 1;

	}
}

static int widget_set_button_2_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_2_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_2_enable__()
{
	static void *__hmi_var_48_ptr;
	u8 __hmi_var_48 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_48_ptr));
	static void *__hmi_var_49_ptr;
	u8 __hmi_var_49 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_49_ptr));
	{
#line 1 "控件:button_2,属性:enable"
if(((__hmi_var_48+1)*4) >= __hmi_var_49)
{
    return 0;
}
return 1;

	}
}

static int widget_set_button_2_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_2_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_visible__()
{
	static void *__hmi_var_51_ptr;
	u8 __hmi_var_51 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_51_ptr));
	{
#line 1 "控件:button,属性:visible"
if(__hmi_var_51 == 0)
{
    return 0;
}
return 1;
	}
}

static int widget_set_button_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_enable__()
{
	static void *__hmi_var_52_ptr;
	u8 __hmi_var_52 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_52_ptr));
	{
#line 1 "控件:button,属性:enable"
if(__hmi_var_52 == 0)
{
    return 0;
}
return 1;
	}
}

static int widget_set_button_enable(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_enable__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_15_visible__()
{
	static void *__hmi_var_54_ptr;
	u8 __hmi_var_54 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_54_ptr));
	static void *__hmi_var_55_ptr;
	u8 __hmi_var_55 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_55_ptr));
	{
#line 1 "控件:button_15,属性:visible"
unsigned char index;
index = __hmi_var_54*4+4;
if(index > __hmi_var_55)
{
    return 0;
}
return 1;

	}
}

static int widget_set_button_15_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_15_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_16_visible__()
{
	static void *__hmi_var_58_ptr;
	u8 __hmi_var_58 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_58_ptr));
	static void *__hmi_var_59_ptr;
	u8 __hmi_var_59 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_59_ptr));
	{
#line 1 "控件:text_16,属性:visible"
unsigned char index;
index = __hmi_var_58*4+4;
if(index > __hmi_var_59)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_16_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_16_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_16_text__()
{
	static void *__hmi_var_60_ptr;
	u8 __hmi_var_60 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_60_ptr));
	static void *__hmi_var_61_ptr;
	char * __hmi_var_61 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_61_ptr));
	{
#line 1 "控件:text_16,属性:text"
u8 index;
HISTORY_MSG history_msg;
static char timestr[12];
index = __hmi_var_60*4+4;
memset(timestr , 0 , 12);
if(1 == read_history_info(index , &history_msg))
{
    memcpy(timestr , datetime2str(history_msg.data_time)+5 , 11);//不显示年
    return timestr;
}
return __hmi_var_61;

	}
}

static int widget_set_text_16_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_16_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_15_visible__()
{
	static void *__hmi_var_62_ptr;
	u8 __hmi_var_62 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_62_ptr));
	static void *__hmi_var_63_ptr;
	u8 __hmi_var_63 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_63_ptr));
	{
#line 1 "控件:text_15,属性:visible"
unsigned char index;
index = __hmi_var_62*4+4;
if(index > __hmi_var_63)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_15_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_15_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_15_text__()
{
	static void *__hmi_var_64_ptr;
	u8 __hmi_var_64 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_64_ptr));
	static void *__hmi_var_65_ptr;
	char * __hmi_var_65 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_idle",&__hmi_var_65_ptr));
	static void *__hmi_var_66_ptr;
	char * __hmi_var_66 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_used",&__hmi_var_66_ptr));
	static void *__hmi_var_67_ptr;
	char * __hmi_var_67 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_lock",&__hmi_var_67_ptr));
	static void *__hmi_var_68_ptr;
	char * __hmi_var_68 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_68_ptr));
	{
#line 1 "控件:text_15,属性:text"
u8 index;
HISTORY_MSG history_msg;
index = __hmi_var_64*4+4;
if(1 == read_history_info(index , &history_msg))
{
    switch(history_msg.box_info.status)
    {
        case BOX_IDLE: return __hmi_var_65;
        case BOX_USED: return __hmi_var_66;
        case BOX_LOCK: return __hmi_var_67;
        default : return __hmi_var_68;
    }
}
return __hmi_var_68;

	}
}

static int widget_set_text_15_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_15_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_14_visible__()
{
	static void *__hmi_var_69_ptr;
	u8 __hmi_var_69 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_69_ptr));
	static void *__hmi_var_70_ptr;
	u8 __hmi_var_70 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_70_ptr));
	{
#line 1 "控件:text_14,属性:visible"
unsigned char index;
index = __hmi_var_69*4+4;
if(index > __hmi_var_70)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_14_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_14_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_14_text__()
{
	static void *__hmi_var_71_ptr;
	u8 __hmi_var_71 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_71_ptr));
	{
#line 1 "控件:text_14,属性:text"
u8 index;
HISTORY_MSG history_msg;
static char virturlbuf[5];
index = __hmi_var_71*4+4;
memset(virturlbuf , 0 , 4);
if(1 == read_history_info(index , &history_msg))
{
    memcpy(virturlbuf , history_msg.box_info.virtualnumber , VIRTUAL_NUM_LENGTH);
}
return virturlbuf;

	}
}

static int widget_set_text_14_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_14_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_14_visible__()
{
	static void *__hmi_var_72_ptr;
	u8 __hmi_var_72 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_72_ptr));
	static void *__hmi_var_73_ptr;
	u8 __hmi_var_73 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_73_ptr));
	{
#line 1 "控件:button_14,属性:visible"
unsigned char index;
index = __hmi_var_72*4+3;
if(index > __hmi_var_73)
{
    return 0;
}
return 1;

	}
}

static int widget_set_button_14_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_14_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_13_visible__()
{
	static void *__hmi_var_76_ptr;
	u8 __hmi_var_76 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_76_ptr));
	static void *__hmi_var_77_ptr;
	u8 __hmi_var_77 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_77_ptr));
	{
#line 1 "控件:text_13,属性:visible"
unsigned char index;
index = __hmi_var_76*4+3;
if(index > __hmi_var_77)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_13_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_13_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_13_text__()
{
	static void *__hmi_var_78_ptr;
	u8 __hmi_var_78 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_78_ptr));
	static void *__hmi_var_79_ptr;
	char * __hmi_var_79 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_79_ptr));
	{
#line 1 "控件:text_13,属性:text"
u8 index;
HISTORY_MSG history_msg;
static char timestr[12];
index = __hmi_var_78*4+3;
memset(timestr , 0 , 12);
if(1 == read_history_info(index , &history_msg))
{
    memcpy(timestr , datetime2str(history_msg.data_time)+5 , 11);//不显示年
    return timestr;
}
return __hmi_var_79;

	}
}

static int widget_set_text_13_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_13_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_12_visible__()
{
	static void *__hmi_var_80_ptr;
	u8 __hmi_var_80 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_80_ptr));
	static void *__hmi_var_81_ptr;
	u8 __hmi_var_81 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_81_ptr));
	{
#line 1 "控件:text_12,属性:visible"
unsigned char index;
index = __hmi_var_80*4+3;
if(index > __hmi_var_81)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_12_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_12_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_12_text__()
{
	static void *__hmi_var_82_ptr;
	u8 __hmi_var_82 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_82_ptr));
	static void *__hmi_var_83_ptr;
	char * __hmi_var_83 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_idle",&__hmi_var_83_ptr));
	static void *__hmi_var_84_ptr;
	char * __hmi_var_84 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_used",&__hmi_var_84_ptr));
	static void *__hmi_var_85_ptr;
	char * __hmi_var_85 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_lock",&__hmi_var_85_ptr));
	static void *__hmi_var_86_ptr;
	char * __hmi_var_86 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_86_ptr));
	{
#line 1 "控件:text_12,属性:text"
u8 index;
HISTORY_MSG history_msg;
index = __hmi_var_82*4+3;
if(1 == read_history_info(index , &history_msg))
{
    switch(history_msg.box_info.status)
    {
        case BOX_IDLE: return __hmi_var_83;
        case BOX_USED: return __hmi_var_84;
        case BOX_LOCK: return __hmi_var_85;
        default : return __hmi_var_86;
    }
}
return __hmi_var_86;

	}
}

static int widget_set_text_12_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_12_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_11_visible__()
{
	static void *__hmi_var_87_ptr;
	u8 __hmi_var_87 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_87_ptr));
	static void *__hmi_var_88_ptr;
	u8 __hmi_var_88 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_88_ptr));
	{
#line 1 "控件:text_11,属性:visible"
unsigned char index;
index = __hmi_var_87*4+3;
if(index > __hmi_var_88)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_11_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_11_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_11_text__()
{
	static void *__hmi_var_89_ptr;
	u8 __hmi_var_89 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_89_ptr));
	{
#line 1 "控件:text_11,属性:text"
u8 index;
HISTORY_MSG history_msg;
static char virturlbuf[5];
index = __hmi_var_89*4+3;
memset(virturlbuf , 0 , 4);
if(1 == read_history_info(index , &history_msg))
{
    memcpy(virturlbuf , history_msg.box_info.virtualnumber , VIRTUAL_NUM_LENGTH);
}
return virturlbuf;

	}
}

static int widget_set_text_11_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_11_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_13_visible__()
{
	static void *__hmi_var_90_ptr;
	u8 __hmi_var_90 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_90_ptr));
	static void *__hmi_var_91_ptr;
	u8 __hmi_var_91 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_91_ptr));
	{
#line 1 "控件:button_13,属性:visible"
unsigned char index;
index = __hmi_var_90*4+2;
if(index > __hmi_var_91)
{
    return 0;
}
return 1;

	}
}

static int widget_set_button_13_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_13_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_10_visible__()
{
	static void *__hmi_var_94_ptr;
	u8 __hmi_var_94 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_94_ptr));
	static void *__hmi_var_95_ptr;
	u8 __hmi_var_95 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_95_ptr));
	{
#line 1 "控件:text_10,属性:visible"
unsigned char index;
index = __hmi_var_94*4+2;
if(index > __hmi_var_95)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_10_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_10_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_10_text__()
{
	static void *__hmi_var_96_ptr;
	u8 __hmi_var_96 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_96_ptr));
	static void *__hmi_var_97_ptr;
	char * __hmi_var_97 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_97_ptr));
	{
#line 1 "控件:text_10,属性:text"
u8 index;
HISTORY_MSG history_msg;
static char timestr[12];
index = __hmi_var_96*4+2;
memset(timestr , 0 , 12);
if(1 == read_history_info(index , &history_msg))
{
    memcpy(timestr , datetime2str(history_msg.data_time)+5 , 11);//不显示年
    return timestr;
}
return __hmi_var_97;

	}
}

static int widget_set_text_10_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_10_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_9_visible__()
{
	static void *__hmi_var_98_ptr;
	u8 __hmi_var_98 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_98_ptr));
	static void *__hmi_var_99_ptr;
	u8 __hmi_var_99 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_99_ptr));
	{
#line 1 "控件:text_9,属性:visible"
unsigned char index;
index = __hmi_var_98*4+2;
if(index > __hmi_var_99)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_9_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_9_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_9_text__()
{
	static void *__hmi_var_100_ptr;
	u8 __hmi_var_100 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_100_ptr));
	static void *__hmi_var_101_ptr;
	char * __hmi_var_101 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_idle",&__hmi_var_101_ptr));
	static void *__hmi_var_102_ptr;
	char * __hmi_var_102 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_used",&__hmi_var_102_ptr));
	static void *__hmi_var_103_ptr;
	char * __hmi_var_103 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_lock",&__hmi_var_103_ptr));
	static void *__hmi_var_104_ptr;
	char * __hmi_var_104 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_104_ptr));
	{
#line 1 "控件:text_9,属性:text"
u8 index;
HISTORY_MSG history_msg;
index = __hmi_var_100*4+2;
if(1 == read_history_info(index , &history_msg))
{
    switch(history_msg.box_info.status)
    {
        case BOX_IDLE: return __hmi_var_101;
        case BOX_USED: return __hmi_var_102;
        case BOX_LOCK: return __hmi_var_103;
        default : return __hmi_var_104;
    }
}
return __hmi_var_104;

	}
}

static int widget_set_text_9_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_9_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_8_visible__()
{
	static void *__hmi_var_105_ptr;
	u8 __hmi_var_105 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_105_ptr));
	static void *__hmi_var_106_ptr;
	u8 __hmi_var_106 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_106_ptr));
	{
#line 1 "控件:text_8,属性:visible"
unsigned char index;
index = __hmi_var_105*4+2;
if(index > __hmi_var_106)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_8_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_8_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_8_text__()
{
	static void *__hmi_var_107_ptr;
	u8 __hmi_var_107 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_107_ptr));
	{
#line 1 "控件:text_8,属性:text"
u8 index;
HISTORY_MSG history_msg;
static char virturlbuf[5];
index = __hmi_var_107*4+2;
memset(virturlbuf , 0 , 4);
if(1 == read_history_info(index , &history_msg))
{
    memcpy(virturlbuf , history_msg.box_info.virtualnumber , VIRTUAL_NUM_LENGTH);
}
return virturlbuf;

	}
}

static int widget_set_text_8_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_8_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_button_12_visible__()
{
	static void *__hmi_var_108_ptr;
	u8 __hmi_var_108 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_108_ptr));
	static void *__hmi_var_109_ptr;
	u8 __hmi_var_109 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_109_ptr));
	{
#line 1 "控件:button_12,属性:visible"
unsigned char index;
index = __hmi_var_108*4+1;
if(index > __hmi_var_109)
{
    return 0;
}
return 1;

	}
}

static int widget_set_button_12_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_button_12_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_7_visible__()
{
	static void *__hmi_var_112_ptr;
	u8 __hmi_var_112 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_112_ptr));
	static void *__hmi_var_113_ptr;
	u8 __hmi_var_113 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_113_ptr));
	{
#line 1 "控件:text_7,属性:visible"
unsigned char index;
index = __hmi_var_112*4+1;
if(index > __hmi_var_113)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_7_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_7_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_7_text__()
{
	static void *__hmi_var_114_ptr;
	u8 __hmi_var_114 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_114_ptr));
	static void *__hmi_var_115_ptr;
	char * __hmi_var_115 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_115_ptr));
	{
#line 1 "控件:text_7,属性:text"
u8 index;
HISTORY_MSG history_msg;
static char timestr[12];
index = __hmi_var_114*4+1;
memset(timestr , 0 , 12);
if(1 == read_history_info(index , &history_msg))
{
    memcpy(timestr , datetime2str(history_msg.data_time)+5 , 11);//不显示年
    return timestr;
}
return __hmi_var_115;

	}
}

static int widget_set_text_7_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_7_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_6_visible__()
{
	static void *__hmi_var_116_ptr;
	u8 __hmi_var_116 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_116_ptr));
	static void *__hmi_var_117_ptr;
	u8 __hmi_var_117 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_117_ptr));
	{
#line 1 "控件:text_6,属性:visible"
unsigned char index;
index = __hmi_var_116*4+1;
if(index > __hmi_var_117)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_6_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_6_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_6_text__()
{
	static void *__hmi_var_118_ptr;
	u8 __hmi_var_118 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_118_ptr));
	static void *__hmi_var_119_ptr;
	char * __hmi_var_119 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_idle",&__hmi_var_119_ptr));
	static void *__hmi_var_120_ptr;
	char * __hmi_var_120 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_used",&__hmi_var_120_ptr));
	static void *__hmi_var_121_ptr;
	char * __hmi_var_121 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_lock",&__hmi_var_121_ptr));
	static void *__hmi_var_122_ptr;
	char * __hmi_var_122 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_122_ptr));
	{
#line 1 "控件:text_6,属性:text"
u8 index;
HISTORY_MSG history_msg;
index = __hmi_var_118*4+1;
if(1 == read_history_info(index , &history_msg))
{
    switch(history_msg.box_info.status)
    {
        case BOX_IDLE: return __hmi_var_119;
        case BOX_USED: return __hmi_var_120;
        case BOX_LOCK: return __hmi_var_121;
        default : return __hmi_var_122;
    }
}
return __hmi_var_122;

	}
}

static int widget_set_text_6_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_6_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static u8 widget_set_text_4_visible__()
{
	static void *__hmi_var_123_ptr;
	u8 __hmi_var_123 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_123_ptr));
	static void *__hmi_var_124_ptr;
	u8 __hmi_var_124 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.win_history_count",&__hmi_var_124_ptr));
	{
#line 1 "控件:text_4,属性:visible"
unsigned char index;
index = __hmi_var_123*4+1;
if(index > __hmi_var_124)
{
    return 0;
}
return 1;

	}
}

static int widget_set_text_4_visible(void *value)
{
	u8 __hmi_retval = (u8)( widget_set_text_4_visible__());
	if (__hmi_retval != (*(u8 *)value))
	{
		(*(u8 *)value) = __hmi_retval;
		return 1;
	}
	return 0;
}

static char * widget_set_text_4_text__()
{
	static void *__hmi_var_125_ptr;
	u8 __hmi_var_125 = (*(u8 *)hmidb_get_data_value_by_ptr("picture_ctrl.page_count",&__hmi_var_125_ptr));
	{
#line 1 "控件:text_4,属性:text"
u8 index;
HISTORY_MSG history_msg;
static char virturlbuf[5];
index = __hmi_var_125*4+1;
memset(virturlbuf , 0 , 4);
if(1 == read_history_info(index , &history_msg))
{
    memcpy(virturlbuf , history_msg.box_info.virtualnumber , VIRTUAL_NUM_LENGTH);
}
return virturlbuf;
	}
}

static int widget_set_text_4_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_4_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

#endif
