/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static void widget_button_12_click(void);
static void widget_button_11_click(void);

hmi_widget_func_t hmi_window_77696E5F7379735F7265736574_event_funcs[]={
{"button_12_click",(void *)widget_button_12_click},
{"button_11_click",(void *)widget_button_11_click},
{NULL,NULL}
};

static void widget_button_12_click(void)
{
	{
#line 1 "控件:button_12,事件:click"
hmi_window_hide("win_sys_reset");

	}
{
}
}

static void widget_button_11_click(void)
{
	u8 __hmi_var_228 = (*(u8 *)hmidb_get_data_value("sys_set.init_flag"));
	u8 __old___hmi_var_228 = __hmi_var_228;
	char * __hmi_var_229 = ((char *)hmidb_get_data_value("picture_ctrl.win_tip"));
		{
#line 1 "控件:button_11,事件:click"
__hmi_var_228 = 0;
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_229);
	if(__old___hmi_var_228 != __hmi_var_228)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_228);
		__old___hmi_var_228 = __hmi_var_228;
	}
}
  
sys_save_params();//保存好系统信息  

    strcpy(__hmi_var_229 , "系统已恢复出厂设置，请重新启动");
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_229);
	if(__old___hmi_var_228 != __hmi_var_228)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_228);
		__old___hmi_var_228 = __hmi_var_228;
	}
}

hmi_window_show("win_tip"); 

	}
{
		hmidb_set_data_value("picture_ctrl.win_tip",__hmi_var_229);
	if(__old___hmi_var_228 != __hmi_var_228)
	{
		hmidb_set_data_value("sys_set.init_flag",&__hmi_var_228);
	}
}
}

#endif
