/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE

hmi_widget_func_t hmi_window_77696E5F696E7075745F73656E645F746D_prop_funcs[]={
{NULL,NULL}
};

#endif
