/*
 * This file is automatically generated by func_gen.c,don't edit
 */

#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include "lincon.h"
#include "linconhmi.h"
#include "userfunc.h"

#ifndef HMI_GEN_FUNC_FILE
static int widget_set_text_9_text(void *value);
static int widget_set_text_8_text(void *value);
static int widget_set_text_7_text(void *value);
static int widget_set_text_5_text(void *value);
static int widget_set_text_4_text(void *value);
static int widget_set_text_3_text(void *value);
static int widget_set_text_2_text(void *value);
static int widget_set_text_text(void *value);

hmi_widget_func_t hmi_window_77696E5F686973746F72795F64657461696C_prop_funcs[]={
{"text_9_text",(void *)widget_set_text_9_text},
{"text_8_text",(void *)widget_set_text_8_text},
{"text_7_text",(void *)widget_set_text_7_text},
{"text_5_text",(void *)widget_set_text_5_text},
{"text_4_text",(void *)widget_set_text_4_text},
{"text_3_text",(void *)widget_set_text_3_text},
{"text_2_text",(void *)widget_set_text_2_text},
{"text_text",(void *)widget_set_text_text},
{NULL,NULL}
};

static int widget_set_text_9_text(void *value)
{
	static void *__hmi_var_127_ptr;
	char * __hmi_var_127 = ((char *)hmidb_get_data_value_by_ptr("box_msg.timestr",&__hmi_var_127_ptr));
#line 1 "控件:text_9,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_127);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_8_text(void *value)
{
	static void *__hmi_var_128_ptr;
	char * __hmi_var_128 = ((char *)hmidb_get_data_value_by_ptr("box_msg.send_id",&__hmi_var_128_ptr));
#line 1 "控件:text_8,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_128);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_7_text(void *value)
{
	static void *__hmi_var_129_ptr;
	char * __hmi_var_129 = ((char *)hmidb_get_data_value_by_ptr("box_msg.send_num",&__hmi_var_129_ptr));
#line 1 "控件:text_7,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_129);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_5_text(void *value)
{
	static void *__hmi_var_130_ptr;
	char * __hmi_var_130 = ((char *)hmidb_get_data_value_by_ptr("box_msg.user_phnum",&__hmi_var_130_ptr));
#line 1 "控件:text_5,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_130);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_4_text(void *value)
{
	static void *__hmi_var_131_ptr;
	char * __hmi_var_131 = ((char *)hmidb_get_data_value_by_ptr("box_msg.user_id",&__hmi_var_131_ptr));
#line 1 "控件:text_4,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_131);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static char * widget_set_text_3_text__()
{
	static void *__hmi_var_132_ptr;
	char __hmi_var_132 = (*(char *)hmidb_get_data_value_by_ptr("box_msg.status",&__hmi_var_132_ptr));
	static void *__hmi_var_133_ptr;
	char * __hmi_var_133 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_idle",&__hmi_var_133_ptr));
	static void *__hmi_var_134_ptr;
	char * __hmi_var_134 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_used",&__hmi_var_134_ptr));
	static void *__hmi_var_135_ptr;
	char * __hmi_var_135 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.history_lock",&__hmi_var_135_ptr));
	static void *__hmi_var_136_ptr;
	char * __hmi_var_136 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_136_ptr));
	{
#line 1 "控件:text_3,属性:text"
    switch(__hmi_var_132)
    {
        case BOX_IDLE: return __hmi_var_133;
        case BOX_USED: return __hmi_var_134;
        case BOX_LOCK: return __hmi_var_135;
        default : return __hmi_var_136;
    }

	}
}

static int widget_set_text_3_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_3_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static char * widget_set_text_2_text__()
{
	static void *__hmi_var_137_ptr;
	char __hmi_var_137 = (*(char *)hmidb_get_data_value_by_ptr("box_msg.type",&__hmi_var_137_ptr));
	static void *__hmi_var_138_ptr;
	char * __hmi_var_138 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_min",&__hmi_var_138_ptr));
	static void *__hmi_var_139_ptr;
	char * __hmi_var_139 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_mid",&__hmi_var_139_ptr));
	static void *__hmi_var_140_ptr;
	char * __hmi_var_140 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_max",&__hmi_var_140_ptr));
	static void *__hmi_var_141_ptr;
	char * __hmi_var_141 = ((char *)hmidb_get_data_value_by_ptr("picture_ctrl.box_err",&__hmi_var_141_ptr));
	{
#line 1 "控件:text_2,属性:text"
switch(__hmi_var_137)
{
    case BOX_TYPE_MIN: return __hmi_var_138;
    case BOX_TYPE_MID: return __hmi_var_139;
    case BOX_TYPE_MAX: return __hmi_var_140;
    default : return __hmi_var_141;
}


	}
}

static int widget_set_text_2_text(void *value)
{
	char * __hmi_retval = (char *)( widget_set_text_2_text__());
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

static int widget_set_text_text(void *value)
{
	static void *__hmi_var_142_ptr;
	char * __hmi_var_142 = ((char *)hmidb_get_data_value_by_ptr("box_msg.virtualnumber",&__hmi_var_142_ptr));
#line 1 "控件:text,属性:text"
	char * __hmi_retval = (char *)(__hmi_var_142);
	if ( strcmp(__hmi_retval, (char *)value))
	{
		strncpy(value,__hmi_retval,32);
		((char *)value)[32-1]=0;
		return 1;
	}
	return 0;
}

#endif
